### ISSUE TITLE
get the total height of pdf document

### ISSUE THREAD

**Issue by Dante3887** [barteksc/AndroidPdfViewer#1001]
Hello, I am a beginner on developing android app.
And now I am trying to add a button on the pdfview, since I have been successful to merge pdfview into scrollview after getting help from #396 
And how should I get the height of the pdfview since I always get 0 when using PDFView.height??

```
val PDFView = binding.pdfView
       PDFView.fromAsset("secrets.pdf").onTap(OnTapListen()).enableSwipe(true)
            .swipeHorizontal(false).pageFitPolicy(FitPolicy.BOTH).load()
```
        //Wrong Height
        val height = PDFView.height
        
        PDFView.getViewTreeObserver()
            .addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
                @Override
                override fun onGlobalLayout() {
                    PDFView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                    val params: ViewGroup.LayoutParams = PDFView.getLayoutParams();
                    params.width = Resources.getSystem().displayMetrics.widthPixels;
                    //should not be fixed height
                    params.height = 10000;
                    PDFView.setLayoutParams(params);

                }

            });

**Comment by DoveBarnett** [comment]
请问，现在能正确获取PDF的高度了吗？

**Comment by DoveBarnett** [comment]
请问，现在能正确获取pdf的高度了吗？

**Comment by DoveBarnett** [comment]
Can you get the PDF height correctly now?

**Comment by bhavinatharva** [comment]
I have solve it using this 


```
 private fun adjustPdfViewHeight(numberOfPages: Int) {
        binding.pdfView.viewTreeObserver.addOnGlobalLayoutListener(object :
            ViewTreeObserver.OnGlobalLayoutListener {
            override fun onGlobalLayout() {
                binding.pdfView.viewTreeObserver.removeOnGlobalLayoutListener(this)

                val pageWidth = binding.pdfView.measuredWidth
                var totalHeight = 0

                // Loop through each page to calculate its height
                for (i in 0 until numberOfPages) {
                    val pageSize = binding.pdfView.getPageSize(i)
                    val pageHeightRatio = pageSize.height / pageSize.width
                    val pageHeight = (pageWidth * pageHeightRatio).toInt()

                    totalHeight += pageHeight
                }

                val layoutParams = binding.pdfView.layoutParams as LinearLayout.LayoutParams
                layoutParams.height = totalHeight
                binding.pdfView.layoutParams = layoutParams
            }
        })
    }
```
