### ISSUE TITLE
Some tiles don't be created and displayed

### ISSUE THREAD

**Issue by santinoc** [barteksc/AndroidPdfViewer#102]
In a horizontal swipe mode when the PDF (3 A4 pages) fills the screen with 2 1/2 pages; some areas will be drawn with the thumb instead of the page.
I disabled thumb draw, insert some log.e in the code and I see that some tiles are never requested.
I think that MathUtil.floor seem not correct because for some values generate 2 times the same columns.
In order to reproduce the bug, set the tile size to 100, increase the cache size and display a pdf on a large device so you can see 2 or more pages. The 3rd and the 5th columns of the second page are not displayed until you zoom or scroll by some pixel.

**Comment by ThePaulrBear** [comment]
This was fixed in a recent commit.
