### ISSUE TITLE
Hyperlinks don't work for api 30 and above

### ISSUE THREAD

**Issue by perdix1975** [barteksc/AndroidPdfViewer#1075]
Hyperlinks are functional if the in the build.gradle, in the field defaultConfig we put targetSdk 29.
However, Google Play Store doesn't allow targetSdk less than 30.
Can anyone fix this?

**Comment by HylkeB** [comment]
I updated to version 3.2.0-beta.1 and that solved it for me.

**Comment by perdix1975** [comment]
Well, I also have 3.2.0-beta.1 but at my Samsung A70 (Android 11), hyperlinks pointing to YouTube, don't work...

**Comment by perdix1975** [comment]
I have found the solution for my problem at
https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30
The accepted answer solved my problem!
