### ISSUE TITLE
Antialiasing problem ?

### ISSUE THREAD

**Issue by lezardos** [barteksc/AndroidPdfViewer#108]
Hi,

I have build the sample app, but I have a quality problem. 

Do you have any idea why ?

Thanks in advance !

![screenshot_pdfium](https://cloud.githubusercontent.com/assets/5501874/18863884/eb8933fc-8493-11e6-8928-7b5a5bcf9879.png)

**Comment by TheMaxCoder** [comment]
the library itself works perfect, but PDF might be of low quality, you should try another PDF.

**Comment by matav** [comment]
I have same problem. Antialiasing or bad zoom step?

![screenshot_20161010-232238](https://cloud.githubusercontent.com/assets/11376359/19251673/ca898c94-8f40-11e6-8b62-a6bb97e65e8d.png)

![screenshot_20161010-232942](https://cloud.githubusercontent.com/assets/11376359/19251835/b6940556-8f41-11e6-9939-686753e2896a.png)

![screenshot_20161010-232922](https://cloud.githubusercontent.com/assets/11376359/19251840/b9b5e38a-8f41-11e6-8e01-277489d694e4.png)

Original: 
[pokusne02.pdf](https://github.com/barteksc/AndroidPdfViewer/files/520469/pokusne02.pdf)
[pokusne01.pdf](https://github.com/barteksc/AndroidPdfViewer/files/520470/pokusne01.pdf)

**Comment by aneddamattia** [comment]
I have the same problem, in my case I created the PDF with itext library, after the creation the PDF is opened with this library, the text is rendered not well, i don't understand why,

**Comment by barteksc** [comment]
Version 2.5.0 introduced `Configurator.enableAntialiasing(true)` which may fix the problem, otherwise there is no more I can do.
