### ISSUE TITLE
Alkme41470@gmail.com 

### ISSUE THREAD

**Issue by alkme41470** [barteksc/AndroidPdfViewer#1085]
Alkme41470@gmail.com

**Comment by ehsan951** [comment]
دریافت Outlook برای Android<https://aka.ms/AAb9ysg>
________________________________
From: alkme41470 ***@***.***>
Sent: Saturday, May 7, 2022 9:24:51 AM
To: barteksc/AndroidPdfViewer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [barteksc/AndroidPdfViewer] ***@***.*** (Issue #1085)


***@***.******@***.***>
