### ISSUE TITLE
flip animation

### ISSUE THREAD

**Issue by arifcebe** [barteksc/AndroidPdfViewer#11]
how can i add flip animation like google play book? i try some library but i can't get animation like google play book. i put animation on onPageChange.

**Comment by barteksc** [comment]
I'm afraid it's not possible, it would require rebuilding whole rendering engine.

**Comment by arifcebe** [comment]
ohh.. i see, that's need more time and effort. thank you for your explanation. as an alternative, now i'm just try some animation library

**Comment by umarF** [comment]
Sad that it can't have animation like flip and curl, otherwise it's perfect !
