### ISSUE TITLE
Scroll every page

### ISSUE THREAD

**Issue by WBlackstorm** [barteksc/AndroidPdfViewer#110]
I can`t scroll every page of pdf view. Scroll happens directly and it sounds bad...

**Comment by CrisBarreiro** [comment]
Can you please post a code snippet so we can try to see what's going wrong?

**Comment by WBlackstorm** [comment]
@CrisBarreiro Older versions of this lib it was possible scroll pages one per time, now page scroll is continuous. Did you understand? I would like to scroll page per page, but I can't

**Comment by barteksc** [comment]
There is no such possibility in version 2.x, you can use 1.x

**Comment by Abdullah2993** [comment]
It would be really nice to swipe to the next page instead of going through multiple pages with one swipe

**Comment by nicholashartono** [comment]
can you make a method to make the new version implement one page scroll per swipe?

**Comment by XCarbone** [comment]
Can you at least give us an hint on how to do it ?
