### ISSUE TITLE
Library is not supporting JDK 11 & above

### ISSUE THREAD

**Issue by morevishal06** [barteksc/AndroidPdfViewer#1115]
We want to update our android application to Android 13 for which JDK 11 is must. However, com.github.barteksc:android-pdf-viewer:2.8.2 does not support JDK 11. Can you please provide solution on this?

**Comment by AndreBlumenthal** [comment]
I am here, because I have an sdk that requests the version `2.8.2` but it cannot find it. And it seems there is no version `2.8.2`. Did this version get removed somehow or did it never exists? Do I miss something?

**Comment by morevishal06** [comment]
![image](https://user-images.githubusercontent.com/95213747/195532699-38770345-d0ac-4302-bc1a-6679582f53e4.png)
Its there on https://github.com/barteksc/AndroidPdfViewer/

**Comment by AndreBlumenthal** [comment]
Not it is working. For me it was just temporarily unavailable I guess. Sorry for interrupting your request here
