### ISSUE TITLE
getPageCount returns 0

### ISSUE THREAD

**Issue by ammaratef45** [barteksc/AndroidPdfViewer#113]
I want to get the count of pages for the file but it returns 0 when i use getPageCount method
How to solve this issue?

**Comment by ochkarik05** [comment]
I think you should completely load document first.

```
         pdfView.fromFile(pdf)
                .onLoad(new OnLoadCompleteListener() {
                    @Override
                    public void loadComplete(int nbPages) {

                        Log.d(TAG, "loadComplete: " + nbPages);

                        Log.d(TAG, "pages count: " + pdfView.getPageCount());

                    }
                })
                .load();

```

**Comment by grommel435** [comment]
getPageCount() method doesn't return PDF's pageCount
after the PDF file is completely loaded.

ochkarik05's example return NaN in my app.

The method returns 0 or NaN.

**Comment by grommel435** [comment]
getPageCount() method doesn't return PDF's page correctely.
 after the PDF file is completely loaded.

ochkarik05's example also returns 0.

The method returns 0.

In the library the pageCount is the length of Array (PDF pages array I think).
There is a line that array A = array B (array B is passed by)
and this could be a reason that method always return 0.

**Comment by ammaratef45** [comment]
ochkarik05's worked ... it is okay thanks
