### ISSUE TITLE
Cant import the project 

### ISSUE THREAD

**Issue by lloretf** [barteksc/AndroidPdfViewer#1146]
Hi, I put the line in the dependencies my project sync without error but I can't import the project on my classes it make "Cannot resolve symbol GitHub" . I already try to invalidate caches, nothing change

**Comment by zer0Ambit1on** [comment]
how did you solve that issue?

**Comment by lloretf** [comment]
> how did you solve that issue?

As I recall, my primary difficulty stemmed from the fact that in my settings.gradle, I only imported mavenCentral. When I tried to add jcenter, Android Studio advised me to replace jcenter with mavenCentral. However, making this substitution resulted in AndroidPdfViewer ceasing to function properly. Hence, my recommendation would be to ensure that you have included jcenter.

![image](https://github.com/barteksc/AndroidPdfViewer/assets/97182834/319db2d6-2630-47b4-9842-659a129f9291)
