### ISSUE TITLE
How to disable/enable zooming

### ISSUE THREAD

**Issue by AhmadullahSaikat** [barteksc/AndroidPdfViewer#118]
How can I disable/enable 
- pinch zooming

**Comment by barteksc** [comment]
Currently there is no such possibility.

**Comment by bonyhardian** [comment]
Add this code in onCreate:
Constants.Pinch.MINIMUM_ZOOM = 1;
Constants.Pinch.MAXIMUM_ZOOM = 1;

For disable double tap:
pdfView.fromAsset(SAMPLE_FILE)
.......
.enableDoubletap(false)
.load();
