### ISSUE TITLE
Split pages visually after rendering

### ISSUE THREAD

**Issue by Knarff** [barteksc/AndroidPdfViewer#119]
First of all your library is awesome! But I have one issue:
Is it possible to draw a gap between the pages of a pdf? Or maybe something like a CardView.
Actually the pages fuse into eachother and it is hard to see where one page ends and another page starts. 
Thanks in advance

**Comment by adisiji** [comment]
Yes. can we add gap between pages ? Thanks
Cheers!

**Comment by alansong** [comment]
is there any solution for this issue? it is really critical for us... Thanks.

**Comment by Stefantost** [comment]
I have the same requirement. I took this way:

Set onDraw-Listener:
```
        pdfView.fromFile(new File(getPathFromIntentExtras()))
                .enableSwipe(true)
                .swipeHorizontal(true)
                .onDraw(this)
                .load();
```

Implement like this:
```
    @Override
    public void onLayerDrawn(Canvas canvas, float pageWidth, float pageHeight, int displayedPage) {
            canvas.drawLine(0, 0, pageWidth, 0, paint);
            canvas.drawLine(0, pageHeight, pageWidth, pageHeight, paint);
            canvas.drawLine(0, 0, 0, pageHeight, paint);
            canvas.drawLine(pageWidth, 0, pageWidth, pageHeight, paint);
    }
```

However, it is only working correctly for horizontal scrolling...  Still searching for a way to do this in vertical mode.

**Comment by Stefantost** [comment]
For vertical scrolling mode the implementation looks like this:
```
 @Override
    public void onLayerDrawn(Canvas canvas, float pageWidth, float pageHeight, int page) {

        float xLeft = -1 * page * pageWidth;
        float yTop = page * pageHeight;
        float xRight = (-1 * page * pageWidth) + pageWidth;
        float yBottom = (page + 1) * pageHeight;

        //Top:
        canvas.drawLine(xLeft, yTop, xRight, yTop, paint);
        //Bottom:
        canvas.drawLine(xLeft, yBottom, xRight, yBottom, paint);
        //Left:
        canvas.drawLine(xLeft, yTop, xLeft, yBottom, paint);
        //Right:
        canvas.drawLine(xRight, yTop, xRight, yBottom, paint);

    }
```

**Comment by Knarff** [comment]
@Stefantost  Thanks for your solution. It is one way to split the pages visually.
But imo a gap with an elevation of each page or something like that would look more like an document viewer.

**Comment by Stefantost** [comment]
Hi @Knarff! Of course this is just a basic solution. You could also draw a "background" and "shadow"-lines on top of the pages to simulate an elevation. However this will "eat" some space of the pages.
I think you can not set a background for the pages or set a spacing between them.

**Comment by clarknt** [comment]
Thanks @Stefantost. Expanded a bit on vertical solution to get a border around all pages instead of current page only.

Limitations:
- Vertical page display only
- Does not work with mixed portrait/landscape (though PDFView 2.3.0 does seem to display mixed orientation as all portrait or all landscape anyway)
```
@Override
public void onLayerDrawn(Canvas canvas, float pageWidth, float pageHeight, int displayedPage) {
    // set a margin, otherwise depending on device resolution, border is not displayed (falls outside the component)
    final float MARGIN = 1f;
    // compute coordinates
    float xLeft = (-1f * displayedPage * pageWidth) + MARGIN;
    float xRight = (-1f * displayedPage * pageWidth) + pageWidth - MARGIN;
    float yGlobalTop = MARGIN;
    float yGlobalBottom = ((float) pdfView.getPageCount() * pageHeight) - MARGIN;
    float yTop = (displayedPage * pageHeight) + MARGIN;
    float yBottom = ((displayedPage + 1f) * pageHeight) - MARGIN;
    // left vertical border
    canvas.drawLine(xLeft,  yGlobalTop, xLeft,  yGlobalBottom, paint);
    // right vertical border
    canvas.drawLine(xRight,  yGlobalTop, xRight,  yGlobalBottom, paint);
    // top origin horizontal border
    canvas.drawLine(xLeft,  yGlobalTop, xRight,  yGlobalTop, paint);
    // bottom horizontal border up to current page - 2
    for (int loopPage = 0; loopPage < (displayedPage - 1) && loopPage < pdfView.getPageCount(); loopPage++) {
        float yLoopEnd = ((loopPage + 1f) * pageHeight) - MARGIN;
        canvas.drawLine(xLeft,  yLoopEnd, xRight,  yLoopEnd, paint);
    }
    // top and bottom horizontal borders for current page
    // not in the loop to have correct borders when display page fills the screen
    canvas.drawLine(xLeft,  yTop, xRight,  yTop, paint);
    canvas.drawLine(xLeft,  yBottom, xRight,  yBottom, paint);
    // bottom horizontal border up to last page
    for (int loopPage = displayedPage + 1; loopPage < pdfView.getPageCount(); loopPage++) {
        float yLoopEnd = ((loopPage + 1f) * pageHeight) - MARGIN;
        canvas.drawLine(xLeft,  yLoopEnd, xRight,  yLoopEnd, paint);
    }
}
```
There is probably a cleaner way to do that though.

**Comment by MonaHammad** [comment]
what is the paint you are using here?

**Comment by clarknt** [comment]
It's a android.graphics.Paint, with just a Color set.

**Comment by MonaHammad** [comment]
Ok,thanks @clarknt 
this is the object in the PDFView class right?
then you override onLayerDrawn in the PDFView class?

**Comment by clarknt** [comment]
It's a onDrawListener set with pdfView.onDraw(yourListener), see Stefantost message above.

**Comment by AkashiTetsuya** [comment]
it was crush coz of null object reference.How I can fix?

**Comment by 1stmetro** [comment]
fixed page borders on my fork.. in case you want to add page markers

**Comment by Knarff** [comment]
Looks awesome in 2.7.0-beta.1

**Comment by NaseerAttari** [comment]
try this for Split pages visually
https://github.com/barteksc/AndroidPdfViewer/issues/719#issuecomment-445702797
cheers!
