### ISSUE TITLE
Support for hyperlinks

### ISSUE THREAD

**Issue by gizm090** [barteksc/AndroidPdfViewer#120]
Is it possible (or will be in future) to use hyperlinks internal and external inside pdf files? 

I believe currently the library is ignoring hyperlinks.

**Comment by barteksc** [comment]
There is no support for hyperlinks and won't be added in the near future.

**Comment by venkatdesireddy1993** [comment]
Can you provide hyperlinks support, then only it will be helpful to most of android developers. Or is there any library to support hyperlinks and open pdf file within app like our library.
