### ISSUE TITLE
PDF versions supported ?

### ISSUE THREAD

**Issue by BapNesS** [barteksc/AndroidPdfViewer#121]
Hi,

I guess it's not an technical issue as it use to be but it's more like a question.

Which versions of PDF version are supported by this lib ?

I've found 10 versions :
- (1993) PDF **1.0** / Acrobat 1.0
- (1994) PDF **1.1** / Acrobat 2.0
- (1996) PDF **1.2** / Acrobat 3.0
- (1999) PDF **1.3** / Acrobat 4.0
- (2001) PDF **1.4** / Acrobat 5.0
- (2003) PDF **1.5** / Acrobat 6.0
- (2005) PDF **1.6** / Acrobat 7.0
- (2006) PDF **1.7** / Acrobat 8.0
- (2008) PDF **1.7**, Adobe Extension Level 3, Acrobat 9.0
- (2009) PDF **1.7**, Adobe Extension Level 5, Acrobat 9.1

**Comment by barteksc** [comment]
This library uses Pdfium lib for decoding PDF documents, but unfortunately I don't know which versions are supported. Good news is that I exported PDFs from many different apps and all have worked.

**Comment by BapNesS** [comment]
Okay thanks a lot !

It could be useful to know more about this point or at least add this kind of information on the repo documentation. :-)
