### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by vadol** [barteksc/AndroidPdfViewer#134]
FileNotFoundException: No content provider: http://partners.adobe.com/public/developer/en/xml/AdobeXMLFormsSamples.pdf

When load pdf from uri that time come issues

**Comment by vadol** [comment]
`public class MainActivity extends AppCompatActivity implements OnPageChangeListener, OnLoadCompleteListener {

    PDFView mPdfView;
    Integer pageNumber = 0;
    TextView mTextView;
    public static final String SAMPLE_FILE = "Samples.pdf";
    @Override

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        init();
//        mPdfView.fromAsset(SAMPLE_FILE)
//                .defaultPage(pageNumber)
//                .onPageChange(this)
//                .enableAnnotationRendering(true)
//                .onLoad(this)
//                .load();

        mPdfView.fromUri(Uri.parse("http://partners.adobe.com/public/developer/en/xml/AdobeXMLFormsSamples.pdf"))
                .defaultPage(pageNumber)
                .onPageChange(this)
                .enableAnnotationRendering(true)
                .onLoad(this)
                .load();
    }

    private void init() {
        mPdfView = (PDFView) findViewById(R.id.pdfView);
        mTextView = (TextView) findViewById(R.id.text_page);
    }

    @Override
    public void loadComplete(int nbPages) {
        PdfDocument.Meta meta = mPdfView.getDocumentMeta();
        Log.e(getClass().getSimpleName(), "title = " + meta.getTitle());
       

    }

    @Override
    public void onPageChanged(int page, int pageCount) {

        pageNumber = page;
        mTextView.setText("" + (page + 1) + "/" + pageCount);


    }
}
`

When put pdf in assets folder run  with out error

**Comment by barteksc** [comment]
Use search, it was asked many times. This library does not support remote files.
