### ISSUE TITLE
Documentation for version 1.4.0

### ISSUE THREAD

**Issue by senhor** [barteksc/AndroidPdfViewer#139]
Because of version 1.4.0 being way better than current version can you add a link for documentation of version 1.4.0?

**Comment by senhor** [comment]
As I experienced, older versions have better rendering, better swiping, better experience. It would be way better to add scrollHandler and fling functions to older versions instead of working on current one.

**Comment by janvde** [comment]
I agree. I liked the 1.x version better, because it was faster. Only thing I like better in the current version is the possibility to scroll to a next page while zoomed in.

**Comment by barteksc** [comment]
Every release is tagged on this repo, so source code and docs for 1.4 version is available on tag 1.4

**Comment by barteksc** [comment]
I've moved version 1.x to new repo [AndroidPdfViewerV1](https://github.com/barteksc/AndroidPdfViewerV1).
I have no idea how ScrollHandle should work on previous version, when you are scrolling page by page.

**Comment by senhor** [comment]
Thanks for your response, I will do my best to implement missing functions, if you have any points that you think should be covered, make me know.
