### ISSUE TITLE
App crashes after opening a splashscreen

### ISSUE THREAD

**Issue by adnan6434** [barteksc/AndroidPdfViewer#146]
the app crashes as the splashscreen can not start the PDFViewActivity . Is there any other way to add a splashscreen in the app? It would be very kind of you if you provide  a quick reply

**Comment by barteksc** [comment]
What splashscreen?

**Comment by adnan6434** [comment]
I added a custom splashscreen , at the end of the splashscreen activity , i created an intent to start the PDFViewActivity , but for some reason the PDFViewActivity does not start

**Comment by barteksc** [comment]
What does it mean "does not start"? Some logs, code, anything?

**Comment by adnan6434** [comment]
[splashscreen.txt](https://github.com/barteksc/AndroidPdfViewer/files/607443/splashscreen.txt)
[Manifest.txt](https://github.com/barteksc/AndroidPdfViewer/files/607445/Manifest.txt)

**Comment by adnan6434** [comment]
Is there any generalized way to add splashscreen to the sample app?

**Comment by barteksc** [comment]
You are starting activity from non-ui thread, probably that makes problem. Also, `Splashscreen.this.finish();` executes twice. You didn't show logs from logcat. Splashscreen is not related to this library, so look for help on stackoverflow or others.

**Comment by adnan6434** [comment]
`11-23 02:06:04.468 23628-23628/? I/art: Late-enabling -Xcheck:jni
11-23 02:06:04.531 23628-23628/com.github.barteksc.sample D/Proxy: setHttpRequestCheckHandler
11-23 02:06:04.542 23628-23628/com.github.barteksc.sample I/InstantRun: Instant Run Runtime started. Android package is com.github.barteksc.sample, real application class is null.
11-23 02:06:04.599 23628-23628/com.github.barteksc.sample D/ActivityThread: BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{342585cc com.github.barteksc.sample}}
11-23 02:06:04.599 23628-23628/com.github.barteksc.sample V/ActivityThread: Handling launch of ActivityRecord{2a865015 token=android.os.BinderProxy@cd4af2a {com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}}
11-23 02:06:04.648 23628-23628/com.github.barteksc.sample V/ActivityThread: ActivityRecord{2a865015 token=android.os.BinderProxy@cd4af2a {com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}}: app=android.app.Application@350b32b8, appName=com.github.barteksc.sample, pkg=com.github.barteksc.sample, comp={com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}, dir=/data/app/com.github.barteksc.sample-2/base.apk
11-23 02:06:04.738 23628-23628/com.github.barteksc.sample V/ActivityThread: Performing resume of ActivityRecord{2a865015 token=android.os.BinderProxy@cd4af2a {com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}}
11-23 02:06:04.738 23628-23628/com.github.barteksc.sample D/ActivityThread: ACT-AM_ON_RESUME_CALLED ActivityRecord{2a865015 token=android.os.BinderProxy@cd4af2a {com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}}
11-23 02:06:04.739 23628-23628/com.github.barteksc.sample V/ActivityThread: Resume ActivityRecord{2a865015 token=android.os.BinderProxy@cd4af2a {com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}} started activity: false, hideForNow: false, finished: false
11-23 02:06:04.739 23628-23628/com.github.barteksc.sample V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{3188d891 I.E..... R.....ID 0,0-0,0}
11-23 02:06:04.747 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: initialize DisplayEventReceiver 0xb8611710
11-23 02:06:04.747 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: Render dirty regions requested: false
11-23 02:06:04.755 23628-23628/com.github.barteksc.sample D/GraphicBuffer: register, handle(0xb862a4b0) (w:768 h:768 s:768 f:0x1 u:0x000100)
11-23 02:06:04.756 23628-23628/com.github.barteksc.sample D/Atlas: Validating map...
11-23 02:06:04.760 23628-23628/com.github.barteksc.sample V/ActivityThread: Resuming ActivityRecord{2a865015 token=android.os.BinderProxy@cd4af2a {com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}} with isForward=true
11-23 02:06:04.760 23628-23628/com.github.barteksc.sample V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{1d0f36da com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{3188d891 V.E..... R.....ID 0,0-0,0}
11-23 02:06:04.760 23628-23628/com.github.barteksc.sample V/ActivityThread: Scheduling idle handler for ActivityRecord{2a865015 token=android.os.BinderProxy@cd4af2a {com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}}
11-23 02:06:04.761 23628-23628/com.github.barteksc.sample D/ActivityThread: ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{2a865015 token=android.os.BinderProxy@cd4af2a {com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}}
11-23 02:06:04.786 23628-23656/com.github.barteksc.sample E/[DRVB][EXT][UTIL]: disp_only_chk: DRVB CHECK DISP PROCESS DONE ! (1/0x2f/0x30/0x2e)
11-23 02:06:04.786 23628-23656/com.github.barteksc.sample E/[DRVB][EXT][UTIL]: disp_only_chk: DRVB CHECK DISP PROCESS DONE ! (720/1280/1)
11-23 02:06:04.789 23628-23656/com.github.barteksc.sample I/OpenGLRenderer: Initialized EGL, version 1.4
11-23 02:06:04.791 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: Enabling debug mode 0
11-23 02:06:04.792 23628-23656/com.github.barteksc.sample I/[MALI][Gralloc]: dlopen libsec_mem.so fail
11-23 02:06:04.798 23628-23656/com.github.barteksc.sample D/GraphicBuffer: register, handle(0xb8644fa8) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:04.799 23628-23656/com.github.barteksc.sample I/MaliEGL: [Mali]window_type=1, is_framebuffer=0, errnum = 0
11-23 02:06:04.799 23628-23656/com.github.barteksc.sample I/MaliEGL: [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
11-23 02:06:04.799 23628-23656/com.github.barteksc.sample I/MaliEGL: [Mali]max_allowed_dequeued_buffers=3
11-23 02:06:04.800 23628-23656/com.github.barteksc.sample D/GraphicBuffer: unregister, handle(0xb8644fa8) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:04.803 23628-23656/com.github.barteksc.sample D/GraphicBuffer: register, handle(0xb8645fb8) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:04.832 23628-23628/com.github.barteksc.sample V/InputMethodManager: onWindowFocus: null softInputMode=288 first=true flags=#81810100
11-23 02:06:04.832 23628-23628/com.github.barteksc.sample V/InputMethodManager: START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{3188d891 V.E..... R.....ID 0,0-720,1280} ic=null tba=android.view.inputmethod.EditorInfo@9fade00 controlFlags=#104
11-23 02:06:04.860 23628-23656/com.github.barteksc.sample D/GraphicBuffer: register, handle(0xb864ddf8) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:04.868 23628-23656/com.github.barteksc.sample D/GraphicBuffer: register, handle(0xb8651ad0) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:04.877 23628-23656/com.github.barteksc.sample D/GraphicBuffer: register, handle(0xb86465a8) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:05.062 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: DisplayEventReceiver 0xb8611710 requestNextVsync
11-23 02:06:05.068 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: DisplayEventReceiver 0xb8611710 latestVsyncEvent 19570541506116
11-23 02:06:08.252 23628-23655/com.github.barteksc.sample E/AndroidRuntime: FATAL EXCEPTION: Thread-2451
                                                                            Process: com.github.barteksc.sample, PID: 23628
                                                                            android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.barteksc.sample/com.github.barteksc.sample.PDFViewActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                                at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1767)
                                                                                at android.app.Instrumentation.execStartActivity(Instrumentation.java:1491)
                                                                                at android.app.Activity.startActivityForResult(Activity.java:3769)
                                                                                at android.app.Activity.startActivityForResult(Activity.java:3730)
                                                                                at android.app.Activity.startActivity(Activity.java:4040)
                                                                                at android.app.Activity.startActivity(Activity.java:4008)
                                                                                at com.github.barteksc.sample.Splashscreen$1.run(Splashscreen.java:52)
11-23 02:06:08.297 23628-23628/com.github.barteksc.sample D/ActivityThread: ACT-AM_ON_PAUSE_CALLED ActivityRecord{2a865015 token=android.os.BinderProxy@cd4af2a {com.github.barteksc.sample/com.github.barteksc.sample.Splashscreen}}
11-23 02:06:08.318 23628-23628/com.github.barteksc.sample D/ActivityThread: ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@cd4af2a
11-23 02:06:08.747 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: Flushing caches (mode 0)
11-23 02:06:08.747 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: Flushing caches (mode 0)
11-23 02:06:08.747 23628-23656/com.github.barteksc.sample D/GraphicBuffer: unregister, handle(0xb8645fb8) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:08.749 23628-23656/com.github.barteksc.sample D/GraphicBuffer: unregister, handle(0xb864ddf8) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:08.750 23628-23656/com.github.barteksc.sample D/GraphicBuffer: unregister, handle(0xb8651ad0) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:08.751 23628-23656/com.github.barteksc.sample D/GraphicBuffer: unregister, handle(0xb86465a8) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
11-23 02:06:08.946 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: Flushing caches (mode 1)
11-23 02:06:08.956 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: Flushing caches (mode 0)
11-23 02:06:08.956 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: Flushing caches (mode 0)
11-23 02:06:09.005 23628-23628/com.github.barteksc.sample D/ActivityThread: ACT-DESTROY_ACTIVITY handled : 1 / android.os.BinderProxy@cd4af2a
11-23 02:06:13.972 23628-23656/com.github.barteksc.sample D/OpenGLRenderer: Flushing caches (
mode 0)
`
Here's the log ,  android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.barteksc.sample/com.github.barteksc.sample.PDFViewActivity};

**Comment by adnan6434** [comment]
And i forgot to thank you for prompt reply , Thanks a Lot :) :+1:

**Comment by barteksc** [comment]
`android.content.ActivityNotFoundException: Unable to find explicit activity class {com.github.barteksc.sample/com.github.barteksc.sample.PDFViewActivity}; have you declared this activity in your AndroidManifest.xml?` Most important part, use PdfViewActivity_

**Comment by adnan6434** [comment]
Did that from start but no got  change

**Comment by barteksc** [comment]
You pass `PdfViewActivity` to `new Intent(...)` but you have to pass  `PdfViewActivity_`

**Comment by adnan6434** [comment]
I feel very stupid right now. Thanks a lot mate , you are a legend :100:
