### ISSUE TITLE
Fille corrupted when loading pdf files from the Android Device folder

### ISSUE THREAD

**Issue by sssvrock** [barteksc/AndroidPdfViewer#15]
I have done as below:
- Directory: pdf_file
- pdf files: page.pdf, page2.pdf
- Permission for file access in manifest file

When I am trying to render the pdf file, below crash is not allowing to render

**06-25 12:04:46.229 20365-20365/? I/applock: launch broadcast taken: com.joanzapata.pdfview.sample
06-25 12:04:46.291 19545-19545/? D/pdf file path:: /storage/emulated/0/pdf_files/page1.pdf
06-25 12:04:46.297 19545-19560/? D/PdfDroid: initializing PdfRender JNI library based on MuPDF
06-25 12:04:46.303 19545-19560/? I/PdfDroid: Corrupted file '/storage/emulated/0/pdf_files/page1.pdf', trying to repair
06-25 12:04:46.303 19545-19560/? D/PdfDroid: Exception 'java/lang/RuntimeException', Message: 'PDF file is corrupted'
06-25 12:04:46.303 19545-19560/? D/PdfDroid: PdfDocument.nativeOpen(): return handle = 0x74f5211050**

I tried to render using other applications adobe etc... its good to go and render smoothly

Can you please provide or suggest me what is happening here?

Thanks

**Comment by barteksc** [comment]
Stacktrace clearly shows that you are not using this library, but android-pdfview...
