### ISSUE TITLE
can't dispaly this pdf 

### ISSUE THREAD

**Issue by philos3** [barteksc/AndroidPdfViewer#152]
can't dispaly this pdf   "http://7xwqut.com2.z0.glb.qiniucdn.com/20160928191134_video.pdf"

**Comment by barteksc** [comment]
What does it mean "can't display"?

**Comment by philos3** [comment]
download the PDF to the loacal from this URL "http://7xwqut.com2.z0.glb.qiniucdn.com/20160928191134_video.pdf"，and then i put this pdf into the assets folder, I use the under code to load the pdf


public static final String SAMPLE_FILE = "20160928191134_video.pdf";

  pdfView.fromAsset(SAMPLE_FILE)
                .defaultPage(pageNumber)
                .onPageChange(this)
                .enableAnnotationRendering(true)
                .onError(this)
                .onLoad(this)
                .scrollHandle(new DefaultScrollHandle(context))
                .load();

but it shows nothing.......    and then  i replace it with another  pdf  which copy from your sample, it works well .
there is nothing difference between  the pdfs, both of them work well in windows 
so,what is the problem?  how can I solve this

**Comment by barteksc** [comment]
@philos3 Unfortunately I cannot reproduce this problem. I own 4 Android devices and I don't have any problem opening this document.
