### ISSUE TITLE
Render landscape pdf

### ISSUE THREAD

**Issue by ScheNi** [barteksc/AndroidPdfViewer#153]
My application requests a generated pdf from a back-end. This pdf can either be a landscape or portait (A4 format) pdf, according to a template that the customer uses for this. But I'm having issues rendering this landscape pdf, text overlaps other text and it doesn't get completely rendered. Are there any known solutions for this? I couldn't manage to find one. 

Thanks

**Comment by ScheNi** [comment]
If you need some more information or an example, please tell me.

**Comment by barteksc** [comment]
More information will be useful - some screen, document, example and more

**Comment by ScheNi** [comment]
Sorry, I just found out it's not an issue of this library. When I was loading an example landscape pdf from the assets I noticed that this one got rendered properly. I found out that the downloaded pdf file, that had the problems, doesn't get saved properly.
