### ISSUE TITLE
Ugly rendering during scale

### ISSUE THREAD

**Issue by hansinator85** [barteksc/AndroidPdfViewer#156]
Hi,

I would like to have an option, to disable the rendering during scaling.
On current devices, the View is rendering like crazy when scaling in or out.

As far as I have figured out, the DragPinchManager fires to the ScaleGestureDetector which is handled in onScaleBegin, onScaleEnd, onScale. But it also fires to the GestureDetector, which additionaly detects a scroll which is then handled in onScroll ... and onScroll calls loadPageByOffset().
Therefore it is always rendering while actually scaling.

It would be great to either disable this at all, or to make it configurable and have an option like:
`mPdfView.enableRenderDuringScale(false);`

On older Devices (< API 19) the GestureDetector does not fire onScroll when more than 1 pointer is currently down - so on older devices it already has my favoured behaviour, which looks much smoother as the view is only rendered once after onScaleEnd.

**Comment by barteksc** [comment]
Resolved in version 2.4.0
