### ISSUE TITLE
Rendering quality when zooming/dezooming

### ISSUE THREAD

**Issue by aurelhubert** [barteksc/AndroidPdfViewer#16]
First, thank you very much for your work, I think a lot of people are waiting for a library like yours.

I was wondering if it could be possible to improve the render when loading the tiles? I have noticed that the library displays bad quality of the tiles when "re-calculating" the render for the given zoom (I suppose!). You'll find a screenshot in attachment.

Thank you,

![untitled](https://cloud.githubusercontent.com/assets/4895410/16377848/ac18680a-3c68-11e6-9d8c-8c241b8597e9.png)

**Comment by sssvrock** [comment]
Hi barteksc,

Thanks for providing library, I wondered after seeing this library but disappointed about rendering quality when zoom in and out. If any possibility to avoid this black glitch and make it smooth that ll be help fun

- Can we load pdf with full or max pixel so that it won't take that much render effect and ll be smooth?
- Can we reduce or refresh till pdf seems good to read?

Hi @aurelhubert if you find any solutions for this please let me know :) 

Please clear my doubts and may be useful for others also.



Thanks
Vinod

**Comment by sgueniot** [comment]
Hi, 
you can change com.github.barteksc.pdfviewer.utilConstants.THUMBNAIL_RATIO value to 1f to improve it.

**Comment by sssvrock** [comment]
Hi Sgueniot,

  I tried with above solution, Great man, awesome solution Thanks for your valuable reply and you saved my time.

Thanks

**Comment by aurelhubert** [comment]
@sgueniot it seems clearly better, thanks for the advice 👍

**Comment by sgueniot** [comment]
You're welcome

**Comment by barteksc** [comment]
Be careful with changing THUMBNAIL_RATIO, it may slow down less efficient devices.

**Comment by aurelhubert** [comment]
@barteksc I will try to find the best ratio between quality & perf (maybe it's already done with the original value). Thanks again for your work 👍

**Comment by sssvrock** [comment]
Hi @barteksc as you mentioned I am changing the THUMBNAIL_RATIO, it is slowing down and causing error some times like : too much work on main (UI) thread. so I am reverting back to 0.5 from 1.

and how can I fit the pdf view to the device screen, by default it is not fittings and in zoomed state it is not navigating to other pdf files in my view pager.

Please suggest me how can I achieve my goal.

Thanks

**Comment by aurelhubert** [comment]
Please consider not using a closed issue to ask new questions. You already have commented this one: #4. Create a new issue if necessary, thanks.

**Comment by sssvrock** [comment]
OK, I ll make sure to follow your words

**Comment by soniamelimu** [comment]
Hi barteksc,

Great PDF code. Font quality is not good when rendering the pdf. When using it on phone the text is not visible. Please help.

**Comment by barteksc** [comment]
@soniamelimu Could you attach some screens?

**Comment by soniamelimu** [comment]
Thanks for your reply. Attached is the screen-shot. Not able to clear text of the pdf in normal mode without zoom. Please help.
![issue1](https://cloud.githubusercontent.com/assets/22980948/24286923/54d1b16e-109d-11e7-87d9-067e78b39804.png)

**Comment by barteksc** [comment]
What is resolution of this device? Did you use `.enableAntialiasing(true)`?

**Comment by soniamelimu** [comment]
No I haven't used it. Below are the details of device- 

Resolution - 1280*800
Density group - 213dpi (x1.3312501)
Density Code - tvdpi
Android version- 4.4.2
API level - 17

Thanks
Sonia

**Comment by soniamelimu** [comment]
Please help on this issue.

**Comment by barteksc** [comment]
Did you try using antialiasing?

**Comment by soniamelimu** [comment]
No. I haven't.

**Comment by FilCZ** [comment]
Hi, I have the same issue and I tried to use  `.enableAntialiasing(true)`, but it looks like the PDFView class doesn't have this metod.
