### ISSUE TITLE
Hyperlinks not loading in pdf view

### ISSUE THREAD

**Issue by venkatdesireddy1993** [barteksc/AndroidPdfViewer#165]
In pdf view we have hyper links which needs to be open in browser while click on that hyperlink.

**Comment by venkatdesireddy1993** [comment]
Can you provide hyperlinks support, then only it will be helpful to most of android developers. Or is there any library to support hyperlinks and open pdf file within app like our library.

**Comment by barteksc** [comment]
It is not easy to introduce hyperlinks support so it won't be implemented in the near future. There are some paid libraries that should be able to open hyperlinks.
