### ISSUE TITLE
Scroll one Page

### ISSUE THREAD

**Issue by mobilestar0223** [barteksc/AndroidPdfViewer#167]
I try to scroll one page per swipe.
When I swipe once, several pages are scrolled.
It works well in 1.x, but there is content rendering problem in 1.x.
So I choose 2.x, but have problem like this.
I'm very trouble and confused about this.
Please let me know how can I fix it.
Thanks

**Comment by barteksc** [comment]
Version 2.x does not have page by page swipe functionality, so to use this feature you should stay with 1.x
