### ISSUE TITLE
Issue rendering

### ISSUE THREAD

**Issue by campcoxconsultants** [barteksc/AndroidPdfViewer#168]
I am seeing what appear to be missing scan lines.  Any suggestions?  This is not scanned, but it appears the same when zoomed.

<img width="329" alt="screen shot 2016-12-25 at 6 14 31 pm" src="https://cloud.githubusercontent.com/assets/20117209/21473210/0cf1a760-cace-11e6-80bf-fc82a744cf86.png">

vs a normal (non android) viewer
<img width="603" alt="screen shot 2016-12-25 at 6 15 46 pm" src="https://cloud.githubusercontent.com/assets/20117209/21473214/3482e76c-cace-11e6-99da-23493b9a2a54.png">

I am using:
        pdfView.useBestQuality(true);
        pdfView.fromFile(file)
                .defaultPage(0)
                .onPageChange(this)
                .enableAnnotationRendering(true)
                .onLoad(this)
                .scrollHandle(new DefaultScrollHandle(this))
                //.enableDoubletap(false)
                .load();
        pdfView.useBestQuality(true); // Not sure if it should be before or after so trying both

**Comment by majkimester** [comment]
Enable antialiasing for rendering as I described in #191.

**Comment by barteksc** [comment]
Try using `Configurator.enableAntialiasing(true)`, which implements solution from #191
