### ISSUE TITLE
Failing to build my app with 2.3.0 version

### ISSUE THREAD

**Issue by hargagan** [barteksc/AndroidPdfViewer#170]
I have given this in my build.gradle file 

dependencies {
    repositories {
        jcenter()
    }

    compile ('com.github.barteksc:android-pdf-viewer:2.3.0')
}

It is pulling the required dependency of com.android.support:21.0.3 but it fails further while building with this error ==

AGPBI: {"kind":"error","text":"Error converting bytecode to dex:\nCause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;","sources":[{}],"original":"UNEXPECTED TOP-LEVEL EXCEPTION:\ncom.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;\n\tat com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)\n\tat com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)\n\tat com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)\n\tat com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)\n\tat com.android.dx.merge.DexMerger.merge(DexMerger.java:188)\n\tat com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)\n\tat com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)\n\tat com.android.dx.command.dexer.Main.run(Main.java:277)\n\tat com.android.dx.command.dexer.Main.main(Main.java:245)\n\tat com.android.dx.command.Main.main(Main.java:106)\n","tool":"Dex"}

I noticed that in the path 'build/intermediates/exploded-aar/com.android.support/support-v4/21.0.3/jars' there is a 'classes.jar' and under this there is a 'libs' directory which has 'internal_impl-21.0.3.jar'. When I see the content of this using 'mc' command on linux, it is showing similar list of '.class' files (there are few of them I could see, if not all). You should be able to tell more.

I tried, 'multipledexenabled true' setting in 'defaultConfig' but that doesn't help either.

If I add 'exclude' in the 'compile' tag mentioned about for 'com.android.support' there is a runtime exception of 
E/PDFView: load pdf error
           java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
               at com.shockwave.pdfium.PdfDocument.<init>(PdfDocument.java:84)
               at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:104)
               at com.github.barteksc.pdfviewer.source.UriSource.createDocument(UriSource.java:38)
               at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:49)
               at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
               at android.os.AsyncTask$2.call(AsyncTask.java:304)

One other point : I have to use gradle version as 2.1.3, but if I update it to 2.2.1 (suggested by android studio), it builds fine and app comes up clean without any need to add 'exclude' and no runtime error too.

I am new to the understanding of build of android, so not able to move any further. Please help. Is there a setting in build.gradle that I should do to come out of this error. Or there is some other setting along with the one mentioned above, that I should do to correct this build error of multiple dex file.

**Comment by hargagan** [comment]
should I download the project and add it as a  library ?

**Comment by hargagan** [comment]
Please let me know what other information is required from my side to give some directions for me ? I am eagerly looking for help here. Thanks.

**Comment by barteksc** [comment]
If you have to use old gradle then try adding this library as a module
