### ISSUE TITLE
how can I see bookmarks list?

### ISSUE THREAD

**Issue by ismly** [barteksc/AndroidPdfViewer#171]
how can I see bookmarks list of my pdf?

**Comment by barteksc** [comment]
Check sample in this repository

**Comment by ismly** [comment]
installed apk of code. but in app, I dont know what to do show bookmarks.

**Comment by barteksc** [comment]
You have to render it somewhere by yourself.

**Comment by ismly** [comment]
but how? I cant see any code on sample file, or any info on documentation.. 😀

**Comment by barteksc** [comment]
There is no any method for rendering bookmarks list. Get bookmarks using `pdfView.getTableOfContents()` and display it using some Android views.

**Comment by KnIfER** [comment]
[This](https://github.com/KnIfER/PolymPic) WIP project supports bookmark display.  Help me star it and I'll help figure it out.

![SVID_20201122_214248_1_GifNo 0](https://user-images.githubusercontent.com/11593903/100048752-ec379f00-2e58-11eb-8f66-eb4e4a46881a.gif)
