### ISSUE TITLE
Signatures + images

### ISSUE THREAD

**Issue by pickett2k** [barteksc/AndroidPdfViewer#177]
Any glance of adding support to insert signatures and images?? Would make it one of the best out there with those things implemented

**Comment by barteksc** [comment]
It is only reader, I don't plan implementing any features that modify PDF documents.

**Comment by TechnologyMaster** [comment]
@barteksc  many developer use your library. and of course it is good and fast library to read the pdf doc in android app , it would be helpful to all developer if you think and implement the code to edit the PDF library . I also want to edit but find no method. think it and do if possible.

**Comment by SayedTalha** [comment]
> @barteksc many developer use your library. and of course it is good and fast library to read the pdf doc in android app , it would be helpful to all developer if you think and implement the code to edit the PDF library . I also want to edit but find no method. think it and do if possible.

Same here man I wish he will worked it on
