### ISSUE TITLE
Error - File is empty

### ISSUE THREAD

**Issue by andrejunges** [barteksc/AndroidPdfViewer#179]
Hey guys,

Im getting the error `File is empty` when I try to display some pdf files (it just happens in some of the files). 
However, if I load the pdf file from that path separately, it loads just fine.
I noticed its related to the file's size - in my tests files larger than 300mb were not opening.

Any idea what might be causing this?

**Comment by barteksc** [comment]
What was the issue?

**Comment by andrejunges** [comment]
Actually the problem was in my code. 
I was trying to read and visualize the PDF before the file creations completed.
My service that created the file was returning its path before the promise resolves. So in some light files the file creation was fast enough and had time to close the file before AndroidPdfViewer tried to read it. But for heavier files that small window of time wasn't enough.

**Comment by barteksc** [comment]
Thanks for description, it may help other people facing similar issue.
