### ISSUE TITLE
Event for page rendering complete?

### ISSUE THREAD

**Issue by Jaeder42** [barteksc/AndroidPdfViewer#185]
I am using the viewer to create an e-paper reader. But if you scroll through the pages too fast it crashes (fata signal 11). It seems to work when I limit the user to only turn pages every 500 ms. 

This makes me think that the renderer is trying to render to a PDFView that no longer exists or is already rendering. So an event that tells me when a page is done rendering might help.

Thanks,
Johan

**Comment by 1stmetro** [comment]
look at onLoad() its the listener for loading the document.

Regards

Andrew

**Comment by Jaeder42** [comment]
@1stmetro the onLoad() event is triggered when the document has loaded, what I am looking for is an event that is triggered once the page has finished rendering.

**Comment by AchesKkk** [comment]
have you solved it? sometimes i find it renders too slow and then the page is blank...

**Comment by Jaeder42** [comment]
No, my temporary solution is to block pageswapping for 500 ms

**Comment by barteksc** [comment]
Version 2.5.0 introduces `Configurator.onRender()`, it should meet your requirements

**Comment by Jaeder42** [comment]
@barteksc Thank you it solved my issue!

**Comment by barteksc** [comment]
@Jaeder42 Great :)
