### ISSUE TITLE
Is there a function to go to page using pageidx

### ISSUE THREAD

**Issue by dbkonxepts** [barteksc/AndroidPdfViewer#187]
Is there a function to go to a certain page using pageidx

**Comment by barteksc** [comment]
Use `pdfView.jumpTo(idx);`

**Comment by dbkonxepts** [comment]
Thanks but actually what I want is an example to read bookmarks from pdfview. Because using the getTableofConents isn't working for me.

**Comment by barteksc** [comment]
What does it mean "isn't working for me"?

**Comment by dbkonxepts** [comment]
What I mean is it's returning an empty bookmark array. Whereas the PDF file has bookmarks. Because I checked using Adobe Reader. So I just wanted to know if I am doing it wongly.
Here is an excerpt of what my code looks like.

```
pdfView.fromasset("file.pdf");
for(int i = 0 ; i < pdfView.getTableOfContent().size ; i++)
{
    Toast.show();
}
```
Point is that am getting an empty array.

**Comment by dbkonxepts** [comment]
Please I really need to get the bookmarks of a pdf
