### ISSUE TITLE
Bookmarks in PDF file

### ISSUE THREAD

**Issue by dbkonxepts** [barteksc/AndroidPdfViewer#189]
Please is there a proper procedure to get the Bookmarks in a PDF file. Because it is not working. 
Here is my code.
```
pdfview.fromAssets("pdf_file")
          .load();
pdfview.getTableofContents().size();  // Returns 0. (Zero)
```

**Comment by barteksc** [comment]
If it is not working for you, there is nothing I can do. Bookmarks are read by Pdfium, which is big C library maintained by Google.

**Comment by dbkonxepts** [comment]
Alright thanks.  Cheers.
