### ISSUE TITLE
Error opening pdf

### ISSUE THREAD

**Issue by Radeonisos** [barteksc/AndroidPdfViewer#194]
Hello

I have a pdf to /storage/emulated/0/testthreepdf/prog.pdf and i verify with my file explore. I write this : 

`pdfView.fromAsset("/storage/emulated/0/testthreepdf/prog.pdf")
                .defaultPage(pageNumber)
                .onPageChange(this)
                .enableAnnotationRendering(true)
                .onLoad(this)
                .scrollHandle(new DefaultScrollHandle(getContext()))
                .load();`

but he doesn't works : "FileNotFoundException: /storage/emulated/0/testthreepdf/prog.pdf does not exist."
Help me plz

**Comment by Gericop** [comment]
That is not an asset, you need `fromFile(new File("/storage/emulated/0/testthreepdf/prog.pdf"))` for that.

**Comment by Radeonisos** [comment]
thanks for your help. 
I try and i have this : 
Can't create handler inside thread that has not called Looper.prepare()

**Comment by Gericop** [comment]
You have to call all of this from your main (UI) thread.

**Comment by Radeonisos** [comment]
ohhhh sorry i forgot that it's works thanks 👍
