### ISSUE TITLE
option to swipe left or right to move between pages

### ISSUE THREAD

**Issue by LanmanGroup** [barteksc/AndroidPdfViewer#198]
is there an option to swipe left or right to move between pages?

**Comment by barteksc** [comment]
It is stated in README, use `.swipeHorizontal(true)`

**Comment by LanmanGroup** [comment]
with `.swipeHorizontal(true)` you can move between pages but the redaer not change one page but "scrool" between pages

**Comment by barteksc** [comment]
There is no such possibility, you may use [AndroidPdfViewerV1](https://github.com/barteksc/AndroidPdfViewerV1)
