### ISSUE TITLE
Get Bitmaps from every page of PDF file

### ISSUE THREAD

**Issue by Garrus007** [barteksc/AndroidPdfViewer#20]
Is there any way to get `Bitmap` from every page of PDF file? I need to render pdf and also get Bitmaps to do some extra operations with them (e.g. save). 

There is `onLayerDrawn` event, but it call not only once, but every time pdf is scrolled.

I know, that storing many Bitmaps in memory is not good idea, but it is important feature and will work for files with a few pages.

**Comment by barteksc** [comment]
Library does not render whole page as one bitmap, so you can't do that. Only possibility is to use PdfiumAndroid itself and manually render page to bitmap e.g. on page change.

**Comment by Garrus007** [comment]
Do you know how to do this? Or what I can read to learn something about it?

**Comment by barteksc** [comment]
PdfiumAndroid on Github - https://github.com/barteksc/PdfiumAndroid

**Comment by Garrus007** [comment]
Thank you!
