### ISSUE TITLE
Multiple APKs per architectures

### ISSUE THREAD

**Issue by djsbaa** [barteksc/AndroidPdfViewer#202]
Any one can help us of how to build multiple APKs per each architectures to reduce APK size!

**Comment by barteksc** [comment]
There is a link with instruction in README

**Comment by djsbaa** [comment]
I saw it but its complicated.
I don't *.so file; I find it but I don't think is a good idea to copy it in jiniLibs, In addition to that when I generate APKs its give me more than 200 APKs. 
So what I do I follow the google guide and finally I got what I want; here is how

`
splits {
        density {
            enable true
        }
        abi{
            enable true
            universalApk true
        }
    }
`

**Comment by spfannemueller** [comment]
This is what I've got and what is working pretty well:

`splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a' //select ABIs to build APKs for
            universalApk true //generate an additional APK that contains all the ABIs
        }
    }

    // map for the version code
    project.ext.versionCodes = ['armeabi': 4, 'armeabi-v7a': 5, 'arm64-v8a': 6, 'x86': 7, 'x86_64': 8]

    android.applicationVariants.all { variant ->
        // assign different version code for each output
        variant.outputs.each { output ->
            output.versionCodeOverride = project.ext.versionCodes.get(output.getFilter(com.android.build.OutputFile.ABI), 0) * 1000000 + android.defaultConfig.versionCode
        }
    }`

This well create 4 APKs for armeabi-v7a, arm64-v8a, x86 7, x86_64 architectures and automatically assign different Version-Codes to each of them so you're able to upload them into the PlayStore.

**Comment by djsbaa** [comment]
Thanks  '**spfannemueller**' that really what  I did,
but what about density and how PlayStore work with it
when I enable density it generate about 57 APKs including a universal one.

**Comment by barteksc** [comment]
Sorry, but this is not library related problem. When you use native libraries, you can place all of them in one APK (which causes size increase) or split by architecture.
