### ISSUE TITLE
How to view pdf from internet?

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [barteksc/AndroidPdfViewer#204]
Is there any way to view pdf using web url?

**Comment by barteksc** [comment]
You have to download pdf by yourself

**Comment by Ekalips** [comment]
You can use retrofit InputStream to view it like this pdfView.fromStream(response.body().byteStream())

**Comment by barteksc** [comment]
@Ekalips You should be careful with this method, `pdfView.fromStream()` read whole stream to bytearray (as native lib cannot receive Java streams), so some larger documents can crash your app with `OutOfMemoryError`. There is no built-in method to read from web.

**Comment by Ekalips** [comment]
@barteksc You see, there is no problem in reading from steam, there is enough RAM to store PDF document. OOM occurs only when you start to scroll like a mad man.
