### ISSUE TITLE
Fragment orientation leaves bottom border on full screen su

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#209]
When i change the device orientation and go full screen within a fragment i get a bottom border i cant figure out where its coming from and how to remove it.

Or how do you force pdfview to fill screen...?

This is the code to go full screen within my fragment the removal of the appbarlayout leaves the bottom gap.

 AppBarLayout appbar = (AppBarLayout) findViewById(R.id.appbar);
    appbar.setVisibility(View.GONE);

WindowManager.LayoutParams.FLAG_FULLSCREEN);
    getWindow().getDecorView().setSystemUiVisibility(
                      View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                    | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                    | View.SYSTEM_UI_FLAG_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_IMMERSIVE);

Anyone have any ideals?

**Comment by bestbobgit** [comment]
private void setFullscreen(boolean fullScreen) {
        WindowManager.LayoutParams lp = getWindow().getAttributes();
        if (fullScreen) {
            SizeUtil.hideNavigationBar(this);

            lp.flags |= WindowManager.LayoutParams.FLAG_FULLSCREEN;
            getWindow().setAttributes(lp);
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
        } else {
            SizeUtil.displayNavigationBar(this);

            lp.flags &= (~WindowManager.LayoutParams.FLAG_FULLSCREEN);
            getWindow().setAttributes(lp);
            getWindow().clearFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
        }
 }

**Comment by bestbobgit** [comment]
`private void setFullscreen(boolean fullScreen) {
        WindowManager.LayoutParams lp = getWindow().getAttributes();
        if (fullScreen) {
            SizeUtil.hideNavigationBar(this);

            lp.flags |= WindowManager.LayoutParams.FLAG_FULLSCREEN;
            getWindow().setAttributes(lp);
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
        } else {
            SizeUtil.displayNavigationBar(this);

            lp.flags &= (~WindowManager.LayoutParams.FLAG_FULLSCREEN);
            getWindow().setAttributes(lp);
            getWindow().clearFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
        }
 }`

**Comment by bestbobgit** [comment]
```
private void setFullscreen(boolean fullScreen) {
        WindowManager.LayoutParams lp = getWindow().getAttributes();
        if (fullScreen) {
            SizeUtil.hideNavigationBar(this);

            lp.flags |= WindowManager.LayoutParams.FLAG_FULLSCREEN;
            getWindow().setAttributes(lp);
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
        } else {
            SizeUtil.displayNavigationBar(this);

            lp.flags &= (~WindowManager.LayoutParams.FLAG_FULLSCREEN);
            getWindow().setAttributes(lp);
            getWindow().clearFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
        }
 }

**Comment by bestbobgit** [comment]
```
public static void hideNavigationBar(Activity activity) {
        View decorView = activity.getWindow().getDecorView();
        int systemUiVisibility = decorView.getSystemUiVisibility();

        if (Build.VERSION.SDK_INT >= 14) {
            systemUiVisibility ^= View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
        }

        if (Build.VERSION.SDK_INT >= 18) {
            systemUiVisibility ^= View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
        }

        decorView.setSystemUiVisibility(systemUiVisibility);
    }

public static void displayNavigationBar(Activity activity) {
        View decorView = activity.getWindow().getDecorView();
        int systemUiVisibility = decorView.getSystemUiVisibility();

        if (Build.VERSION.SDK_INT >= 14) {
            systemUiVisibility = View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                    | View.SYSTEM_UI_FLAG_VISIBLE;
        }

        decorView.setSystemUiVisibility(systemUiVisibility);
    }

**Comment by 1stmetro** [comment]
Many thanks will try your code later
