### ISSUE TITLE
Question: Does this library have the ability to get the PDF metadata?

### ISSUE THREAD

**Issue by NightSkyDev** [barteksc/AndroidPdfViewer#21]
I need to get the PDF metadata, such as Title, author, etc.  I didn't see a way to get it with this library, but just want to ask in case I missed it.

Thanks!

-Rick

**Comment by barteksc** [comment]
Currently it's not possible to get metadata, but it's good idea to add such feature.

**Comment by NightSkyDev** [comment]
Ok, thanks for the response!

**Comment by barteksc** [comment]
Support for metadata added in version 1.2.0.

**Comment by NightSkyDev** [comment]
Thanks @barteksc!  Great addition to your library.
