### ISSUE TITLE
Pinch Zoom limit ?

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#211]
Does anyone know if there is a limit on the pinch to zoom amount,

Barteksc can this be added or shall i add and post the code ?

The more you zoom the slower the cpu gets on moving around when zoomed in so putting the limit on the pinch zoom amount will be a way of limiting how slow the ui will get.

**Comment by barteksc** [comment]
Yes, you can set maximum zoom to `Constants.Pinch.MAXIMUM_ZOOM`
