### ISSUE TITLE
Not displaying fields

### ISSUE THREAD

**Issue by david1542** [barteksc/AndroidPdfViewer#215]
I have a pdf document which I want to display in my android app.

The document is created using PDFBox. Then I'd like to present to the user the document he has
just created.

My problem is the PDFView doesn't present the fields. It just displays the template document, without all the dynamic data that the user has entered.

For comparison, when I open the resulted document in any kind of PDF reader, it displays it perfectly. No errors or corrupted file.

Why is this happening?

**Comment by david1542** [comment]
I figured this out. I just needed to set enableAnnotationRendering to true and it solved the problem :)

**Comment by barteksc** [comment]
Ok :)
