### ISSUE TITLE
i getting this error when i try open the pdf

### ISSUE THREAD

**Issue by Kharlos** [barteksc/AndroidPdfViewer#218]
E/UncaughtException: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0 at com.github.barteksc.pdfviewer.PDFView.loadComplete(PDFView.java:682) at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:63) at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:25) at android.os.AsyncTask.finish(AsyncTask.java:660) at android.os.AsyncTask.-wrap1(AsyncTask.java) at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6077) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

private static File getOutputMediaFile(String imgName, String subpath){

        //File mediaStorageDir = new File(Environment.getExternalStoragePublicDirectory("CAOAV"), "pdf");
        String root = Environment.getExternalStorageDirectory().toString();
        File mediaStorageDir = new File(root + "/myapptest/" + subpath);

        if (!mediaStorageDir.exists()){
            if (!mediaStorageDir.mkdirs()){
               	Log.d("error","creating dir failed");
            }
        }

	File localFile = new File(mediaStorageDir.getAbsolutePath() +"/"+ imgName);
	pdfView.fromFile(object)
		                    .pages()
		                    .enableSwipe(true)
		                    .swipeHorizontal(false)
		                    .enableDoubletap(true)
		                    .defaultPage(0)
		                    .onError(new OnErrorListener() {
		                        @Override
		                        public void onError(Throwable t) {
		                            Log.d("Error",t.toString());
		                        }
		                    })
		                    .enableAnnotationRendering(false)
		                    .password(null)
		                    .scrollHandle(null)
		                    .load();
		            progressBar.setVisibility(View.GONE);
    }

**Comment by 1stmetro** [comment]
Did you notice the following lines, 

File localFile = new File(mediaStorageDir.getAbsolutePath() +"/"+ imgName);
pdfView.fromFile(object)

guess it should be

pdfView.fromFile(localFile)

**Comment by Kharlos** [comment]
ty that works

**Comment by zhangxu0401** [comment]
remove  .pages()
