### ISSUE TITLE
Performance issue when use pdfView.fromStream()

### ISSUE THREAD

**Issue by JiangGuangyuan** [barteksc/AndroidPdfViewer#222]
Hi,
I try to load a PDF file which the size is almost 70MB by pdfView.fromStream()...load();
But it hardly to load successfully,it seems that it has a performance limit.
So dear PDFViewer developer,is there a solution for this case?
Thank you.

**Comment by barteksc** [comment]
Stream is written to bytearray, because native code cannot use Java Streams
