### ISSUE TITLE
Hi How can we use it for reading a book format like user swipe to goto next page......not to show all pages in List

### ISSUE THREAD

**Issue by Farrukh381** [barteksc/AndroidPdfViewer#224]

**Comment by barteksc** [comment]
You can use `.swipeHorizontal(true)` or disable swiping with `.enableSwipe(false)`, recognize gestures and programmatically changing page.

**Comment by Farrukh381** [comment]
Thanks for Quick Reply.......How can we put animation on page Swipe.......And how text can copy be copied......And Highlighting options etc? like i want to make good Book Reading Experience with your great Work......Looking forward for your suggestions
Thanks

**Comment by barteksc** [comment]
This is simple lib for rendering pdf documents, there is no text selection or highlighting. Animations are in `AnimationManager` class, maybe you will find it useful.

**Comment by Farrukh381** [comment]
so it can't be used suitable for pdf base books .....what you recommend?

**Comment by 1stmetro** [comment]
I can get pdfView to swipe sideways, although i have an issue with lag when i do this but not spent any time on it.

The end of the day pdfView is for reading PDF's if you want magic moving pages then you would have to build your own animations hence the animationManager.

I guess any open source pdf reader would also require coding to get the magic pages to turn, maybe not to hard to implement i imagine its a case of turning the screen as a bitmap.

**Comment by barteksc** [comment]
@Farrukh381 It can be used as a base, but you have to put some work. There is only one another free PDF rendering library called MuPDF, distributed under GPL license, but again, it is not designed as book reader.

**Comment by KnIfER** [comment]
too complex to becom a base...

@Farrukh381 I can give you some ideas. I am using the framework of subsmapling-scale-imagview to display pdf files, showing all pages as an oversized picture. If you want some "slide show" effect, then just display one page at a time and hold multiple such "subsmapling-scale-imagview"s in a horizontal viewpager !

In this way,  you can achieve results similar to photo viewers like QuickPic.

Also, Text selection and manipulation is easy and possible, within less than 4000 lines of code, and just a work of three days. 

https://github.com/KnIfER/PolymPic
