### ISSUE TITLE
I can't load the file

### ISSUE THREAD

**Issue by JoanFaFr** [barteksc/AndroidPdfViewer#225]
I use this code but dosn't work:
pdfView = (PDFView) findViewById(R.id.pdfView);
InputStream file = getResources().openRawResource(R.raw.test);
pdfView.fromStream(file);
pdfView.enableDoubletap(true);
pdfView.enableAnnotationRendering(false);
boolean ad  = pdfView.documentFitsView();
pdfView.loadPages();

documentFitsView return false. Im doing something wrong?

**Comment by barteksc** [comment]
Yes, gou code is wrong, please refer to README and demo app
