### ISSUE TITLE
pdfview  can support web link? 

### ISSUE THREAD

**Issue by myxfeng** [barteksc/AndroidPdfViewer#227]
pdfview  can support web link?

**Comment by barteksc** [comment]
Unfortunately ther is no support for links and currently I do not plan it.

**Comment by myxfeng** [comment]
why pdfview can not supoort link?

**Comment by barteksc** [comment]
It is not implemented

**Comment by juhasuni** [comment]
I've implemented support for links and I'll submit PRs for the required changes. Of course it is up to @barteksc to accept them.
