### ISSUE TITLE
FitToWidth() method would be nice

### ISSUE THREAD

**Issue by Papabrose** [barteksc/AndroidPdfViewer#231]
Hello,

A suggestion I have would be to add a fit to width method that can zoom/resize the document to be the width of the parent window so that people don't have to zoom in to see the text on the phone. Currently right now I am just doing a .zoomTo(3f). Wondering if there is a better way to do it.

**Comment by 1stmetro** [comment]
use the event below and add your own code to resize on load, seems a few people struggle doing this.

.onLoad(new OnLoadCompleteListener() {
                                    @Override
                                    public void loadComplete(int nbPages) {

**Comment by Papabrose** [comment]
Yeah I ended up doing that and got it to work I just thing it would be a nice feature to have a method that does it for me :) Its really a first world problem but is one of the things that would make this pdfviewer feel like it is well featured.

**Comment by 1stmetro** [comment]
once you get the screen width, the center its just a case of zoomto that point on the screen its not something every one wants so i guess its not included otherwise it will be asked how do i remove this feature etc.

Plus its a learning experience !
