### ISSUE TITLE
BUG : Moving once Zoomed UI Lag.

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#234]
I finally got to the bottom of the lagging issue but not had time to play with any code but now i have located the issue its just a case of fixing it.

To replicate the lagging issue zoom into a PDF and try to move left or right you will notice the screen moves slightly and stops, try again and it will do the same and makes you think the device is lagging, so you try to alter things to make the device work faster, smaller pdf, etc but it wont make it work any better.

Now do the same again zoom into the PDF but this time move your finger diagonally and you will notice that the PDF movies with no lag, once you stop moving the PDF try again to move left or right and will notice the PDF moves slightly and stops as in the test above, so the fix currently is don't drag left or right use a diagonal motion when dragging.

**Now the race is on to fix this bug eh ?**

**Comment by 1stmetro** [comment]
@barteksc is there a simply way to sort the dragging left to right, i have been through lots of functions in the source trying to locate the correct function but i cant seem to locate the function and cure the issue?

**Comment by barteksc** [comment]
@1stmetro Can this issue be solved?
