### ISSUE TITLE
meizu 魅蓝E打开下面的pdf文件不能正常显示

### ISSUE THREAD

**Issue by hwahwahwa** [barteksc/AndroidPdfViewer#239]
有一个pdf文件，meizu 魅蓝E打开下面的pdf文件不能正常显示

**Comment by barteksc** [comment]
Sorry, I don't understand this language

**Comment by 1stmetro** [comment]
translated to : 

There is a pdf file, meizu charm blue E open the following pdf file can not be displayed properly

**Comment by barteksc** [comment]
Closing due to author's inactivity
