### ISSUE TITLE
Auto size pdf width on orientation, page change, etc - Complete Fix Here !!

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#241]
Over the past few weeks lots of people are asking how to auto width the display on rotation, or even upon loading as its not done for you.

Some say please create a function, well here is the answer and it will also work on selected pages.

Cant see what all the fuss was about but im sure a few people will be wanting this code.

Enjoy !

.onLoad(new OnLoadCompleteListener() {
                                    @Override
                                    public void loadComplete(int nbPages) {
                                        int cPos=0;
                                        int centerPos=pdfView.getPageAtPositionOffset(cPos);
                                        float pageWidth = pdfView.getOptimalPageWidth();
                                        float viewWidth = pdfView.getWidth();
                                        pdfView.zoomTo(viewWidth / pageWidth);
                                        pdfView.setPositionOffset(centerPos);
                                        pdfView.jumpTo(pageNumber);
                                        pdfView.loadPages();

                                    }
                                })

**Comment by barteksc** [comment]
Thanks, I will add this as option to new version, which is coming soon

**Comment by 1stmetro** [comment]
Does the new version address the left and right dragging while zoomed?

**Comment by barteksc** [comment]
Problem is, that I cannot reproduce it on any of my devices

**Comment by 1stmetro** [comment]
Strange I have seen a few people who have posted simular issues, it will drag a tiny bit and stop but drag diagonal and it works fine, same will horizontal pages can only move page on a diagonal swipe.

**Comment by 1stmetro** [comment]
If I add a system.out.print to i think it was the moverelativeto function side swipes print once where as a diagonal, up or down continuously print on a drag.

Can't find where the issue is....

**Comment by barteksc** [comment]
Method `pdfView.fitToWidth()` introduced in 2.5.0

**Comment by 1stmetro** [comment]
Do you want to add an option to oversize the pdf and reduce the margins, 

i just added this, with an option in settings for the size of px to over size.

//pixels to oversize pdf and reduce margins
                                        int margin = Integer.parseInt(prefs.getString("pdfOverSize", "0"));
                                        int cPos = 0;
                                        int centerPos = pdfView.getPageAtPositionOffset(cPos+margin);
                                        float pageWidth = pdfView.getOptimalPageWidth()-margin;
                                        float viewWidth = pdfView.getWidth()-margin;
                                        pdfView.zoomTo(viewWidth / pageWidth);
                                        pdfView.setPositionOffset(centerPos-margin);
                                        pdfView.jumpTo(pageNumber);
                                        pdfView.loadPages();
