### ISSUE TITLE
@barteksc Stuttering when zoomed and dragging, located BUG !

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#242]
Hi @barteksc  i  took a step backwards in trying to locate the stuttering issue when zooming and then dragging.

This appears to be an issue for a few who posted as well as me,

If you run the code below in an activity it works ok, if you run the code in a fragment it stutters !

public class test extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test2);

        File file = new File("/storage*********etc***********/Appendix 1.0.pdf");

        PDFView pdfView = (PDFView) findViewById(R.id.pdfView);
        pdfView.fromFile(file)
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(0)
            //    .onDraw(onDrawListener)
             //   .onLoad(onLoadCompleteListener)
             //   .onPageChange(onPageChangeListener)
             //   .onPageScroll(onPageScrollListener)
             //   .onError(onErrorListener)
                .enableAnnotationRendering(false)
                .password(null)
                .scrollHandle(null)
                .load();
    }
}

**Comment by barteksc** [comment]
When I run this code in fragment everything works as it should.

**Comment by 1stmetro** [comment]
strange, my fragment stutters and doesnt move.... weird..

Im going to move to a standard activity so it works ok, but be interesting to see if the others that had issues used fragments.

**Comment by 1stmetro** [comment]
i might find the issue as i move the code over into another activity, if i locate the issue will post here..

**Comment by 1stmetro** [comment]
Moved code to normal activity all okay ! case closed...
