### ISSUE TITLE
Reduce white space around edge of pdf?

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#244]
Anyone managed to remove the white space on left and right side of the page is there a quick fix?

**Comment by barteksc** [comment]
I don't have any white spaces, could attach a screen?

**Comment by 1stmetro** [comment]
I mean if the pdf has a border can it be reduced?

**Comment by 1stmetro** [comment]
Closed by mistake

**Comment by barteksc** [comment]
Library does not have such functionality
