### ISSUE TITLE
How to disable page number on PDF View

### ISSUE THREAD

**Issue by amantat** [barteksc/AndroidPdfViewer#245]
Hi

How can I disable the page number on the pdf view.

Any help is appreciated. 

Thanks!
![pdf_pagenumber_display](https://cloud.githubusercontent.com/assets/7849131/24268653/d66a875a-0fe4-11e7-99a3-0271e4b3e6d9.png)

**Comment by 1stmetro** [comment]
I thought you didnt get the page number unless you add the scroll bar its been a while since i played with that part but believe the settings below may help you.

    .onPageChange(onPageChangeListener)
    .onPageScroll(onPageScrollListener)
    .scrollHandle=null;

**Comment by amantat** [comment]
I removed this setting .scrollHandle(new DefaultScrollHandle(ViewBillActivity.this)) and it worked fine, Thanks for the reply appreciate it.
