### ISSUE TITLE
Render Example, issues for newbies !

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#246]
Hi, @barteksc can we extend the Constants to have access to all of the constants... 

pdfView.onRender(new OnRenderListener() {
    @Override
    public void onInitiallyRendered(int pages, float pageWidth, float pageHeight) {
        pdfView.fitToWidth(); // optionally pass page number
    }
});

might want to remove the pdfview before .onRender and ; in the example as its sure to mess people up and have countless people asking why it doesnt work..

**Comment by barteksc** [comment]
There is access to all `Constants`.

Thanks, I have fixed this example.

**Comment by 1stmetro** [comment]
I was looking for THUMBNAILS_CACHE_SIZE and GRIDSIZE in the constants but its not there, for some reason a pdf with lots of image will lag on rendering but didnt on version 2.4

Turned off enableAntialiasing(false) but still slow to render, so looking for a fix

**Comment by 1stmetro** [comment]
I found the cache size of 150 is the issue, the 2.4 settings with some changes seems not so laggy this renders quicker but then does the double render for some reason when the pdf has already been drawn.

 public static class Cache {

        /** The size of the cache (number of bitmaps kept) */
        //public static int CACHE_SIZE = 150;
        public static int GRID_SIZE = 10;
        public static int CACHE_SIZE = (int) Math.pow(GRID_SIZE, 2d);

       // public static int THUMBNAILS_CACHE_SIZE = 6;
        public static int THUMBNAILS_CACHE_SIZE = 10;

    }
