### ISSUE TITLE
Rendering with one large image on pdf.

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#247]
I found the cache size of 150 is the issue for initial slow rendering, I reverted back the 2.4 settings with some changes it now renders quicker and not so laggy but it continues to do the double render for some reason when the pdf has already been drawn but its a lot faster with the settings below.

public static class Cache {

    /** The size of the cache (number of bitmaps kept) */
    //public static int CACHE_SIZE = 150;
    public static int GRID_SIZE = 10;
    public static int CACHE_SIZE = (int) Math.pow(GRID_SIZE, 2d);

   // public static int THUMBNAILS_CACHE_SIZE = 6;
    public static int THUMBNAILS_CACHE_SIZE = 10;

}

**Comment by barteksc** [comment]
Using smaller cache causes glitches on screen edges of bigger screens

**Comment by 1stmetro** [comment]
On one pdf it renders quicker with less issues on 9.7 screen with the settings, it seems very slow to render on 2.5 you have to wait for redraw.

I will play around with code later

**Comment by 1stmetro** [comment]
I removed the new render to width function and reinstated the onload function but this version has render issues compared to older version as it now lags on pdfs with large image content when rendering it renders a second time its that second render that lags,

Not looked at code just changed constraints currently to improve it as no time yet.

Which function does the second Render?
