### ISSUE TITLE
Cant open pdf file

### ISSUE THREAD

**Issue by w3ggy** [barteksc/AndroidPdfViewer#252]
Cant open file by this link https://www.x.org/archive/X11R7.5/doc/LICENSE.pdf
Another files open correctly. PDF readers open this file correctly, what i'm doing wrong?
`pdfView.fromFile(file)
                .load();`
Where "file" -- absolute path to the pdf-file, so file.exists()  returns always true.

**Comment by 1stmetro** [comment]
You might want to try this one , pdfView.fromUri(Uri)

**Comment by w3ggy** [comment]
Nothing changed. 
pdfView.fromUri(Uri.fromFile(file)).load()
still doesn't open file from link and open others.

**Comment by 1stmetro** [comment]
Quickly tested and yes seems to be an issue, download the file locally using curl, etc and open locally then it will work ok.

**Comment by 1stmetro** [comment]
Oh don't forget you could use the stream if you don't want a local copy.

**Comment by w3ggy** [comment]
> Quickly tested and yes seems to be an issue, download the file locally using curl, etc and open locally then it will work ok.
There is any ways to open file like this?
I'm already loading file to the device to
`context.getExternalFilesDir(null)`directory
then open it locally. 
On other files it works perfectly. 
May be it is incorrect pdf file or smt?

**Comment by 1stmetro** [comment]
Simple enough when you save locally double check your paths. System.out.print path etc and use a file manager on device to compare paths incase you have an invalid path, obviously load pdf using another program to check if download code is okay and pdf is valid. The code should download and then open a local copy then delete when not required basically it's a temp pdf unless you wanna keep it.
