### ISSUE TITLE
Confirmed render missing text issue

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#255]
I can confirm 2.5 has an issue with missing text inside pdf, I'm yet to locate the issue but does point towards pdf with missing embedded fonts.

Can anyone else confirm simular issues?

**Comment by ahmerafzal1** [comment]
Yes! But now it works perfectly.

**Comment by 1stmetro** [comment]
I had to down grade pdfium to version 1.5 to fix the issue, most pdfs are okay but some wont render text and miss parts.
