### ISSUE TITLE
Missing Text in a PDF?, Quick Fix here...

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#256]
Okay so i have pdf's with the text removed, some other people do also.

I have downgraded from com.github.barteksc:pdfium-android:1.6.0 to com.github.barteksc:pdfium-android:1.5.0 and the issue is no longer there.

This is a quick fix as i'm sure @barteksc will be working on resolving this issue in pdfium ? it appears to be a ghostscript issue although not fully investigated.

Great work @barteksc do you take donations ?

**Comment by barteksc** [comment]
Unfortunately I will not work on resolving this issue in pdfium, this is huge library in C and I don't have time and skills to develop it.

Thank you, but I don't take donations, there are too many problems and I don't have enough time to work on it.

**Comment by 1stmetro** [comment]
I wasn't suggesting you fix for a donation, the offer was to show my apreciation for your hard work.

I downgraded  to version  1.5 it works fine tweeted the settings and nearly removed the redraw.

Also created a fork and added some code for page margins and further code to auto size, let me know what you think.

**Comment by barteksc** [comment]
I meant that I don't feel right to take donations for software with many problems. But thank you for your appreciation.
I will take a look at your fork, but if you think that it is stable piece of code, send a pull request
