### ISSUE TITLE
How to make highlight text function and bookmarks on pdf? 

### ISSUE THREAD

**Issue by AkashiTetsuya** [barteksc/AndroidPdfViewer#258]
I have problem to make highlight on text and bookmark.

**Comment by barteksc** [comment]
This library does not have any function to highlight text

**Comment by 1stmetro** [comment]
You would have to implement OCR or build your own and then post for us.

**Comment by TechnologyMaster** [comment]
@AkashiTetsuya have you find solution for this? I wanted to do same thing.

**Comment by AkashiTetsuya** [comment]
Nope.

**Comment by KnIfER** [comment]
[this](https://github.com/KnIfER/PolymPic) WIP project supports text highlighting and saving.  Help me star it and I'll help figure it out.
