### ISSUE TITLE
Sliding Animation

### ISSUE THREAD

**Issue by nbau21** [barteksc/AndroidPdfViewer#26]
Hello, it seems that the library is locking me into using default animations thru `.swipeVertical(false)` upon rendering a PDF.

Is there a way to disable this slide animation all in all? We just want our PDF to show up, and not slide from right to left (or bottom to top). The readme implies that the only possible configurations are [here](https://github.com/barteksc/AndroidPdfViewer#load-a-pdf-file).

**Comment by barteksc** [comment]
You can set `.enableSwipe(false)` to disable document scrolling by touch.

**Comment by nbau21** [comment]
@barteksc 
`enableSwipe(false)` only disables swiping to a different page. I'm talking about the "swipe" animation that happens when the PDF is loaded. I want to turn this feature off.

**Comment by barteksc** [comment]
Added in 1.4.

**Comment by nbau21** [comment]
Thank you so much!

**Comment by JulienRaad** [comment]
Hello guys, is it possible to swipe page by page ?
