### ISSUE TITLE
can this Viewer catch the word in the PDF file

### ISSUE THREAD

**Issue by huzhaoforwork** [barteksc/AndroidPdfViewer#262]
i need to do the  function （Long press to copy）。but the viewer i useing cant catch the word

**Comment by 1stmetro** [comment]
You would need to write the function to search or highlight text before you could do what you ask, this code has not been done yet.

**Comment by TechnologyMaster** [comment]
@1stmetro @huzhaoforwork  have you find the solution for search text, highlight the text and catch the word onlong click on word?
