### ISSUE TITLE
Split pages in swipeHorizontal

### ISSUE THREAD

**Issue by svelorio** [barteksc/AndroidPdfViewer#264]
Hi.

Is there a way to split pages on the swipeHorizontal configuration?

Im getting this.

![sin titulo](https://cloud.githubusercontent.com/assets/26717835/24883762/faa9de06-1e0b-11e7-8a26-298ca14515a0.jpg)

Which are 3 pages shown in the same view.
What I want is each page shown individually and swipe through them.

**Comment by 1stmetro** [comment]
My fork has page markers which you can size and color, if you resize the pages in landscape you will be off the bottom of the page unless in book mode in portrait which then shows a full page with markers to the sides.

**Comment by svelorio** [comment]
I dont think I expressed myself correctly.

This is what I want

![image](https://cloud.githubusercontent.com/assets/26717835/24913673/7ec1fcec-1e97-11e7-8baa-1a4b31e50ad3.png)

Each page shown alone.
Dont need markers and my app is always in landscape mode.

Thanks in advance.

**Comment by 1stmetro** [comment]
Simple answer load one page at a time.

**Comment by 1stmetro** [comment]
Going back to page markers I have the code to select white or color markers and the size of marker so you could pad the pages out and make it more seamless but wide pages to fill the screen.

Two options hope it helps

**Comment by svelorio** [comment]
I ended up modifying the library and its methods to fit my needs.
Had to work around the canvas and the calculations of each page to add spacing between them and map correctly each point for the zoom features.
