### ISSUE TITLE
After zoom in PDF view, the scroll up is not compatible.

### ISSUE THREAD

**Issue by sssvrock** [barteksc/AndroidPdfViewer#265]
Hello, Once after zoom in single pdf view I am trying to scroll left, right, up and down to read the content. In that case scroll up is not as smooth as scroll left, right & down.

Please suggest to fix this issue asap.

Thanks for great help in advance

**Comment by 1stmetro** [comment]
My suggestion would be to test your code in a different type of activity as I previously had issues in a fragment so i changed to a normal fragment and my code works perfectly.

**Comment by sssvrock** [comment]
as suggested I am using the same in the documentation, only issue with scroll up. In other cases it is working fine.

I am using it in activity.

  pdfView.fromFile(PDF)
                        .pages(0)
                        .enableDoubletap(true)
                        .enableAnnotationRendering(true)
                        .load();

To increase the performance:

pdfView.recycle();
        pdfView.invalidate();

        pdfView.resetZoom();

        pdfView.useBestQuality(true);
        pdfView.setFitsSystemWindows(true);
        pdfView.setDrawingCacheQuality(View.DRAWING_CACHE_QUALITY_HIGH);
        pdfView.setWillNotCacheDrawing(false);
        pdfView.setLayerType(View.LAYER_TYPE_HARDWARE,null);
        pdfView.setDrawingCacheEnabled(true);
        pdfView.enableRenderDuringScale(false);
        pdfView.enableAnnotationRendering(true);

Let me know I m correct or not. 

Regards
Vinod

**Comment by 1stmetro** [comment]
i don't use any of the additional settings as shown that you use and but have modified the constants though to improve the rendering.

Try with a few PDF's and see if you still get issues.

pdfView.recycle();
pdfView.invalidate();

    pdfView.resetZoom();

    pdfView.useBestQuality(true);
    pdfView.setFitsSystemWindows(true);
    pdfView.setDrawingCacheQuality(View.DRAWING_CACHE_QUALITY_HIGH);
    pdfView.setWillNotCacheDrawing(false);
    pdfView.setLayerType(View.LAYER_TYPE_HARDWARE,null);
    pdfView.setDrawingCacheEnabled(true);
    pdfView.enableRenderDuringScale(false);
    pdfView.enableAnnotationRendering(true);
