### ISSUE TITLE
important bug

### ISSUE THREAD

**Issue by droay** [barteksc/AndroidPdfViewer#270]
When the size of the file is an integer multiple of 16, the parsing file is incomplete

**Comment by 1stmetro** [comment]
if you want to send the sample pdf i will test it for you ?

**Comment by droay** [comment]
http://file.firmail.com/testPdf.pdf   This pdf is 905,216 bytes   thanks~

**Comment by 1stmetro** [comment]
I can load the document no problem there, but I have an issue with the font so characters are missing.

**Comment by droay** [comment]
yes，i also have this problem，http://file.firmail.com/test2.pdf  -->  this pdf is also have the problem.

**Comment by droay** [comment]
can you send the shared library source code to my email?

**Comment by 1stmetro** [comment]
What source are you after?

**Comment by droay** [comment]
libjniPdfium.so and libmodpdfium.so    my email:275298736@qq.com  thanks

**Comment by barteksc** [comment]
These files are part of PdfiumAndroid and modpdfium repos...

**Comment by droay** [comment]
thank you very much
