### ISSUE TITLE
How to load multiple PDFs in a single Viewer?

### ISSUE THREAD

**Issue by KSelyman** [barteksc/AndroidPdfViewer#271]
I want the ability to scroll from document to document within a single pdfViewer. How could this be made possible using AndroidPDFViewer.
Also, the PDF documents could have different page sizes and Orientations. How to manage that?

Thanks a bunch

**Comment by 1stmetro** [comment]
Use an array containing the paths and filenames on the last page load the next pdf but you will lose the old one or you could just use multiple viewers and hide and make visible depending where you are within the array.

That's a few ideals to be going on with.
