### ISSUE TITLE
how to use pdfview with fromFile?!

### ISSUE THREAD

**Issue by mahmoodlhb** [barteksc/AndroidPdfViewer#272]
hi i downloaded a pdf file and save it in sdcard then i got it like this:
/storage/emulated/0/pdf/marizi1.pdf
my source code:
File file = new File(Environment.getExternalStorageDirectory()+"/pdf/"+"marizi1.pdf");
pdfView.fromFile(file)
                .load();

but pdfview is empty! how can i fix it?!

**Comment by 1stmetro** [comment]
Quickly test the path and print out Environment.getExternalStorageDirectory it should be the same path that you show, then if still blank use a sample pdf that is a standard pdf not a pdf form,  etc.

To rule out permissions check manifest file, check path using a file manager it might be /sdcard/ you get the ideal.

**Comment by barteksc** [comment]
Closing due to author's inactivity
