### ISSUE TITLE
how to set orientation horizontal scrolling

### ISSUE THREAD

**Issue by AndroidMsky** [barteksc/AndroidPdfViewer#273]
can i set  orientation horizontal scrolling?

default is vertical

Thank you。

**Comment by AndroidMsky** [comment]
i get it . 

And another question, when i accelerated scrol the  view  it pass many pages, i want next page。

how to automatic positioning to the next page by scrolling？

**Comment by 1stmetro** [comment]
.swipeHorizontal(false) set to true for horizontal swipes,

 Scroll to next page that's a function within source code FlingTo function this will point you in the right direction.

**Comment by barteksc** [comment]
Scrolling by page is available only in AndroidPdfViewerV1
