### ISSUE TITLE
OOM cash !!!

### ISSUE THREAD

**Issue by xiaoX3** [barteksc/AndroidPdfViewer#274]
when I  reload pdf more than once.OOM happens somethimes.How to fix it?

error log:
 FATAL EXCEPTION: PDF renderer
                                                                   Process: com.zsl.zhaosubao, PID: 29763
                                                                   java.lang.OutOfMemoryError
                                                                       at android.graphics.Bitmap.nativeCopy(Native Method)
                                                                       at android.graphics.Bitmap.copy(Bitmap.java:568)
                                                                       at com.github.barteksc.pdfviewer.RenderingHandler.proceed(RenderingHandler.java:107)
                                                                       at com.github.barteksc.pdfviewer.RenderingHandler.handleMessage(RenderingHandler.java:71)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by 1stmetro** [comment]
probably worth posting your code which generates the error, no issues loading pdf multiple times here although you appear to run out of memory indicating the memory is not being released, etc...

**Comment by xiaoX3** [comment]
I use pdfview in the Viewpager widget

 viewpager adapter code :

@Override
    public Object instantiateItem(ViewGroup container, int position) {
        View view = mViews.get(position);

        final SwipeRefreshLayout refreshLayout = (SwipeRefreshLayout) view.findViewById(R.id.swipe_refresh);
        refreshLayout.setColorSchemeResources(R.color.tab_contract_end, R.color.tab_contract_ing);
        final PDFView pdfView = (PDFView) view.findViewById(R.id.pdfview);
        String path = mData.get(position);
        if (StringUtil.isNotNull(path)) {
            pdfView.fromFile(new File(path))
                    .defaultPage(1)
                    .enableSwipe(true)
                    .load();
        }

        pdfView.setZoomListener(new IZoomWatchListener() {
            @Override
            public void IsZoomingListener(boolean isZooming) {
                //Log.d("TAG", "isZooming" + isZooming);
                refreshLayout.setEnabled(!isZooming);
                ((MyViewPager) mSignContractFragment.getVp_contract()).setScrollble(!isZooming);
            }
        });
        refreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                mSignContractFragment.initData(true);
            }
        });

        container.addView(view);
        return view;
    }

when the SwipeRefreshLayout call onRefresh(),it will  get data ,and repeat set the viewpager adapter 

the called method code :
private void initViewPager(List<String> pdfData) {
        mVpAdapter = new LoadContractPdfAdapter(getActivity(), this);
        mVp_contract.setAdapter(mVpAdapter);
        mViews.clear();
        mVpAdapter.notifyDataSetChanged();
        for (int i = 0; i < pdfData.size(); i++) {
            View view = View.inflate(getActivity(), R.layout.contract_sign, null);
            mViews.add(view);
        }
        mVpAdapter.setData(pdfData, mViews);
        mVpAdapter.notifyDataSetChanged();
        //每次刷新将当前页置为0
        mCurrentPager = 0;
        mView.setVisibility(View.GONE);
    }

**Comment by 1stmetro** [comment]
When you have finished with the PDF use pdfview.recycle () which I believe is the correct function to release the memory, as you are overriding functions it's possible this is not being called and why you have memory issues.

Just a note to say that I has issues using pdfview in fragments and once I moved my code to a normal activity it worked fine.

**Comment by xiaoX3** [comment]
I will study it agian.Thank your for your answer.
