### ISSUE TITLE
while scrolling next page lands in middle of two pages

### ISSUE THREAD

**Issue by shashankmishra091** [barteksc/AndroidPdfViewer#277]
while scrolling to the next page it lands in middle of two pages how can we make it to load either previous page completely or the next one

**Comment by barteksc** [comment]
This version uses continuous scroll, you may use AndroidPdfViewerV1 for desired behavior

**Comment by shashankmishra091** [comment]
can you please help me to implement that scroll behaviour to land over the exactly another page instead of landing on middle of two pages.
please help me with compile library of versionV1.


Thanks.

**Comment by barteksc** [comment]
Here it is: https://github.com/barteksc/AndroidPdfViewerV1
There is nothing unusual
