### ISSUE TITLE
Allow change max zoom

### ISSUE THREAD

**Issue by registrochin** [barteksc/AndroidPdfViewer#278]
Hi, 

I was using this library, a it's almost perfect for my project needs. But I have a little problem: some pdf files mi app handle have too small text, and I'd need to increase max zoom with pinch (not double tap).

Can you add this feature in future realeases?

thank you

**Comment by 1stmetro** [comment]
It's all ready added constants.blah  max zoom min zoom etc read the text.

**Comment by registrochin** [comment]
Thanks
