### ISSUE TITLE
Password PDF

### ISSUE THREAD

**Issue by RupamShaw** [barteksc/AndroidPdfViewer#28]
Password PDF are not asking,  for password to enter. 
 07-08 15:21:57.020 13331-13331/com.jagdiv.android.gogleapplication E/PDFView: load pdf error
07-08 15:21:57.020 13331-13331/com.jagdiv.android.gogleapplication E/PDFView: java.io.IOException: cannot create document: Incorrect password.
07-08 15:21:57.020 13331-13331/com.jagdiv.android.gogleapplication E/PDFView:     at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
07-08 15:21:57.020 13331-13331/com.jagdiv.android.gogleapplication E/PDFView:     at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:87)
07-08 15:21:57.020 13331-13331/com.jagdiv.android.gogleapplication E/PDFView:     at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:59)

**Comment by barteksc** [comment]
There is no support for documents with password. I will add this in next release.

**Comment by barteksc** [comment]
Support for documents with password added in version 1.2.0

**Comment by PembaTamang** [comment]
where do I enter the password in the code
