### ISSUE TITLE
When the PDF zoom in or out, the text will blur, and then become clear。

### ISSUE THREAD

**Issue by TsuiYC** [barteksc/AndroidPdfViewer#281]
Can someone help me with this problem?
Thank you.

**Comment by 1stmetro** [comment]
This is normal adjust constants to improve, Adobe acrobat also does the same.

**Comment by TsuiYC** [comment]
@1stmetro Hello, thank you for your answer. But this phenomenon occurs in my Android APP, which is a normal phenomenon? Is there a solution?

**Comment by 1stmetro** [comment]
Even commercial apps are blurry and become clearer after zoom scroll etc. I modified my constants to help with this issue and blocks that don't become clear is that is your problem also.
