### ISSUE TITLE
Password option not working

### ISSUE THREAD

**Issue by danielobasi** [barteksc/AndroidPdfViewer#282]
I'm working on a project that requires a password protected pdf but when i put the correct password the pdf doesn't load and i get this error in android monitor:
E/PDFView: load pdf error   java.io.IOException: File is empty
 at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
                                                                         at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:107)
                                                                         at com.github.barteksc.pdfviewer.source.FileSource.createDocument(FileSource.java:38)
                                                                         at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:49)
                                                                         at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)

Although it works without password.
I use this for the pdf reader.
   readerView.fromFile(mBook)
                .enableSwipe(true)
                .swipeHorizontal(true)
                .enableDoubletap(true)
                .defaultPage(0)
                .enableAnnotationRendering(false)
                .password("08034283779")
                .defaultPage(pageNumber)
                .onPageChange(this)
                .onLoad(this)
                .scrollHandle(new DefaultScrollHandle(this))
                .load();

Is there a different way of using passwords?

**Comment by 1stmetro** [comment]
simply 

.password(pass)

is correct, but you catch the errors are you sure the password is correct ?

Forward the pdf can test on my app if you wish ?

**Comment by danielobasi** [comment]
[CSE 000-3-COMPUTER ENGLISH.pdf](https://github.com/barteksc/AndroidPdfViewer/files/980757/CSE.000-3-COMPUTER.ENGLISH.pdf)
That is the file, Please check, Thanks a lot .
I can open it with the password on pages without any problems.

**Comment by 1stmetro** [comment]
It's what I thought it was when you do not use the correct password it will error that's normal just catch the error and display to the user that the password is incorrect works fine for me a blue background pdf file when opened and my message saying pdf requires a correct password if I do not set one.

**Comment by danielobasi** [comment]
Please can you send me a sample of your activity that reads the pdf. What I have there, the password showed on my code is what I used and it's not working on mine, if it's working on yours I need to see your implementation. On mine with that password I get a blank screen when  trying to read the pdf and that error shows on my android monitor.

**Comment by 1stmetro** [comment]
if you have the correct password and the page is white that's a bit string, if you have the wrong pass it will error out which is what you catch, i would work on the basics which is the .password(pass) bit and then work on the error catching.

readerView.fromFile(mBook) <-- have you checked the path to the file, as your error reads "load pdf error java.io.IOException: File is empty" i dont believe it gives this error on an incorrect password although its a while since i played around with error catching...

**Comment by danielobasi** [comment]
Thanks alot. I have the correct password, the page is white, it's not a path error because if I remove the password it works. What do you mean:
 "if you have the correct password and the page is white that's a bit string"
I don't understand. I think that's the error , how can I be sure to use the same string type ?

**Comment by 1stmetro** [comment]
That it about string was a typo, i basically have the same as you have used, but you have applied the default page twice ? is the second one a null or an invalid page ?

.password(password) - password is a string, i actually restore it from a database and apply it to the loaded pdf.

readerView.fromFile(mBook)
.enableSwipe(true)
.swipeHorizontal(true)
.enableDoubletap(true)
.defaultPage(0)
.enableAnnotationRendering(false)
.password("08034283779")
.defaultPage(pageNumber) ------ What page is this ? since you have set it twice ie blank page ?
.onPageChange(this)
.onLoad(this)
.scrollHandle(new DefaultScrollHandle(this))
.load();

**Comment by danielobasi** [comment]
Sorry that is not a blank page . It was a mistake after I implemented code to store the last page number in database and resume after a user comes back.  It's not a blank page, my screen is just white and in monitor I see "file is empty" only when i use a password with the pdf.
I've loaded the password from a string variable and it still doesn't work.

**Comment by 1stmetro** [comment]
i have experienced issues using fragments but not one with using a password in a fragment.

Just start basic and use the default instructions on here, it will probably work without any issues thats how i know there is issues using fragments, but no everyone gets the same issues.

some use fragments with no problem's just depends what else you are doing i guess.

**Comment by danielobasi** [comment]
Ok. But I'm using an activity and not a fragment. The problem exist only when I try to use a password. I guess it's not matching the password correctly because the error I get is the same when I intentionally try a wrong  password. I guess I'll have to look through the sources for the implementation of the password for pdf. Thanks alot

**Comment by 1stmetro** [comment]
Dunno if this my help

"Am trying a populate a pdf which is stored in internal storage is throwing FileNotFoundException."

Simular issues to what you have as file not could found or empty.

https://github.com/barteksc/AndroidPdfViewer/issues/2

**Comment by danielobasi** [comment]
I uploaded the pdf on a backend, download it to the phone using the app, store the name and path of the pdf in database, take the file path from the database and pass it to the read. It's just one implementation and it works without password but with password if gives that  file empty error. If it's a path thing or some other errors other pdf that aren't locked won't also load, but they load.

**Comment by danielobasi** [comment]
I've found the issue, has nothing to do with the library. it was a blank space on the path i didn't notice. It works now. Thanks a lot.

**Comment by 1stmetro** [comment]
I did say check the path..... good luck with your app !

Now you gotta catch the wrong password !
