### ISSUE TITLE
When I use fitToWidth method with defaultPage, defaultPage isn't working

### ISSUE THREAD

**Issue by EnesKaraosman** [barteksc/AndroidPdfViewer#283]
pdfView.fromAsset(PDF_FILENAME)
                .defaultPage(83)
                .enableSwipe(true) // allows to block changing pages using swipe
                .swipeHorizontal(false)
                .enableDoubletap(false)
                .scrollHandle(new DefaultScrollHandle(this))
                .onRender(new OnRenderListener() {
                    @Override
                    public void onInitiallyRendered(int nbPages, float pageWidth, float pageHeight) {
                        pdfView.fitToWidth();
                    }
                })
                .load();

When I used these codes, my default page opens onCreate but immediately goes to first page, 
but when I remove .onRender(..  method, its working, is there something that I am missing, could you help me..

**Comment by barteksc** [comment]
Pass page number to `fitToWidth` method

**Comment by EnesKaraosman** [comment]
Thanks, solved problem, works together.
