### ISSUE TITLE
Non-static method 'onRender(com.github.barteksc.pdfviewer.listener.OnRenderListener)' cannot be referenced from a static context

### ISSUE THREAD

**Issue by AhmadullahSaikat** [barteksc/AndroidPdfViewer#286]
PDFView.Configurator.onRender(new OnRenderListener() {
            @Override
            public void onInitiallyRendered(int pages, float pageWidth, float pageHeight) {
                pdfView.fitToWidth(); // optionally pass page number
            }
        });

Here ".onRender" shows that error...
please fix that error.. and update..

**Comment by barteksc** [comment]
This is not error, you are using it incorrectly. Refer to [README](https://github.com/barteksc/AndroidPdfViewer#load-a-pdf-file)
