### ISSUE TITLE
Please I need your help!

### ISSUE THREAD

**Issue by CARChayder** [barteksc/AndroidPdfViewer#287]
Dear friends, 
Could you please show me how can I use this code:

`PDFView.Configurator.onRender(new OnRenderListener() {
            @Override
            public void onInitiallyRendered(int pages, float pageWidth, float pageHeight) {
                pdfview.fitToWidth(); // optionally pass page number
            }
        });`

I put it inside the Oncreate method and I got an error: non-static method cannot be reference from a static context. I check the README. But, I still do not know how to use it. 
Thanks a lot

**Comment by barteksc** [comment]
```java
...
pdfView.fromSource(DocumentSource)
or
pdfView.fromAsset(String)
    .pages(0, 2, 1, 3, 3, 3) // all pages are displayed by default
    ...
    .onError(onErrorListener)
    .onRender(onRenderListener) // called after document is rendered for the first time
    .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
    ...
    .load();
```
This is fragment from readme

**Comment by CARChayder** [comment]
Thanks a lot. It works like a charm.
My implementation is this:

`        pdfview.fromAsset("Mypdf.pdf")
                .pages(0, 2, 1, 3, 3, 3)
                .onRender(new OnRenderListener() {
                    @Override
                    public void onInitiallyRendered(int pages, float pageWidth, float pageHeight) {
                        pdfview.fitToWidth(); 
                    }
                }) 
                .enableAnnotationRendering(false) 
                .load();
`
