### ISSUE TITLE
itext PDF use Chinese font,and the  app crash

### ISSUE THREAD

**Issue by momoc** [barteksc/AndroidPdfViewer#288]
itext PDF use Chinese font,and the  app crash

**Comment by 1stmetro** [comment]
little more information would be good.

**Comment by momoc** [comment]
itext PDF use Chinese font,and the app crash；
Because itext PDF use  iTextAsian.jar and BaseFont.createFont("STSong-Light", "UniGB-UCS2-H",BaseFont.NOT_EMBEDDED);

So I'm not using this now, using other font formats
Thank you……

**Comment by 1stmetro** [comment]
No idea what Itext pdf is, good luck.

**Comment by momoc** [comment]
Thank you……

**Comment by barteksc** [comment]
@momoc Is this issue resolved?

**Comment by momoc** [comment]
yes
