### ISSUE TITLE
č and ć letters doesn't display, leaves empty space?

### ISSUE THREAD

**Issue by MerimaHus** [barteksc/AndroidPdfViewer#289]
Please help, the library is working great, except of this issue. When my pdf is loaded inside the view, it doesn't display č and ć letters, but š and ž letters are displayed. How can I fix it?

**Comment by 1stmetro** [comment]
perhaps post the pdf so others can confirm the same issue to perhaps a fix.

**Comment by MerimaHus** [comment]
Well, the problem is that I can't post a pdf, because of the clients confidentiality issue. But the way I handle it is,  I get the an array of bytes from my server, then I decode it with Base64.decode(myByteArray, Base64.DEFAULT). Then I create my pdf file inside the downloads folder and at the end I call the fromFile() method on my predefined pdfView.

**Comment by 1stmetro** [comment]
Just post a pdf without client details... then it can be tested on someone else's app ....

**Comment by barteksc** [comment]
Closing due to no response from author
