### ISSUE TITLE
Enable Break Between Pages

### ISSUE THREAD

**Issue by Papabrose** [barteksc/AndroidPdfViewer#292]
Hello, Is there a way I can enable it to show a break between each page in the pdf?

**Comment by 1stmetro** [comment]
I have this done in my fork, user selectable for the size of the page marker also enable option.

**Comment by Papabrose** [comment]
So there is no way to currently do it. When will that be put in? Or can you give me a code snippet of how to do it?

**Comment by 1stmetro** [comment]
I custom added the code and create a fork, codes on there

**Comment by 1stmetro** [comment]
Not had time to update the fork but the basics are there.... i will have to update and merge 

@barteksc

**Comment by wonday** [comment]
+1

**Comment by barteksc** [comment]
@Papabrose Try 2.7.0-beta version, it has possibility to add spacing between pages

**Comment by Papabrose** [comment]
@barteksc is there anyway to make it look like a page break like this? This is really what I meant by break between pages.  

![image](https://user-images.githubusercontent.com/26420596/27245827-f64c90c8-52aa-11e7-9393-8ae09b4de0c8.png)

**Comment by barteksc** [comment]
Set spacing and PdfView's background in desired color

**Comment by Papabrose** [comment]
Thanks you rock!
