### ISSUE TITLE
Any possibility of converting the PDF to formatted String?

### ISSUE THREAD

**Issue by khaledkhj** [barteksc/AndroidPdfViewer#293]
Can I get the PDF file into plain formatted string?

The thing here is that I want to print the PDF file using POS printer, but the printer print only plain strings!
so to format the string is really difficult.

Thank you.

**Comment by 1stmetro** [comment]
I've read its in the C source, you just have to hook into it... good luck..

**Comment by barteksc** [comment]
There is no such possibility, you can try playing with [PdfiumAndroid](https://github.com/barteksc/PdfiumAndroid) and modify its sources to use `FPDFText_GetText()` function from `fpdf_text.h`.
