### ISSUE TITLE
DocumentFile

### ISSUE THREAD

**Issue by ENOZA** [barteksc/AndroidPdfViewer#3]
Is it possible to make AndroidPdfViewer read a DocumentFile? 

Right now, there are `fromFile()` and `fromAsset()` but I was thinking it would be great if we have something like `fromDocumentFile()`.

```
  public Configurator fromDocumentFile(Context context, DocumentFile document_file) {
    if (!document_file.exists()) {
      throw new FileNotFoundException(document_file.getUri().getPath().toString() + " does not exist.");
    }
    return new Configurator(context, document_file);
  }
```

What I want to do is that I let a user pick up a PDF file using  Android's `Storage Access Framework` and display it on the screen using AndroidPdfViewer.

Right now, I can do this by copying DocumentFile to a temp File instance and pass it to fromFile(). However, I was thinking if I could avoid making a temporary file.

**Comment by barteksc** [comment]
Thanks, I will take a look at it

**Comment by barteksc** [comment]
I have played with it a little bit. When you pick file using SAF it returns `Uri`, maybe method `fromUri(Uri)` will suffice? It is more universal than `fromDocumentFile()`

**Comment by ENOZA** [comment]
That's a great idea! 
Yes, `fromUri()` is definitely more universal than `fromDocumentFile()`!

**Comment by barteksc** [comment]
`fromUri(Uri)` method added in version 1.1.0
