### ISSUE TITLE
PDF not displayed in ScrollView

### ISSUE THREAD

**Issue by mountainowl** [barteksc/AndroidPdfViewer#300]
I have to use ScrollView to display bunch of data and PDF (at the bottom), however PDF does not render at all in ScrollView parent. Here my layout,

<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="200dp">

        <com.github.barteksc.pdfviewer.PDFView
            android:id="@+id/pdfview"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </RelativeLayout>
</ScrollView>

Renderer (you can use any local PDF file from assets to test)
vPDFView.fromFile(mPdfFile)
                    .pages(0, 1)
                    .defaultPage(0)
                    .swipeHorizontal(true)
                    .enableSwipe(true)
                    .load();

**Comment by 1stmetro** [comment]
I don't see a scroll view I see a relativeLayout..

Just post your code...

**Comment by barteksc** [comment]
Closing due to no response from author

**Comment by Siddounet** [comment]
Hi, having the same issue with a simple loading. Using 2.6.1.
Without ScrollView/NestedScrollView everything is fine.
Here my full xml :
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white">

    <android.support.v4.widget.NestedScrollView
            android:id="@+id/pdf_scrollview"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

        <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="300dp"
                android:paddingBottom="@dimen/fab_margins">

            <com.github.barteksc.pdfviewer.PDFView
                    android:id="@+id/pdfView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />

        </RelativeLayout>

    </android.support.v4.widget.NestedScrollView>

    <android.support.design.widget.FloatingActionButton
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/fab_margins"
            android:src="@drawable/ic_share"
            app:layout_anchor="@id/pdf_scrollview"
            app:layout_anchorGravity="end|bottom" />

</android.support.design.widget.CoordinatorLayout>
```

I also tried with a different height (wrap or match) for Relative, but no luck. Tried with a ConstraintLayout but same.

Here my loading func : 

```
//    @BindView(R.id.pdfView)
//    PDFView pdfView;
...
private void displayPdf(File file) {
        pdfView.fromFile(file).load();
}
```

My file isn't empty, & nothing is throw (logcat).
Any idea?
Thx.

**Comment by Shivani12345** [comment]
I have the same issue,Without using  ScrollView/NestedScrollView everything is fine but i have to set image below pdfview. please help me

this is my xml code
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">
 <android.support.v4.widget.NestedScrollView
            android:id="@+id/pdf_scrollview"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.github.barteksc.pdfviewer.PDFView
            android:id="@+id/pdfvieww"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="10dp"
            />
<ImageView
                    android:layout_width="190dp"
                    android:layout_height="75dp"
                    android:layout_gravity="center_horizontal"
                    android:src="@drawable/i_logo" />
   </LinearLayout>
</android.support.v4.widget.NestedScrollView>


</android.support.design.widget.CoordinatorLayout>

**Comment by Shivani12345** [comment]
i have same issue .I have to set Imageview below pdfview in scrollview
please help me
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    <android.support.v4.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

        <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

            <com.github.barteksc.pdfviewer.PDFView
                    android:id="@+id/pdfVieww"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />

    <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
 android:layout_below="@+id/pdfVieww"
            android:src="@drawable/i_logo"/>
        </RelativeLayout>

    </android.support.v4.widget.NestedScrollView>

</android.support.design.widget.CoordinatorLayout>

**Comment by lethanhtan89** [comment]
Can not scroll PDF on NestedScrollView, please for me a sugession.

**Comment by sardmendoza** [comment]
Why is this closed without any resolution? The only workaround we found was to set a height (2000dp or more) so that we can scroll through.

**Comment by MustafaSertac** [comment]
Somebody help us 🗡️

**Comment by bhavinatharva** [comment]
Same issue

**Comment by bhavinatharva** [comment]
I have solve it using this 


```
 private fun adjustPdfViewHeight(numberOfPages: Int) {
        binding.pdfView.viewTreeObserver.addOnGlobalLayoutListener(object :
            ViewTreeObserver.OnGlobalLayoutListener {
            override fun onGlobalLayout() {
                binding.pdfView.viewTreeObserver.removeOnGlobalLayoutListener(this)

                val pageWidth = binding.pdfView.measuredWidth
                var totalHeight = 0

                // Loop through each page to calculate its height
                for (i in 0 until numberOfPages) {
                    val pageSize = binding.pdfView.getPageSize(i)
                    val pageHeightRatio = pageSize.height / pageSize.width
                    val pageHeight = (pageWidth * pageHeightRatio).toInt()

                    totalHeight += pageHeight
                }

                val layoutParams = binding.pdfView.layoutParams as LinearLayout.LayoutParams
                layoutParams.height = totalHeight
                binding.pdfView.layoutParams = layoutParams
            }
        })
    }
```
