### ISSUE TITLE
can‘t’  show  the text of font：“AdobeSongStd-Light”  in same type of phone

### ISSUE THREAD

**Issue by 18872731525** [barteksc/AndroidPdfViewer#303]
please help me! user your lib,,now problem occur in same phone !
these pdf file being edit by "AdobeSongStd-Light font   UniGB-UTF16-H   Type1(CID)"   
my boss asking me solve problem,but i don't know what to do now

**Comment by barteksc** [comment]
Which AndroidPdfViewer version are you using?

**Comment by 18872731525** [comment]
I have try 2.5.0 and 2.5.1 both.

**Comment by 18872731525** [comment]
the pdf file version 1.6， is the reason？
ps："AdobeSongStd-Light font UniGB-UTF16-H Type1(CID)"  only num and “@” can‘t’ show，Chinese character  has no problem.

**Comment by barteksc** [comment]
Please attach this document (or similar if you cannot publish this one)

**Comment by barteksc** [comment]
Closing due to no response from author

**Comment by 18872731525** [comment]
the file is business secret，i can‘t show it in public place, and can't  make sample also
 maybe you can show mt you email, i will post file to in private；
（i try 2.7.0beat   ，still can not show the front in   samsung-N9002）
