### ISSUE TITLE
Smooth scroll from top to bottom direction

### ISSUE THREAD

**Issue by tushardar** [barteksc/AndroidPdfViewer#304]
Great library. 
I am using [compile 'com.github.barteksc:android-pdf-viewer:2.5.1'] library.
I have only single page pdf which can be scrolled.
When I scroll from bottom to top direction the page is scrolled smoothly.
How can I implement the same thing when I scroll from top to bottom direction.

**Comment by 1stmetro** [comment]
Should scroll both ways......

**Comment by barteksc** [comment]
Try version 2.6.0, it improves fling.

**Comment by tushardar** [comment]
Thanks...
Its too good.
