### ISSUE TITLE
android:allowBackup= false showing error.

### ISSUE THREAD

**Issue by android85** [barteksc/AndroidPdfViewer#306]
Hello team,
I need your help, I am facing this issue.
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:60:9-36
      is also present at [com.github.barteksc:pdfium-android:1.4.0] AndroidManifest.xml:12:9-35 value=(true).
      Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:57:5-465:19 to override.

I have already used  tools:replace="android:allowBackup", but it doesn't work. please suggest me.

Thanks
Ram

**Comment by barteksc** [comment]
You are using old AndroidPdfViewer. Version 2.3.0 updates PdfiumAndroid to 1.5.0, where `allowBackup` attribute is removed
