### ISSUE TITLE
Zoom width to container size

### ISSUE THREAD

**Issue by theFasta** [barteksc/AndroidPdfViewer#31]
Is there any way to set initial zoom of an open document so that width matches its container (the PDFView) ?
In other words... when rotating to landscape, I would like the document to have the width matching the container, no worries for the height. 
Thank you!

**Comment by barteksc** [comment]
No, currently there is no such possibility.

**Comment by ScheNi** [comment]
I would also like to see this as a feature.

**Comment by crgarridos** [comment]
I achieved this with :

``` java
pdfView.fromFile(outputFile)
    .onLoad{
         pdfView.zoomTo(pdfView.width.toFloat()/pdfView.optimalPageWidth)
         pdfView.moveTo(0f,0f)
    }.load()

```
