### ISSUE TITLE
Pdf not show text

### ISSUE THREAD

**Issue by suli1** [barteksc/AndroidPdfViewer#313]
Mine pdf is not showing text;  After change  'com.github.barteksc:pdfium-android:1.5.0' to 1.6.0, this is OK!

**Comment by barteksc** [comment]
Better don't use 1.6.0 version, not embedded fonts won't be rendered. I am currently fixing 1.6.0 and in a few days I will release new version. But it's good to see that newer version of pdfium has fixed some issues.

**Comment by barteksc** [comment]
Version 2.7.0-beta updates PdfiumAndroid to newest version which should not have problems with font rendering
