### ISSUE TITLE
I want to show a chapter page number from 15 to 25

### ISSUE THREAD

**Issue by ahmerafzal1** [barteksc/AndroidPdfViewer#314]
I want to show a chapter page number from 15 to 25, how it will be? I can start a chapter page number using `.defaultPage(15)` but how can I finish on page 25? Is it possible?

**Comment by 1stmetro** [comment]
You can load a page range and stop at page 25, as per the instructions.

**Comment by barteksc** [comment]
I don't understand question, but does previous response resolve your problem?

**Comment by 1stmetro** [comment]
Sounds like he want to display a range of pages starting at a chapter number say from page 15 to page 25

**Comment by barteksc** [comment]
Closing due to no response from author
