### ISSUE TITLE
Scroll hande is hidden even during scrolling with the handle

### ISSUE THREAD

**Issue by majkimester** [barteksc/AndroidPdfViewer#315]
It is hidden by the new PdfView.computeScroll() method during scrolling with the handle.
That call is intended to hide the handle at the end of a fling, but unfortunately it does it also during scrolling with the handle. This can be avoided in the DefaultScrollHandle with omitting the hideDelayed call while scrolling with the handle is in progress:

    @Override
    public void hideDelayed() {
        if (!fingerDown) {
            handler.postDelayed(hidePageScrollerRunnable, 2000);
        }
    }

and:

    @Override
    public boolean onTouchEvent(MotionEvent event) {

        if (!isPDFViewReady()) {
            return super.onTouchEvent(event);
        }

        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
            case MotionEvent.ACTION_POINTER_DOWN:
                fingerDown = true;
                pdfView.stopFling();
                handler.removeCallbacks(hidePageScrollerRunnable);
                if (pdfView.isSwipeVertical()) {
                    currentPos = event.getRawY() - getY();
                } else {
                    currentPos = event.getRawX() - getX();
                }
            case MotionEvent.ACTION_MOVE:
                if (pdfView.isSwipeVertical()) {
                    setPosition(event.getRawY() - currentPos + relativeHandlerMiddle);
                    pdfView.setPositionOffset(relativeHandlerMiddle / (float) getHeight(), false);
                } else {
                    setPosition(event.getRawX() - currentPos + relativeHandlerMiddle);
                    pdfView.setPositionOffset(relativeHandlerMiddle / (float) getWidth(), false);
                }
                return true;
            case MotionEvent.ACTION_CANCEL:
            case MotionEvent.ACTION_UP:
            case MotionEvent.ACTION_POINTER_UP:
                fingerDown = false;
                hideDelayed();
                return true;
        }

        return super.onTouchEvent(event);
    }

**Comment by barteksc** [comment]
Thank you for the info, I will fix it.

**Comment by barteksc** [comment]
Fixed in 2.6.1
