### ISSUE TITLE
I did not see libjniPdfium.so in libs

### ISSUE THREAD

**Issue by ng2Kaming** [barteksc/AndroidPdfViewer#325]
EXCEPTION STACK:
                                                           java.lang.RuntimeException:Unable to start activity ComponentInfo{com.hbb.app/com.hbb.app.feature.print.ui.PrintPDFPreviewActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class com.github.barteksc.pdfviewer.PDFView
                                                          android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2452)
                                                          ......
                                                          cause by:
                                                          java.lang.UnsatisfiedLinkError:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.hbb.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hbb.app-1/lib/arm, /data/app/com.hbb.app-1/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]] couldn't find "libjniPdfium.so"

**Comment by barteksc** [comment]
How do you include library?

**Comment by ng2Kaming** [comment]
Yes i did it.(compile project(':android-pdf-viewer')  in build.gradle)I just need armeabi, so remove the other.

**Comment by barteksc** [comment]
It is hard to help if you remove part of library...

**Comment by ng2Kaming** [comment]
thank,I have solved it.
