### ISSUE TITLE
Rendering issue during zoom out

### ISSUE THREAD

**Issue by cameronsheng** [barteksc/AndroidPdfViewer#331]
Hi, first thanks for the great PDF library!
I face the issue that sometimes during zoom out, there is a obvious "scanning" effect which shows thick black lines on the screen.
![image](https://user-images.githubusercontent.com/29650430/27469891-13747412-5824-11e7-8588-5c7695b0d611.png)

I have tried to tune the Constants but did not work.
Thank you.

**Comment by 1stmetro** [comment]
Care to post the pdf so I can test for you ?

**Comment by cameronsheng** [comment]
@1stmetro 
Hi, a sample PDF is here
[Test Report-13-06-2017-05-27-45.pdf](https://github.com/barteksc/AndroidPdfViewer/files/1097010/Test.Report-13-06-2017-05-27-45.pdf)
Thank you!

**Comment by 1stmetro** [comment]
Tested...


Okay i cannot replicate your issue but I do not run a stock version of pdfview my constants are completely different. I can how ever see the thick lines but i get a final draw that corrects them looks like your final draw is not doing the same as mine does.

I will post my constants code later as I believe my constant vary on the zoom level set in constants.

Which increases or decreases depending on the set constant as you would expect more cache with a larger zoom as more parts to cache if that makes sense.

**Comment by cameronsheng** [comment]
@1stmetro 
hi, I am sorry I forgot to mention that the image is not the final draw, the final draw is okay.
The problem is intermediate only during the zooming.

Thank you.

**Comment by cameronsheng** [comment]
@1stmetro 
Also this make take a few times a appear, and with fast zooming.

**Comment by 1stmetro** [comment]
I did lots of pinch zooms I can see thick lines but last redraw corrects but as I said my constants change based on maximum zoom level so a zoom level of 20 will have different cache sizes, etc to zoom level of 10.

**Comment by cameronsheng** [comment]
@1stmetro 
Hi, I also get the correct result after the last redraw, as you mentioned "last redraw corrects", but is there anyway to get rid of the black lines even during the zooming before last redraw, so I won't not see any black lines during zooming at all?
Thank you.

**Comment by cameronsheng** [comment]
@1stmetro 
To avoid misunderstanding, I also have a video here.(Sorry I have to zip it before uploading)

[PDF-Rendering-Errors.zip](https://github.com/barteksc/AndroidPdfViewer/files/1097198/PDF-Rendering-Errors.zip)

**Comment by 1stmetro** [comment]
Seen the video, 

That view you see is normal, even adobe reader has a similar look on pdf's

**Comment by cameronsheng** [comment]
@1stmetro 
Thanks for explanation, I guess we can close the issue then.
