### ISSUE TITLE
sometime load white page 

### ISSUE THREAD

**Issue by amin9565** [barteksc/AndroidPdfViewer#335]
hello my friend 
sometimes open the app one page is white and when i change page and come back one page is true !
what do shall ?
thank u

**Comment by 1stmetro** [comment]
I would post some code so we can see what your doing...

**Comment by amin9565** [comment]
just i use the lib 4.1.0 and i don't change any things ...

**Comment by barteksc** [comment]
Problem is, that there is no such version

**Comment by amin9565** [comment]
sorry i write  mistake 
lib 2.5.1

**Comment by barteksc** [comment]
Please try 2.7.0-beta

**Comment by plutext** [comment]
happens for me too (2.7.0-beta)

**Comment by 1stmetro** [comment]
Post your code..

**Comment by BjoernPluester** [comment]
Same problem...
My code:
pdfView.fromUri(uri)
                .onError(new OnErrorListener() {
                        @Override
                        public void onError(Throwable t) {
                            t.printStackTrace();
                            Log.e("pdfView",t.getMessage());
                        }
                    })
                .onRender(new OnRenderListener() {
                        @Override
                        public void onInitiallyRendered(int nbPages, float pageWidth, float pageHeight) {
                            rendered = true;
                            Log.v("pages loaded:", nbPages + "");
                            Log.v("pageHeight",pageHeight+"");
                            Log.v("PageWidth",pageWidth+"");
                            pages = nbPages;
                        }
                    })
                .enableAnnotationRendering(true)
                .spacing(10)
                .enableAntialiasing(true)
                .defaultPage(0)
                .load();

The thing is that it only works sometimes and I haven't been able to find a pattern. The code does not reach onRender and there is no message in the logs. Loading specific pages always works but loading an entire document fails more often than not.
