### ISSUE TITLE
Publishing on the store

### ISSUE THREAD

**Issue by Azaliarym** [barteksc/AndroidPdfViewer#336]
I'm currently developping an application that uses your library.
When it'll be finished i'd like to publish it on the play store.
Is it possible ?

**Comment by barteksc** [comment]
It is possible, why not?

**Comment by 1stmetro** [comment]
I'm guessing they wanted to know the licence details in  summary not the licence jargon.

As in the you can do this but you can't do that....

**Comment by barteksc** [comment]
Library is published on Apache License, may be used in free open source and in commercial closed source apps.
