### ISSUE TITLE
progressOverlay

### ISSUE THREAD

**Issue by plutext** [barteksc/AndroidPdfViewer#338]
This isn't really an issue with the viewer, but more a question about extending the sample.

Using the sample https://github.com/barteksc/AndroidPdfViewer/blob/master/sample/src/main/res/layout/activity_main.xml I'm trying to add a progressOverlayto be displayed using  https://stackoverflow.com/a/29542951/1031689
until I'm ready to invoke pdfView.fromUri

`&lt;RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="match_parent">

    <com.github.barteksc.pdfviewer.PDFView
        android:id="@+id/pdfView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

	<include layout="@layout/include_progress_overlay"/>

&lt;/RelativeLayout>`

But the progressOverlay is never shown.  Any ideas what might be wrong?  I've tried setVisibility(View.VISIBLE) and bringToFront() on progressOverlay, but I don't see anything

**Comment by 1stmetro** [comment]
Simple answer display your progress bar activity upon login load the pdf activity.

Then both are separated which will make it simple.

**Comment by barteksc** [comment]
@plutext Probably you are not using RelativeLayout correctly, please read some materials about it

**Comment by plutext** [comment]
Thanks for your reply.  I've extended the sample a little bit to support conversion (in this case from docx) before viewing.  It works beautifully :-)

Toast, setTitle, and progressOverlay (I'm trying them all, at [1]) don't appear though, until pdfView renders.  They should appear while the conversion is happening.  

I'm a Java dev not an Android dev, so It'd be great to have advice whether there is something simple I might change to fix this.  thanks

[1] https://github.com/plutext/PdfConverterAndroid/blob/master/app/src/main/java/com/plutext/pdfconverterandroidclient/MainActivity.java#L227
