### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by hamidmatris** [barteksc/AndroidPdfViewer#339]
![3](https://user-images.githubusercontent.com/7304722/27794084-eca707e2-6015-11e7-8cab-1089757d76b4.png)
![1](https://user-images.githubusercontent.com/7304722/27794085-eca7259c-6015-11e7-9762-3d63634dfd94.png)
![2](https://user-images.githubusercontent.com/7304722/27794086-ecac7ea2-6015-11e7-8851-f7c635877c2b.png)

**Comment by barteksc** [comment]
This is not PdfiumAndroid repository
