### ISSUE TITLE
PDF Content not displayed

### ISSUE THREAD

**Issue by navneetkarnani** [barteksc/AndroidPdfViewer#344]
I see the attached screenshot when trying to view a certain PDF that I received in my email from a service provider. What could be the reason ? And how do I fix it ? Are there any logs or events I can listen on so that I can handle this kind of content ?

![androidpdfviewer-screenshot](https://user-images.githubusercontent.com/2557648/27875928-ae785cdc-61d2-11e7-9cd2-826e19eda174.png)

**Comment by barteksc** [comment]
Everything is written in message on screenshot. PDF is interactive and this library does not support interactive documents

**Comment by navneetkarnani** [comment]
Is there some way to detect this in the code? That way I can popup the Adobe Reader when this content is detected.

**Comment by barteksc** [comment]
No, there is no such possibility

**Comment by navneetkarnani** [comment]
Thanks.
