### ISSUE TITLE
Text missing

### ISSUE THREAD

**Issue by shxdos** [barteksc/AndroidPdfViewer#345]
when i load this "pdf http://www.anweitong.com/upload/document/laws/139029908093319545.pdf" and display it the text missing  device: xiao mi android 7.0

**Comment by barteksc** [comment]
Which version of this library do you use?

**Comment by shxdos** [comment]
com.github.barteksc:android-pdf-viewer:2.6.1

**Comment by 1stmetro** [comment]
I don't lose text I see Chinese in my pdfview app but in another pdf viewer I lose the chinese.

Onedrivd pdf even says it's corrupt but as I said my pdfview app works fine.

**Comment by barteksc** [comment]
Unfortunately it will be hard to help if document works on some devices but does not on others. You may check if PDF is valid e.g. here [https://www.pdf-online.com/osa/validate.aspx](https://www.pdf-online.com/osa/validate.aspx)

**Comment by shxdos** [comment]
just some devices does not work , but i can read it by native pdf app @1stmetro

**Comment by barteksc** [comment]
Which native pdf app? Did you check validity of document?

**Comment by shxdos** [comment]
@barteksc WPS Office 
the valid response

1
--
Validating file "139029908093319545.pdf" for conformance level pdf1.3The embedded font program 'DY1+ZHBGea-1' cannot be read.The embedded font program 'DY2+ZHBGea-2' cannot be read.The embedded font program 'DY3+ZHBGea-3' cannot be read.The embedded font program 'DY4+ZHBGea-4' cannot be read.The embedded font program 'DY5+ZHBGea-5' cannot be read.The embedded font program 'DY6+ZHBGea-6' cannot be read.The embedded font program 'DY7+ZHBGeb-7' cannot be read.The embedded font program 'DY8+ZHBGeb-8' cannot be read.The embedded font program 'DY9+ZHBGeb-9' cannot be read.The embedded font program 'DY10+ZHBGeb-10' cannot be read.The embedded font program 'DY11+ZHBGeb-11' cannot be read.The embedded font program 'DY12+ZHBGeb-12' cannot be read.The embedded font program 'DY13+ZHBGeb-13' cannot be read.The embedded font program 'DY14+ZHBGeb-14' cannot be read.The embedded font program 'DY15+ZHBGec-15' cannot be read.The embedded font program 'DY16+ZHBGec-16' cannot be read.The embedded font program 'DY17+ZHBGec-17' cannot be read.The embedded font program 'DY18+ZHBGec-18' cannot be read.The embedded font program 'DY19+ZHBGec-19' cannot be read.The embedded font program 'DY20+ZHBGec-20' cannot be read.The embedded font program 'DY21+ZHBGed-21' cannot be read.The embedded font program 'DY22+ZHBGed-22' cannot be read.The embedded font program 'DY23+ZHBGed-23' cannot be read.The value of the key Type is FileSpec but must be Filespec.The document does not conform to the requested standard.The document doesn't conform to the PDF reference (missing required entries, wrong value types, etc.).The document contains fonts without embedded font programs or encoding information (CMAPs).The document contains annotations or form fields with ambigous or without appropriate appearances.Done.

**Comment by barteksc** [comment]
As you see document is not valid PDF, you should fix it and try again

**Comment by shxdos** [comment]
@barteksc this file is from remote....

**Comment by 1stmetro** [comment]
I downloaded locally I presume @barteksc did also when testing. Fix the off and get again my pdfview works with it but commercial app doesnt

**Comment by barteksc** [comment]
@shxdos this problem is strictly connected with Pdfium (because it is pdf rendering engine) and I'm not its author, so unfortunately I cannot do anything with your issue. Only thing that can help is to fix this document, but it may be hard if it's not yours.

**Comment by alanforgithub** [comment]
I have the same problem。
