### ISSUE TITLE
Is it support Bookmark feature?

### ISSUE THREAD

**Issue by Maruf13** [barteksc/AndroidPdfViewer#348]
Please anyone tell me how implement bookmark feature to it .

**Comment by barteksc** [comment]
Did you read README?

**Comment by Maruf13** [comment]
Thanks for your reply. I read READE.md and sample. I also clone this project to android studio. But, i can not understand that support bookmark feature or not.  But in pdffium, i saw BookmarksTree. So i think its possible.

**Comment by barteksc** [comment]
This is main class from sample https://github.com/barteksc/AndroidPdfViewer/blob/master/sample/src/main/java/com/github/barteksc/sample/PDFViewActivity.java

**Comment by Maruf13** [comment]
thanks. but i think, like as foxit reader, page bookmarking feature is not available to it.

**Comment by Maruf13** [comment]
how make page swipe-horizontal sound for going to next page?

**Comment by barteksc** [comment]
Is swiping pages related to bookmarking?

**Comment by Maruf13** [comment]
no no. its another question. I can not solve those two questions.

**Comment by barteksc** [comment]
So please move second question to separated thread. 
You can read bookmarks as it is shown in sample

**Comment by Maruf13** [comment]
ok. thanks
