### ISSUE TITLE
Add annotation / comment support

### ISSUE THREAD

**Issue by KrawczykPawel** [barteksc/AndroidPdfViewer#349]
It will be amazing if the library will have a possibility to add note / annotation / comment to the pdf file with possibility to save it and then for example share it via email. Adobe Acrobat has this feature.

**Comment by barteksc** [comment]
It is PDF reader, I'm afraid that document editing will never be supported. Adobe Acrobat is huge commercial software

**Comment by KrawczykPawel** [comment]
I see. Sounds reasonable. Thank you for quick response.
