### ISSUE TITLE
Links in pdf page are not enabled

### ISSUE THREAD

**Issue by Alecsplus** [barteksc/AndroidPdfViewer#357]
I also try to enable annotation (.enableAnnotationRendering(true)) but internal pdf hyperLinks still not work... there is way to make them work?

Thanks in advance.

Alessandro

**Comment by barteksc** [comment]
No, unfortunately links are not implemented

**Comment by Alecsplus** [comment]
Do you know any way to implement it (also using other renderer)? I absolutely need them for my project. Thanks.

**Comment by barteksc** [comment]
If I know how do it, it would be implemented ;)
