### ISSUE TITLE
Print and Save to Device options

### ISSUE THREAD

**Issue by extravaganza47** [barteksc/AndroidPdfViewer#358]
I'm using this package to present a pdf on my app, and it's working really fine.
The issue now is: how can I have an option on the pdf screen to allow the user to directly print the pdf or to save it on the device?

Does this package support this features?

**Comment by barteksc** [comment]
Add a button to save document on the device.
There is no support for printing

**Comment by extravaganza47** [comment]
Is there an option for the save button? Thanks.

**Comment by barteksc** [comment]
What is the problem? Just add a button...

**Comment by extravaganza47** [comment]
How can I make the button save the pdf? Is there a way where I can get the pdf url or something?

**Comment by barteksc** [comment]
You passed pdf document to library, so you know where it is
