### ISSUE TITLE
Error in AnimationManager.java

### ISSUE THREAD

**Issue by coachsmr** [barteksc/AndroidPdfViewer#360]
I have an error in AnimationManager.java
 I am working with android studio.
This is the error:
'getScrollHandle()' is not public in 'com.github.barteksc.pdfviewer.PDFView'. Cannot be accessed from outside package

and this is the code with the error:
private void hideHandle() {
        if (pdfView.getScrollHandle() != null) {
            pdfView.getScrollHandle().hideDelayed();
        }
    }

**Comment by barteksc** [comment]
Probably you modified something, code pushed to repository is working

**Comment by barteksc** [comment]
Closing due to no response from author
