### ISSUE TITLE
Failed to resolve: com.github.barteksc:android-pdf-viewer:2.6.1

### ISSUE THREAD

**Issue by Abraxelx** [barteksc/AndroidPdfViewer#361]
When i adding compile inside my Gradle like: **compile 'com.github.barteksc:android-pdf-viewer:2.6.1'**
Android Studio threw this error "**Failed to resolve: com.github.barteksc:android-pdf-viewer:2.6.1** ". 
How can i fix it?
By the way i tried to add 'com.github.barteksc:android-pdf-viewer:2.7.0-beta.1' also. Same Error...
Thanks.

**Comment by ksp147** [comment]
yeh,i meet the same error，can  you help  me ?

**Comment by Abraxelx** [comment]
When i remove jUnit() and  changed my build.gradle like; 
allprojects {
    repositories {
        maven { url "http://jcenter.bintray.com" }
    }
}

its worked. Now working well, you can try also. And Lock this post please.

**Comment by Nirwal18** [comment]
When i remove jcenter(), because its reach end of its life.
allprojects {
repositories {
 jcenter()
}
}
I got error:
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.

**Comment by Krishnakumar59** [comment]
In gradle build 
make this change and sync 
it works

allprojects {
    repositories {
        maven { url "http://jcenter.bintray.com" }
        google()
//        mavenCentral()
//        jcenter() // Warning: this repository is going to shut down soon
    }
}

**Comment by gettipsbd-dev** [comment]
If your problem is not solved see this video 100% solved this error.
[](https://rtdev.xyz/barteksc-androidpdfviewer-failed-to-resolve-com-github-bartekscandroid-pdf-viewer-solved/)

**Comment by gettipsbd-dev** [comment]
If your problem is not solved see this video 100% solved this [https://rtdev.xyz/barteksc-androidpdfviewer-failed-to-resolve-com-github-bartekscandroid-pdf-viewer-solved/](url)

**Comment by Lord295** [comment]
when i add this below code to dependencies it gives ma a lots of errror:
allprojects {
repositories {
maven { url "http://jcenter.bintray.com" }
}
}



in app gradle  where to add the above code?????

**Comment by Krishnakumar59** [comment]
You have to replace
 compile to Implementation

**Comment by gettipsbd-dev** [comment]
Follow this video: https://youtu.be/QxrJHlffVwE

**Comment by aarafrao22** [comment]
Do Watch this video for the solution
`<iframe width="560" height="315" src="https://www.youtube.com/embed/Ir4rmSH52Rk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

**Comment by aarafrao22** [comment]
### SOLUTION
DO Watch this video
https://www.youtube.com/watch?v=Ir4rmSH52Rk

**Comment by aarafrao22** [comment]
You can also visit this article:
https://androidstudioo.com/failed-to-resolve-dependency-in-android-studio-bumblebee/

**Comment by NathanNovak** [comment]
I had the same thing happen after upgrading to React-Native 0.68.2. Had to add `gradlePluginPortal()` to allprojects in app/build.gradle

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
        gradlePluginPortal() **_<-- Add this._**
    }

**Comment by ehsan951** [comment]
در تاریخ پنجشنبه ۲۸ آوریل ۲۰۲۲،‏ ۲۲:۲۲ Rao Aaraf Younus <
***@***.***> نوشت:

**Comment by ShreeOcean** [comment]
> maven { url "http://jcenter.bintray.com" }

it is not building the project after implementing this line of code

**Comment by tanvirhossains** [comment]
maven { url "https://jcenter.bintray.com" }
use this instead of.
