### ISSUE TITLE
defaultPage() is not working

### ISSUE THREAD

**Issue by thousight** [barteksc/AndroidPdfViewer#369]
I've tried the defaultPage() way of restoring page scroll on orientation, but it is simply not bringing me to the page. I've tried jumpTo(), didn't work either.

Is this working for everyone else? If it is, how do you restore page scroll in activity?

Here is my code:

    public class MainActivity extends AppCompatActivity {

    private PDFView pdfView;
    private File samplePDF;
    private int pageNumber = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        if (savedInstanceState != null) {
            pageNumber = savedInstanceState.getInt("PDF_PAGE", 0);
        }

        // Create PDF view
        pdfView = (PDFView) findViewById(R.id.pdfView);

        // Get sample PDF file
        samplePDF = new File(Environment.getExternalStorageDirectory() + "/Download/" + "sample.pdf");
        if (!samplePDF.exists()) {
            // Get PDF file from assets
            copySamplePDFToDirectory(); // hidden in this sample, not important
            samplePDF = new File(Environment.getExternalStorageDirectory() + "/Download/" + "sample.pdf");
        }

        // Configure and load PDF view
        pdfView.fromFile(samplePDF)
                .defaultPage(pageNumber)
                .enableSwipe(true)
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .onRender(new OnRenderListener() {
                    @Override
                    public void onInitiallyRendered(int nbPages, float pageWidth, float pageHeight) {
                        pdfView.fitToWidth(); // Let document fit to screen width on orientation change
                    }
                })
                .onPageChange(new OnPageChangeListener() {
                    @Override
                    public void onPageChanged(int page, int pageCount) {
                        pageNumber = page;
                    }
                })
                .load();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putInt("PDF_PAGE", pdfView.getCurrentPage());
    }

    ...
    }

**Comment by barteksc** [comment]
You are using `fitToWidth()` withou parameter, you have to pass page number
