### ISSUE TITLE
Pixelation

### ISSUE THREAD

**Issue by akatamreddy** [barteksc/AndroidPdfViewer#37]
@barteksc - Awesome work.

I see pixelation on the top/middle of the page, while on certain devices. 

For example:-

Galaxy S6 & S7 Edge - I can see pixelation at the top.  

![screen shot 2016-07-18 at 4 42 49 pm](https://cloud.githubusercontent.com/assets/19594016/16931468/bd897ada-4d06-11e6-98b5-dda51d32de9e.png)

On other devices like HTC M8 it happens when I pinch/tap to zoom. Is there any way around this at the moment?

**Comment by LuigiCapasso** [comment]
I have the same problem ! any work around?

@barteksc - Awesome work.

**Comment by barteksc** [comment]
Should be fixed in 2.x
