### ISSUE TITLE
IS there any way to build with out x86 and x86_64

### ISSUE THREAD

**Issue by sairajkishore** [barteksc/AndroidPdfViewer#370]
IS there any way to build with out x86 and x86_64 as Apk size is increasing due to x86 and x86_64
.so files, which are only used for emulator purpose.

**Comment by 1stmetro** [comment]
Look in closed section lots of explanations on how to split the files to make a smaller apk

**Comment by barteksc** [comment]
There are many smartphones and tablets with x86 and x86_64 architecture...

**Comment by sairajkishore** [comment]
@barteksc Basically X86 is for Emulator, so i want to avoid X86.so files for production build.
is there any way to remove X86 and X86_64 so files so that it reduces my apk size.

**Comment by sairajkishore** [comment]
@barteksc Basically X86 is for Emulator, so i want to avoid X86.so files for production build.
is there any way to remove X86 and X86_64 so files so that it reduces my apk size.

**Comment by barteksc** [comment]
As I said, it is not only for emulator, there are devices with this architecture

**Comment by MaciejCzekanski** [comment]
You can use

android {
    defaultConfig {
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
}

@sairajkishore To only include arm libraries in your apk. But barteksc is right, x86 is *not* only for the emulator.
