### ISSUE TITLE
PDF with multiple page sizes

### ISSUE THREAD

**Issue by SinaMoetakef** [barteksc/AndroidPdfViewer#373]
Is there a way to render a DPF containing pages with different sizes (different aspect ratio) ?
I tried to load a document, it loads fine but the aspect ratio for pages with different sizes is not respected.

**Comment by 1stmetro** [comment]
its not been coded.. yet..

**Comment by barteksc** [comment]
Duplicate of #213.
This is known issue, currently there is no solution
