### ISSUE TITLE
How i can Make FullScreen PDFView When i Rotate Screen.

### ISSUE THREAD

**Issue by Abraxelx** [barteksc/AndroidPdfViewer#382]
Hi Could You help me please about making full screen pdfviewer when change rotation like lanscape.
I tried two methods but didnt work, 
**First one;**

```
        PDFView.Configurator.onRender(new OnRenderListener() {
            @Override
            public void onInitiallyRendered(int nbPages, float pageWidth, float pageHeight) {
                pdfView.fitToWidth();
            }
        });
```

**Second one;**

```
    @Override
    public void onConfigurationChanged(Configuration newConfig)
    {
        super.onConfigurationChanged(newConfig);
        if(newConfig.orientation ==Configuration.ORIENTATION_LANDSCAPE)
        {
            pdfView.fitToWidth();
        }
    }
```

Help me please how i can do that? By the way, i want to do this responsivelity.

**Comment by barteksc** [comment]
Pass page number to `fitToWidth()` method

**Comment by Abraxelx** [comment]
But this onRender method throw the error.

**Comment by Abraxelx** [comment]
**I update my second code like this:**

```
    @Override
    public void onConfigurationChanged(Configuration newConfig)
    {
        super.onConfigurationChanged(newConfig);
        if(newConfig.orientation ==Configuration.ORIENTATION_LANDSCAPE)
        {
            pdfView.fitToWidth(pdfView.getCurrentPage());
        }
    }
```

Still didnt work. For Render method i cant try because my method throwing error like this:
 **"non-static method 'onRender(com.github.barteks.pdfviewer.listener.OnRenderListener)' cannot be reference from a static context."**

**Comment by barteksc** [comment]
`.onRender()` method call is shown in the beginning of README, you cannot call this method statically

**Comment by Abraxelx** [comment]
But im reading PDF From Asset. Its didnt work at fromAsset method.

**Comment by Abraxelx** [comment]
I used method like this, still have same problem;
```
        pdfView.fromAsset("Heskatalog.pdf")
                .onRender(new OnRenderListener() {
            @Override
            public void onInitiallyRendered(int nbPages, float pageWidth, float pageHeight) {
                pdfView.fitToWidth(pdfView.getCurrentPage());
            }
        }).load();
```

**Comment by barteksc** [comment]
What problem do you have?

**Comment by ahmerafzal1** [comment]
```
.onRender(new OnRenderListener()
                {
                    @Override
                    public void onInitiallyRendered(int nbPages, float pageWidth, float pageHeight)
                    {
                        pdfView.fitToWidth(mCurrentPage);
                    }
                })
```

**Comment by Abraxelx** [comment]
When I rotate the screen like landscape , pdf is  not happen full screen

**Comment by Abraxelx** [comment]
I mean make this fullscreen;
[](http://prntscr.com/g5qxjl)

**Comment by Abraxelx** [comment]
@ahmerafzal1 did you check my post on top of you ? I already used same but didn't work. I dont know what should i do?

**Comment by ahmerafzal1** [comment]
@Abraxelx Pass page number e.g. `pdfView.fitToWidth(mCurrentPage);`

**Comment by Abraxelx** [comment]
@ahmerafzal1 

` pdfView.fitToWidth(pdfView.getCurrentPage());`
this is false?

**Comment by ahmerafzal1** [comment]
I'm not sure but it works me perfectly

**Comment by Abraxelx** [comment]
@ahmerafzal1  when my phone starting in Landscape rotation mode it working well but when startng in portrait mode and i rotate phone its happened small again.

**Comment by barteksc** [comment]
@Abraxelx after configuration change views are recreated, so current page is 0. But it should fit width anyway

**Comment by Abraxelx** [comment]
@barteksc  Then, what should i do, could you help me please?

**Comment by barteksc** [comment]
Storing current page between configuration changes is shown in sample. I don't know why it does not fit width in your case

**Comment by Abraxelx** [comment]
I found thats why made it. In my manifest i was have this code block;
`android:configChanges="orientation|screenSize"`
When i removed it its worked well.

**Comment by barteksc** [comment]
`onInitiallyRendered()` method was not called in this case, because view was not destroyed between configuration changes

**Comment by Abraxelx** [comment]
I see you can close this post thanks for all of your help :)

**Comment by ahmerafzal1** [comment]
If you getting failed email me I'll help you.

**Comment by Abraxelx** [comment]
@ahmerafzal1 i will text you now, thanks for help :)

**Comment by amit6663** [comment]
@Abraxelx did you get the solution? If did then share here please, I'm getting the same problem.

**Comment by Abraxelx** [comment]
@amit6663  Remove below code block if you have it:

`android:configChanges="orientation|screenSize"
`
