### ISSUE TITLE
Is it possible to jump between two pages?

### ISSUE THREAD

**Issue by Abraxelx** [barteksc/AndroidPdfViewer#384]
For example If i want to show pages between 15  - 100 is it possible with this library ?

**Comment by barteksc** [comment]
You have to pass all pages numbers to `.pages(...)` method

**Comment by Abraxelx** [comment]
But i want to use it when i clicking somethings.

**Comment by barteksc** [comment]
You want to show pages between 15 - 100 when clicking something, I don't understand what do you mean.

**Comment by Abraxelx** [comment]
@barteksc  Yes. I have a listview when i clicking items i want to jump for example between 15 -100

**Comment by barteksc** [comment]
So, use `.jumpTo()` method

**Comment by CityInTheWind** [comment]
还是000000啊0黄0噼里啪啦怕000了他了'他

发自我的vivo智能手机

Halil Şahin <notifications@github.com>编写：

**Comment by Abraxelx** [comment]
@barteksc  bu .jumpTo() just accept one varilable

**Comment by barteksc** [comment]
@CityInTheWind please write in english and translate your comment
@Abraxelx you can jump to page when you click something, there is no solution that will do everything for you

**Comment by 1stmetro** [comment]
If you use the listview as an index and on click jump to the chapter page so to speak.

That's simple enough!

**Comment by barteksc** [comment]
Closing due to no response from author
