### ISSUE TITLE
com.github.barteksc.pdfviewer.PDFView.f(PDFView.java:1009)

### ISSUE THREAD

**Issue by 867588763** [barteksc/AndroidPdfViewer#387]
com.github.barteksc.pdfviewer.PDFView.f(PDFView.java:1009)
2 com.github.barteksc.pdfviewer.d.onScroll(DragPinchManager.java:136)
3 android.view.GestureDetector.onTouchEvent(GestureDetector.java:607)
4 com.github.barteksc.pdfviewer.d.onTouch(DragPinchManager.java:200)
5 android.view.View.dispatchTouchEvent(View.java:10033)
6 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2628)
7 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
8 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
9 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
10 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
11 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
12 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
13 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
14 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
15 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
16 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
17 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
18 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
19 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
20 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
21 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
22 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)
23 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
24 android.app.Activity.dispatchTouchEvent(Activity.java:3195)
25 android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
26 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
27 android.view.View.dispatchPointerEvent(View.java:10266)
28 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4529)
29 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4394)
30 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3927)
31 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3980)
32 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3946)
33 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4073)
34 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3954)
35 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4130)
36 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3927)
37 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3980)
38 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3946)
39 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3954)
40 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3927)
41 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6344)
42 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6318)
43 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6279)
44 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6469)
45 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
46 android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
47 android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
48 android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6418)
49 android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6492)
50 android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
51 android.view.Choreographer.doCallbacks(Choreographer.java:688)
52 android.view.Choreographer.doFrame(Choreographer.java:617)
53 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
54 android.os.Handler.handleCallback(Handler.java:754)
55 android.os.Handler.dispatchMessage(Handler.java:95)
56 android.os.Looper.loop(Looper.java:160)
57 android.app.ActivityThread.main(ActivityThread.java:6274)
58 java.lang.reflect.Method.invoke(Native Method)
59 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
60 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)

**Comment by 1stmetro** [comment]
And....

**Comment by barteksc** [comment]
Closing due to no response from author
