### ISSUE TITLE
How to add or attach new page ?

### ISSUE THREAD

**Issue by babulpatel1309** [barteksc/AndroidPdfViewer#389]
Is that possible to edit pdf. Edit in the sense i want to attach 1 page at the end of the pdf. Is there any method to do that?

**Comment by barteksc** [comment]
No, it is not possible

**Comment by 1stmetro** [comment]
You can create your own method !

**Comment by babulpatel1309** [comment]
I come up with the PDFBox solution.

Create or edit pdf with PDFBox and load it with this library
