### ISSUE TITLE
Open pdf file in internal storage

### ISSUE THREAD

**Issue by Henqsan** [barteksc/AndroidPdfViewer#391]
How to open pdf file that is in internal storage?

**Comment by 1stmetro** [comment]
Use a file manager to get the path then copy it so you can see it works after that use the system commands to generate the same path it can change per OS version so best to have something that works and move on from there

**Comment by barteksc** [comment]
You can use `pdfView.fromFile(File)`

**Comment by barteksc** [comment]
Closing due to no response from author
