### ISSUE TITLE
Kotlin usage

### ISSUE THREAD

**Issue by cfmlam** [barteksc/AndroidPdfViewer#393]
Hello, i have migrating my code from java to kotlin.
This library is so good and working perfectly in Java.
But i think it is not compatible with Kotlin yet?
I have tried a few pdf files but it cannot render it to the viewer.
It seems that i can load the page of PDF but not able to render it

**Comment by cfmlam** [comment]
Oops, i have found out the problem.
We can use it with Kotlin

**Comment by Lucasark** [comment]
And solution?
