### ISSUE TITLE
ContentUris support: content://...

### ISSUE THREAD

**Issue by flieks** [barteksc/AndroidPdfViewer#397]
Would this work with content Uri's ? 
https://developer.android.com/reference/android/content/ContentUris.html

**Comment by flieks** [comment]
ok found it
`InputStream s = getContentResolver().openInputStream(myUri);`
but it could also work with 
`pdfView.fromAsset(path);` (i'll test)

**Comment by barteksc** [comment]
You may use `.fromUri()`
