### ISSUE TITLE
onTapListener

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#398]
Hey what is the on tap listener used for?

**Comment by barteksc** [comment]
It is called when you single tap PDFView. And you get `MotionEvent` event

**Comment by 1stmetro** [comment]
Any why is it needed ? any what would someone use it for ?

**Comment by barteksc** [comment]
When you want to know where did the user click. Plus it is better than standard click listener because tap listener it will be called only when single tap occurred.

**Comment by 1stmetro** [comment]
Only just saw the update, so basically the tap and the divide by zero fixes.

Anything else new in this release ?

**Comment by barteksc** [comment]
No, that's all

**Comment by 1stmetro** [comment]
I did create water marking if that is of any use to you, but i presume you already know how to do that.
