### ISSUE TITLE
E/jniPdfium: Bitmap format must be RGBA_8888

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#399]
I used to allow the app to use lower quality, but it now just goes black with the error, 

E/jniPdfium: Bitmap format must be RGBA_8888

Not sure if this is a bug or the code has been amended to only allow RGBA 8888

**Comment by barteksc** [comment]
Which version do you use? How do you include library in your app?

**Comment by 1stmetro** [comment]
i include source with gradle, not seen the error before when i normally include it which is why i posted my question

**Comment by barteksc** [comment]
Probably you don't have newest PdfiumAndroid

**Comment by 1stmetro** [comment]
if i remove the try statements it does not error just shows black if i change to RGB888 it shows fine.

Where am i updating pdfium i thought i had the latest version of that....

try {
            render = Bitmap.createBitmap(w, h, renderingTask.bestQuality ? Bitmap.Config.ARGB_8888 : Bitmap.Config.RGB_565);
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
            return null;
        }

**Comment by 1stmetro** [comment]
ah i was using 1.6.1 just upgrading to version 1.7.0
