### ISSUE TITLE
Turn pages when zooming.

### ISSUE THREAD

**Issue by ENOZA** [barteksc/AndroidPdfViewer#4]
It would be great if we can turn pages when the view is being zoomed.
I checked DragPinchManager.java and realized that onDrag() and endDrag() methods ignore events when isZooming() returns true.
Is it possible to handle these events?
What changes should be made on PDFView.java for that?

**Comment by barteksc** [comment]
It is quite hard to do it well currently, now I'm working on continuous scroll through whole document that will eliminate this problem

**Comment by ENOZA** [comment]
@barteksc, thank you very much. I am really looking forward to the new function for continuous scrolling!

**Comment by IdioticMadman** [comment]
@barteksc Have this issue be fixed?Or there have some idea can fix it?

**Comment by sssvrock** [comment]
@barteksc Please let us know once you fixed this and tell me about the function to be used for navigating to other page even in zoomed state.

**Comment by barteksc** [comment]
Version 2.0.0 introduced continuous scroll, which eliminates this problem.
