### ISSUE TITLE
FileNotFoundException does not trigger neither onError() nor any other listener

### ISSUE THREAD

**Issue by 39otrebla** [barteksc/AndroidPdfViewer#401]
This is an huge missing, since you are catching the exception.

**Comment by barteksc** [comment]
`FileNotFoundException` triggers `OnErrorListener` passed to `onError()` method.

**Comment by 39otrebla** [comment]
Thanks for the prompt reply. This is not happening on my side, the listener is not triggered, but let me double check. Thanks.

**Comment by barteksc** [comment]
Please show your code

**Comment by barteksc** [comment]
Closing due to no response from author
