### ISSUE TITLE
E/jniPdfium: Bitmap format must be RGBA_8888

### ISSUE THREAD

**Issue by YiiGuxing** [barteksc/AndroidPdfViewer#408]
v2.7.0
pdf:[AO3404A.pdf](https://github.com/barteksc/AndroidPdfViewer/files/1313956/AO3404A.pdf)

**Comment by barteksc** [comment]
How do you include library to your project? Probably you have old PdfiumAndroid version

**Comment by YiiGuxing** [comment]
compile 'com.github.barteksc:android-pdf-viewer:2.7.0'

**Comment by YiiGuxing** [comment]
v2.6:
![2_6](https://user-images.githubusercontent.com/10737066/30590247-5ca24362-9d70-11e7-8b03-fbbab6852523.png)
v2.7:
![2_7](https://user-images.githubusercontent.com/10737066/30590259-65435ee8-9d70-11e7-97c3-dceed4722881.png)

**Comment by 1stmetro** [comment]
Update the pdfium in the app to resolve the black screen, look in the compile modules and update the version to the latest.
