### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by ChenXiaoYao407** [barteksc/AndroidPdfViewer#409]
您好，怎么能设置成你demo里那个页面的样式呢？我没有找到相应代码，请指教。

**Comment by barteksc** [comment]
Please translate issue to english

**Comment by ChenXiaoYao407** [comment]
Hello, how can you set the style of the page in your presentation? I did not find the corresponding code, please advise.

**Comment by barteksc** [comment]
What is "the style of the page"?

**Comment by 1stmetro** [comment]
Erm in the style file..... like normal.

**Comment by ChenXiaoYao407** [comment]
![image](https://user-images.githubusercontent.com/28752258/30779628-2e79df7a-a128-11e7-9b7b-b1182f01d547.png)

Hello, where do you add the page number? I did not find the code, please advise.

**Comment by barteksc** [comment]
This is ScrollHandle, it is explained in readme
