### ISSUE TITLE
Make my app default  app for pdf file

### ISSUE THREAD

**Issue by albakaly** [barteksc/AndroidPdfViewer#416]
This lib required link or a path for its pdf view widget for any file to open it.
Is there a way to open any file with this lib without providing a link or path just with manifest  intentfilter

**Comment by 1stmetro** [comment]
Sounds like you want to use a resource which I believe is possible although I have not used that process.

**Comment by albakaly** [comment]
Thank you,
I have it done ,
Just i coud not find the suitable  words for google
Fortunately I found it by chance
The solution  was:
Intent i = getIntent();
		Uri path1 = i.getData();
		String path = path1.getEncodedPath();
                pdfView.fromFile(new File(path))
