### ISSUE TITLE
want to get the current page number from pdf file

### ISSUE THREAD

**Issue by IORDevelopers** [barteksc/AndroidPdfViewer#417]
I'm displaying the PDF from a file stored in storage,
but every time while opening, i'm getting the PDF from 1st page,
I just want to store the current page number when the user presses the Android BackButton.
I'm using this function PDFView.fromFile(FileName).load();

**Comment by 1stmetro** [comment]
There are a couple of ways to do this,

Simple way pass the page number and filename between activities then just .load (pagenumber) or how ever it loads pages and compare the filename otherwise any pdf you open will load on the stored page number.

Kind starts you off in the right direction....

**Comment by barteksc** [comment]
Closing due to no response from author
