### ISSUE TITLE
Can words in pdf be selected by Long-click like FBReader?

### ISSUE THREAD

**Issue by Songsayit** [barteksc/AndroidPdfViewer#422]
Hi, I get confused when I use the demo. The words in pdf (i.e., sample.pdf in demo) can NOT be selected by long-click.  [The FBReader pdf plugin](https://fbreader.org/content/fbreader-pdf-plugin) works well. Is there some wrong with technology about PdfiumAndroid?

**Comment by 1stmetro** [comment]
This code is on going so features are added as as when.

**Comment by Songsayit** [comment]
Do you mean that Your team will add the features of word-selected ?

**Comment by 1stmetro** [comment]
the team is basically software devs that write code to add abilities to their own app and share with other devs.  This is open source so additions are generally added by everyone.

**Comment by Songsayit** [comment]
Thanks for your replay.
