### ISSUE TITLE
Remove state between pages while scrolling horizontally

### ISSUE THREAD

**Issue by lmdic** [barteksc/AndroidPdfViewer#425]
Here my snippet:

```
   pdfView = findViewById(R.id.pdfView);
        pageNumberTextView = findViewById(R.id.pageNumberTextView);
        pdfView.fromAsset("portrait.pdf")
                .defaultPage(currentPage)
                .onPageChange(this)
                .enableAntialiasing(false)
                .swipeHorizontal(true).load();
```

And it's work fine. OK.
Here result:

![swipe_between_pages](https://user-images.githubusercontent.com/303539/31558668-88b7c488-b056-11e7-8bbb-1701f32b9f08.png)

As you can see when I stop swiping horizontally the pdfViewer can stop between pages. But I wan't this behavior. How I can remove this effect?

**Comment by barteksc** [comment]
You may use [AndroidPdfViewerV1](https://github.com/barteksc/AndroidPdfViewerV1)

**Comment by lmdic** [comment]
Do you mean this:

`compile 'com.github.barteksc:android-pdf-viewer:1.6.0'`

and in Android code:

```
     pdfView.fromAsset("portrait.pdf")
                .defaultPage(currentPage)
                .enableSwipe(false)
                .onPageChange(this)
                .load()
```

?

**Comment by 1stmetro** [comment]
From memory if you adjust the fit to width code you can remove the white to a certain amount

**Comment by 1stmetro** [comment]
My old fork has code to remove borders on orientation which after looking twice is what this may appear to be, change the border color to confirm.

**Comment by ManojKumar-MK** [comment]
**This code working perfectly.**


  pdfView.fromStream(inputStream)
                    .enableDoubletap(true)
                    .enableSwipe(true)
                    .pageSnap(true)
                    .autoSpacing(true)
                    .pageFling(true)
                    .swipeHorizontal(true)
                    .pageFitPolicy(FitPolicy.BOTH)
                    .onPageChange(new OnPageChangeListener() {
                        @Override
                        public void onPageChanged(int page, int pageCount) {
                            Log.d("Check","Check : "+inputStream);
                            Log.d("Check","Check : "+page);
                        }
                    })
                    .load();
            ;
