### ISSUE TITLE
Scroll handler and getCurrentPage have different indexes,

### ISSUE THREAD

**Issue by abbasEbadian** [barteksc/AndroidPdfViewer#426]
Hi. First of all i should appreciate for this awesome and useful library. 
A tiny bug was there and i decided to propound it here
The ScrollHandler starts counting  pages from 1 while getCurrentPage()  and onPageChangeListener () counting from 0. I thought it can be lilbit confusing. 
And i think starting from 1 is  more reasonable for a pdf viewer. 
Thank You.

**Comment by barteksc** [comment]
This is intended behavior - ScrollHandle shows page number (it would be strange for user to see page number 0) and rest of API returns page index - for programmers zero-based indexing is common
