### ISSUE TITLE
how i can to fixed the url of pdf ??

### ISSUE THREAD

**Issue by husamkod** [barteksc/AndroidPdfViewer#427]
hello
i want to update the pfd document every week with not update the app
how i can to fixed the url of pdf ??

**Comment by 1stmetro** [comment]
Just use ddns or static address and then have it download weekly if the info file shows a different version number, ie a raw text file html etc  save the new version number on the device and check weekly before updating again, updating the local version number or date as it does it's weekly update. 

It's a simple thing to do.

**Comment by barteksc** [comment]
Closing due to author's inactivity
