### ISSUE TITLE
E/UncaughtException: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#429]
This error seems to happen a bit recently, any ideal ?

E/UncaughtException: java.util.ConcurrentModificationException
                                                                                          at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                                          at com.github.barteksc.pdfviewer.PDFView.onDraw(PDFView.java:675)

Line 675 Contains,

        for (Integer page : onDrawPagesNums) {
            drawWithListener(canvas, page, onDrawAllListener);
        }
        onDrawPagesNums.clear();

**Comment by 1stmetro** [comment]
Appears my overlay image  code must have been trying to overlay before the pdf view was generated or something...

**Comment by barteksc** [comment]
Did you solve this issue? And please don't add usernames to issue title...

**Comment by 1stmetro** [comment]
I think i found the issue, my code was checking the orientation of the device which on occasion would show an error if there is an error with the actual pdf, it because more relevant with a faulty pdf so disabled the orientation checking currently.

Bit of a strange one but updated a few things so will see what it does now.
