### ISSUE TITLE
I want to mark on pdf

### ISSUE THREAD

**Issue by sapq** [barteksc/AndroidPdfViewer#430]
hi

thank you for PdfViewer

I want to know if i Can I make mark  on page

Example

i open pdf with  AndroidPdfViewer i stop on page 20 

When i open  next time i want pdf open on page 20 not page 1
If there is such a thing will be very cool
thank you

**Comment by 1stmetro** [comment]
You add your own code to do this. It's just a case of storing the page and passing to page number when you reopen.

**Comment by barteksc** [comment]
Closing due to no response from author

**Comment by sapq** [comment]
hi how i do this i dont no

**Comment by 1stmetro** [comment]
Easiest was is pass the page number with the intent... then load the page number passed by the intent.

**Comment by barteksc** [comment]
@sapq If you want to store page number on configuration change, then you have to save it in `onSaveInstanceState()` and restore in `onRestoreInstanceState()`. If you want to store page number for longer period, you may use `SharedPreferences`. In both cases you have to pass stored page number to `.defaultPage(int)` method, when opening PDF document.

**Comment by sapq** [comment]
can i have code sample pls thank you  this will help me

**Comment by barteksc** [comment]
I gave you whole idea, if you still don't know how to do it, please learn Android API. Your problem is not related to this library. Using google you will find tons of articles about storing activity state.

**Comment by sapq** [comment]
i just want no how i do this  i dont have  Experience

**Comment by barteksc** [comment]
As I said, there are many articles about storing activity state, use google to find them.

**Comment by sapq** [comment]
i try use this  but not work  pls tell me what the  proplem


`@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.newpdf);
        pdfView = (PDFView) findViewById(R.id.pdfView);
        displayFromAsset(SAMPLE_FILE);
    }

    private void displayFromAsset(String assetFileName) {
        pdfFileName = assetFileName;

        pdfView.fromAsset(SAMPLE_FILE)
                .defaultPage(SharedPreferences)
                .enableSwipe(true)
                .swipeHorizontal(false)
                .onPageChange(this)
                .enableAnnotationRendering(true)
                .onLoad(this)
                .scrollHandle(new DefaultScrollHandle(this))
                .spacing(10)
                .load();
    }


    @Override
    public void onPageChanged(int page, int pageCount) {
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putInt(name,page);
        editor.commit();
    }


    @Override
    public void loadComplete(int nbPages) {
        PdfDocument.Meta meta = pdfView.getDocumentMeta();
        printBookmarksTree(pdfView.getTableOfContents(), "-");

    }

    public void printBookmarksTree(List<PdfDocument.Bookmark> tree, String sep) {
        for (PdfDocument.Bookmark b : tree) {

            Log.e(TAG, String.format("%s %s, p %d", sep, b.getTitle(), b.getPageIdx()));

            if (b.hasChildren()) {
                printBookmarksTree(b.getChildren(), sep + "-");
            }
        }
    }`

**Comment by sapq** [comment]
i fix my proplem thank you 

`   public static final String MY_PREFS_NAME = "MyPrefsFile";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.newpdf);
        pdfView = (PDFView) findViewById(R.id.pdfView);
        displayFromAsset(SAMPLE_FILE);
    }

    private void displayFromAsset(String assetFileName) {
        pdfFileName = assetFileName;

        pdfView.fromAsset(SAMPLE_FILE)
                .defaultPage(getPageNumber())
                .enableSwipe(true)
                .swipeHorizontal(false)
                .onPageChange(this)
                .enableAnnotationRendering(true)
                .onLoad(this)
                .scrollHandle(new DefaultScrollHandle(this))
                .spacing(10)
                .load();
    }


    @Override
    public void onPageChanged(int page, int pageCount) {

        setPageNumber(page)
        setTitle(String.format("%s %s / %s", pdfFileName, (getPageNumber() + 1), pageCount));
    }


    @Override
    public void loadComplete(int nbPages) {
        PdfDocument.Meta meta = pdfView.getDocumentMeta();
        printBookmarksTree(pdfView.getTableOfContents(), "-");

    }

     public void setPageNumber(int pageNumber) {
            SharedPreferences.Editor editor = getSharedPreferences(MY_PREFS_NAME, MODE_PRIVATE).edit();
            editor.putInt("page_number", pageNumber);
            editor.apply();
        }

        public int getPageNumber() {
            SharedPreferences prefs = getSharedPreferences(MY_PREFS_NAME, MODE_PRIVATE);
            return prefs.getInt("page_number", 0);
        }

    public void printBookmarksTree(List<PdfDocument.Bookmark> tree, String sep) {
        for (PdfDocument.Bookmark b : tree) {

            Log.e(TAG, String.format("%s %s, p %d", sep, b.getTitle(), b.getPageIdx()));

            if (b.hasChildren()) {
                printBookmarksTree(b.getChildren(), sep + "-");
            }
        }   
    }`

**Comment by sapq** [comment]
I have a problem  if  i have 40 PDF

when i use frist pdf i go page number 10 and i closed

the proplem is all  pdf when i open go page number 10

what i do to fix this proplem any idia 

thank you

**Comment by 1stmetro** [comment]
You also need to store the pdf path and if it reopens the and pdf reuse the page number otherwise use page 0.
