### ISSUE TITLE
java.lang.NegativeArraySizeException: -543

### ISSUE THREAD

**Issue by calvinrnp** [barteksc/AndroidPdfViewer#434]
When i try to run the app it crashes and shows this error message:

>java.lang.NegativeArraySizeException: -543
>                                                                       at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:323)
>                                                                       at com.android.volley.toolbox.DiskBasedCache.get(DiskBasedCache.java:119)
>                                                                       at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:100)

This is my activity code snippet to show the pdf
```
        PDFView pdfView = (PDFView)findViewById(R.id.pdfView);
        pdfView.fromAsset("example.pdf").load();
```

and this is my activity xml

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">

        <include android:id="@+id/toolbar"
            layout="@layout/toolbar"/>

        <com.github.barteksc.pdfviewer.PDFView
            android:id="@+id/pdfView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@+id/toolbar" />

</RelativeLayout>

```

**Comment by barteksc** [comment]
Stacktrace is from volley...
