### ISSUE TITLE
Can not read some hindi font pdfs

### ISSUE THREAD

**Issue by khemrajsharma** [barteksc/AndroidPdfViewer#436]
Hi sir,
I am using your library for reading pdfs.
Client tells an issue.
Here is an link that is an hindi font pdf, library can not read it properly, fonts are misbehaved in app.
https://www.flexiprep.com/d/pdf/c1cdb1e0/NCERT-Hindi-Class-9-Hindi-Part-4.pdf
![screenshot_20171027-153717](https://user-images.githubusercontent.com/23208140/32099177-e6294c64-bb2c-11e7-8643-d40f5784ddeb.png)

**Comment by barteksc** [comment]
I don't know hindi so I don't know where it is incorrectly rendered. 
Are these hindi fonts embedded in pdf document?

**Comment by barteksc** [comment]
Closing due to no response from author
