### ISSUE TITLE
How handle click on pdfViewer?

### ISSUE THREAD

**Issue by lmdic** [barteksc/AndroidPdfViewer#437]
Here my code in activity:

```
private void openFromLocalStorage(String pdfUrl) {
        File pdfFile = FileUtil.getFromDir(this, pdfUrl);
        pdfView.fromFile(pdfFile)
                .defaultPage(currentPage)
                .enableSwipe(false)
                .onPageChange(this)
                .load();
    }
```

OK. It's work fine.
When I double click on `pdfView `then it zoom. OK.
But I need to handle simple click on `pdfView`. 
How I can do this?

**Comment by barteksc** [comment]
Use `.onTap()`, it is in readme

**Comment by lmdic** [comment]
`onTap` is only from ver. **2.8.0**
But I use version **1.6.0** . 
I user version **1.6.0**  because it has horizontall scrolling. But in version **2.8.0** no horizontall scrolling.
So the question is:

How I can do handle click and not to lose horizontall scrolling?

**Comment by barteksc** [comment]
You created issue in incorrect repository, there is AndroidPdfViewerV1 repo for version 1.x.
`onTap()` is from 2.7.0.
All version have horizontal scroll.
If you want to use 1.x you may only use standard `View`'s method `setOnClickListener()`

**Comment by barteksc** [comment]
Use `.swipeHorizontal(true)`, it is in readme.

**Comment by lmdic** [comment]
If I use `.swipeHorizontal(true)` then pdfViews can stay between pages. 
Here details: 
https://github.com/barteksc/AndroidPdfViewer/issues/425

So as result I use `.enableSwipe(false)` - this what I need.
But I can't single click by `.onTap`

So I result the solution is to use: standard `setOnClickListener()`

Is I'm right?

**Comment by barteksc** [comment]
You asked for horizontal scroll, not for single-page scroll. Version 2.x only have continuous scroll.

**Comment by lmdic** [comment]
OK. Thanks. The solution is `setOnClickListener()`
