### ISSUE TITLE
When using pages() it stretch bitmap

### ISSUE THREAD

**Issue by Sumeet21** [barteksc/AndroidPdfViewer#440]
I want to show user pages from 21 to 30
so i use pdfView.pages(21,....30), but it stretch pdf page content, is there any alternative way to prevent user when page number exceed from range?

**Comment by 1stmetro** [comment]
It will stretch depending if it's portrait or landscape pdf and if is side or horizontal swipes etc. I modified the resize code months ago to resolve this just amend the resize code.

**Comment by Sumeet21** [comment]
Thanks @1stmetro but i could not find any commit about resize code, can you provide commit hash?

https://github.com/1stmetro/AndroidPdfViewer/commits/master
https://github.com/barteksc/AndroidPdfViewer/commits/master

**Comment by Sumeet21** [comment]
Actually my issue is when i use range pages(...) than pdf view tries to fit document-page into device resolution and when i show full pdf (not using pages) it shows as normal page, and also when using pages and use method fitToWidth the double tap zoom mis-behave

**Comment by Sumeet21** [comment]
i have fixed this issue,  it scale bitmap due to different size of pages, already open an issue #213 and #373
