### ISSUE TITLE
Is there a way to get thumbnail in this library for files?

### ISSUE THREAD

**Issue by albakaly** [barteksc/AndroidPdfViewer#441]
I loaded the pdf files in a recyclerview I need to get thumbnail image of these file , how to do it?
When i put a pdfview , it is slow the recyleview scrolling and sometimes crash,
How to make it soomth scrolling ?

**Comment by 1stmetro** [comment]
Just take a thumbnail of the view same as any view, it's code outside of pdf view that you write to take a thumb of the view, it's a few lines of code.

**Comment by albakaly** [comment]
Thank you 1stmetro , 
I just get the thumbnail from parcelFileDescriptor 
and PdfiumCore to convert to Bitmap then set this bitmap in image view.

Thanks

**Comment by BinarySatan** [comment]
@albakaly  how to get the thumbnail from parcelFileDescriptor ?
