### ISSUE TITLE
How to I add the app into app chooser?

### ISSUE THREAD

**Issue by Luberen** [barteksc/AndroidPdfViewer#444]
I'm making PDF viewer app with this library.
I want to add my app into "Complete action using" list but it doesn't work well...
I added intent to PDFViewActivity.java but the app just shut down.
Are there any special methods I should use?

**Comment by 1stmetro** [comment]
Post some code so we can see what your trying to do...

**Comment by Luberen** [comment]
I've solved the problem now.
I added intent filter to init() method of PDFViewActivity.java file.

**Comment by barteksc** [comment]
Added invalid label as issue is not related to AndroidPdfViewer but to Android API
