### ISSUE TITLE
Blurred text after calling the method "jumpTo()" 

### ISSUE THREAD

**Issue by albka1986** [barteksc/AndroidPdfViewer#448]
I have a problem with method jumpTo, after calling it, system is blurring a text. If I make handle scroll everything is ok.
http://prntscr.com/h9i4yb

pdfView.fromAsset(fileName)
                .enableSwipe(true) // allows to block changing pages using swipe
                .swipeHorizontal(true)
                .enableDoubletap(true)
                .defaultPage(startPage)
                .onPageChange(this)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .scrollHandle(null)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                .spacing(0)
                .invalidPageColor(Color.WHITE) // color of page that is invalid and cannot be loaded
                .load();

**Comment by AhmerAfzal1** [comment]
Same issue

**Comment by barteksc** [comment]
@albka1986 Which version are you using?

**Comment by albka1986** [comment]
@barteksc  
3.0.0-beta.1

**Comment by barteksc** [comment]
There is special issue for reporting beta related issues - #447

**Comment by albka1986** [comment]
@barteksc 
In version 2.8.1 it reproduces too.

**Comment by barteksc** [comment]
@albka1986 please check whether 3.0.0-beta.2 fixes this issue

**Comment by albka1986** [comment]
@barteksc 
Now it works good. The bug is not reproduce.
Thanks! :-)

**Comment by AadilDAR** [comment]
I am Still getting this error. Can u plz explain how u got out of this.

i tested lib ver. 
compile 'com.github.barteksc:android-pdf-viewer:3.0.0-beta.2'
compile 'com.github.barteksc:android-pdf-viewer:2.8.0'
compile 'com.github.barteksc:android-pdf-viewer:2.7.0'
from all of the above versions i got the blurred view.

**Comment by AadilDAR** [comment]
my method

pdfView=(PDFView) findViewById(R.id.pdfView);
        pdfView.fromAsset("yks.pdf")
                .defaultPage(1)
                .spacing(10)
                .load();
    }

    public void nextPage(View view){pdfView.jumpTo(pdfView.getCurrentPage()+1,true);
    pdfView.loadPages();}

    public void prevPage(View view){pdfView.jumpTo(pdfView.getCurrentPage()-1,true);
    pdfView.loadPages();}

    public void zoomIn(View view){
        ++zoomValue;
        pdfView.zoomTo(zoomValue);
        pdfView.loadPages();
    }
    public void zoomOut(View view){
        if (zoomValue!=1){
            --zoomValue;
            pdfView.loadPages();
        }
    }
