### ISSUE TITLE
why all configuration methods are now private for 2.8.0 version? Like setDefaultPage() and etc.

### ISSUE THREAD

**Issue by developer--** [barteksc/AndroidPdfViewer#452]

**Comment by barteksc** [comment]
`setDefaultPage()` method is private since first version of this library

**Comment by developer--** [comment]
And why do u have it in readme file?

"All available options with default values:" here is setDefault method... 

Ok and is there any way to set page with specific number?

**Comment by barteksc** [comment]
Where do you see `setDefaultPage()` in readme? There is whole section in readme that shows how to load document and configure view https://github.com/barteksc/AndroidPdfViewer#load-a-pdf-file . There is also sample app in root of repository

**Comment by 1stmetro** [comment]
set page number - 

.defaultPage(pageNumber)
