### ISSUE TITLE
Blurred text after calling the method "jumpTo()" 

### ISSUE THREAD

**Issue by AadilDAR** [barteksc/AndroidPdfViewer#455]
i tested lib ver.
compile 'com.github.barteksc:android-pdf-viewer:3.0.0-beta.2'
compile 'com.github.barteksc:android-pdf-viewer:2.8.0'
compile 'com.github.barteksc:android-pdf-viewer:2.7.0'
from all of the above versions i got the blurred view.

**Comment by AadilDAR** [comment]
my method

pdfView=(PDFView) findViewById(R.id.pdfView);
pdfView.fromAsset("yks.pdf")
.defaultPage(1)
.spacing(10)
.load();
}

public void nextPage(View view){pdfView.jumpTo(pdfView.getCurrentPage()+1,true);
pdfView.loadPages();}

public void prevPage(View view){pdfView.jumpTo(pdfView.getCurrentPage()-1,true);
pdfView.loadPages();}

public void zoomIn(View view){
    ++zoomValue;
    pdfView.zoomTo(zoomValue);
    pdfView.loadPages();
}
public void zoomOut(View view){
    if (zoomValue!=1){
        --zoomValue;
        pdfView.loadPages();
    }
}

**Comment by 1stmetro** [comment]
Send the pdf so I can test it

**Comment by barteksc** [comment]
@AadilDAR  don't call `pdfView.loadPages()`

**Comment by AadilDAR** [comment]
THEN WHAT TO CALL INSTEAD

**Comment by AadilDAR** [comment]
I WRITE THIS WHEN I SAW A COMMENT OF U REGARDING THIS ISSUE

**Comment by barteksc** [comment]
@AadilDAR Nothing.
And please don't write uppercase.

**Comment by AadilDAR** [comment]
BUT AFTER REMOVING   pdfView.loadPages() I STILL GOT THE ISSUE
I INSERTED pdfView.loadPages() LINE WHEN I SAW A COMMENT OF U REGARDING THIS ISSUE

**Comment by AadilDAR** [comment]
plz give a good explaination regarding the issue

**Comment by AadilDAR** [comment]
link to pdf is 
http://www.ahlesunnatpak.com/wp-content/uploads/2014/ResearchPaper/YAZEED-ki-Shakhsiyat(By-Mohaddis-Ibn-e-JAOZI-r.a).pdf

**Comment by barteksc** [comment]
@AadilDAR
Try to use `pdfView.jumpTo(int)` method (without second parameter) until this issue is fixed.

**Comment by joielechong** [comment]
+1 for this issue. I also experience the blurred text when using `jumpTo(int, boolean)`. No problem when using `jumpTo(int)`. Sorry, I can't share the pdf because it's a copyrighted material.

**Comment by barteksc** [comment]
Fixed in 2.8.2 and 3.0.0-beta.4

**Comment by AadilDAR** [comment]
Thanks will check it soon

**Comment by joielechong** [comment]
Thank you very much for your time and hard works! It's working now!

**Comment by earamsey** [comment]
can the pdfviewer dial phone numbers inside pdf?
