### ISSUE TITLE
Blurred document when loading whole document

### ISSUE THREAD

**Issue by bdariusb** [barteksc/AndroidPdfViewer#456]
Hello. Is there a way to force the library to load the whole document? For example PdfView layout's height is 10000 dp and I want to load a document to it. After the first one or two pages while scrolling the view the document becomes blurred. This view is included in a recycler view.

**Comment by barteksc** [comment]
Does this document load while scrolling or it stays blurred?

**Comment by bdariusb** [comment]
if the document is long, for example 4 pages long, the first two pages load, however when scrolling further, other pages stay blurred. The height of the view is something like 4 * (page height) which is approx 10000 or so. As it is in the recycler view, the native scrolling functionality of pdfview is not being used, so that the whole document can be loaded at once. I hope you understand the issue

**Comment by barteksc** [comment]
You have to use scrolling functionality of `PDFView`, this is the main reason for existence of this library.

**Comment by bdariusb** [comment]
I see. In my case, I don't want to use scrolling, I only need to load the pdf to a view. Isn't that a genuine option for one?

**Comment by barteksc** [comment]
It is not possible to render whole document at once, because you will end with `OutOfMemoryError`. Scrolling mechanism renders visible parts of document and removes not visible from memory

**Comment by bdariusb** [comment]
what about loading a specified amount of pages at once? There would be a safe default value

**Comment by barteksc** [comment]
Only possibilty is to change `Constants.Cache.CACHE_SIZE`, but devices have different RAM sizes and it may work on one device but not on others

**Comment by yeshaohuayeshaohua** [comment]
It's a serious problem.

**Comment by bdariusb** [comment]
I actually tried to change the cache size, and yes, like barteksc said, sooner or later you run out of memory.

**Comment by barteksc** [comment]
You must use scrolling feature of this library, there is no other way
