### ISSUE TITLE
NEED HELP WITH MY FIRST APP.

### ISSUE THREAD

**Issue by rhonxz** [barteksc/AndroidPdfViewer#461]
i want to add button once i click it, i will load the pdf file from asset folder.

package com.example.administrator.mypdftrial03;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.github.barteksc.pdfviewer.PDFView;

public class MainActivity extends AppCompatActivity {
    PDFView pdfView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        pdfView = (PDFView)findViewById(R.id.pdfView);
        pdfView.fromAsset("try.pdf").load();

    }
}

**Comment by 1stmetro** [comment]
so where are you stuck ? with the button or a the pdfview ?

**Comment by rhonxz** [comment]
with button , i don't know what code to use that will view the pdf file/image in asset folder once button is clicked.

**Comment by 1stmetro** [comment]
if you look you will find how to create a button, just add the code to a button
