### ISSUE TITLE
not opening files in the raw directory

### ISSUE THREAD

**Issue by soyuznii** [barteksc/AndroidPdfViewer#467]
Uri myFile = Uri.parse("android.resource://"+getActivity().getPackageName()+"/raw/ssb_facility_letter_terms_raw.pdf");
            pdfView.fromUri(myFile);

 Uri myFile = Uri.parse("android.resource://"+getActivity().getPackageName()+"/raw/ssb_facility_letter_terms_raw");
            pdfView.fromUri(myFile);

neither is opening with or without the file extension

**Comment by barteksc** [comment]
Are you able to get file content without using AndroidPdfViewer?

**Comment by soyuznii** [comment]
it was in the wrong folder, the resource must be in the assets not the raw
directory
