### ISSUE TITLE
Pdf Text Encoding Option

### ISSUE THREAD

**Issue by okarakose** [barteksc/AndroidPdfViewer#472]
I have a problem with text encoding. Some characters ( which are Turkish language characters like İ, ş ) does not rendering properly.

## Actual PDF

![actual-pdf](https://user-images.githubusercontent.com/13510876/34041377-e004d11c-e1a8-11e7-80e3-66e6e5732dd1.png)

## PDFView Result

![encoding-problem](https://user-images.githubusercontent.com/13510876/34041294-828774a4-e1a8-11e7-8ef0-8d35dc79a8e7.png)

## Code

    PDFView pdfView = new PDFView(getContext(), null);
    pdfView.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
    pdfView.fromAsset("test.pdf").load();
    container().addView(pdfView);

Is there any option to set text encoding ?

**Comment by barteksc** [comment]
Do you have correct font embedded in document?

**Comment by okarakose** [comment]
I researched embedded fonts and result is below. ( Problem is solved )

### Command

    strings test.pdf | grep -i FontName

### Output

    /FontName /Arial-BoldMT
    /FontName /ArialMT

and then I opened this pdf with Preview app and used Export as Pdf menu option to export to test2.pdf.

### Command

    strings test2.pdf | grep -i FontName

### Output

    << /Type /FontDescriptor /FontName /ZANVRH+ArialMT /Flags 32 /FontBBox [-665 -325 2000 1006]
    << /Type /FontDescriptor /FontName /KEPTQR+ArialMT /Flags 4 /FontBBox [-665 -325 2000 1006]
    << /Type /FontDescriptor /FontName /GCOKAD+Arial-BoldMT /Flags 32 /FontBBox
    << /Type /FontDescriptor /FontName /VZTIIG+Arial-BoldMT /Flags 4 /FontBBox

Result was **different**. So, I used this test2.pdf file with this library and **it works like a charm !**

Just I have noticed another thing. When I zooming on pdf file, texts are blurring ( like a rendering from scratch ? ). Example video can be found below :

http://sendvid.com/r5f2trd2

Are there any way to fix this rendering flicks ?

**Comment by barteksc** [comment]
Document must be rendered with new level of zoom, there is no other way

**Comment by marcoBettiga** [comment]
Hi!
I can't see a signature (pdfSignature)  in the pdf, how can I solve it?

**Comment by barteksc** [comment]
@marcoBettiga
Your question is not related to this issue, you may create new

**Comment by malwinder-firminiq** [comment]
Does anyone knows how to fix this issue? I was getting invalid characters like:  İ, ş displayed on PDF viewer.
