### ISSUE TITLE
How to divide pages??

### ISSUE THREAD

**Issue by ManikumarGouni** [barteksc/AndroidPdfViewer#473]
When I am trying to using this library all are ok but All pages are linked each other.how to differentiate each with other??

**Comment by 1stmetro** [comment]
.pages is optional, it allows you to filter and order the pages of the PDF as you need

This will allow you to separate into single pages. Not ideal but will do what you want it  to.

**Comment by ManikumarGouni** [comment]
Thanks for replying...
Please find the attachment below..
And I am asking that how to split like in the image???

**Comment by 1stmetro** [comment]
No image attached...

**Comment by ManikumarGouni** [comment]
I am sorry... I replied to the mail from which I got ,with attachement..
Would you please help me through Gmail..
My mail Id is gmanikumar1998@gmail.com.

**Comment by 1stmetro** [comment]
You can attach files here.

**Comment by ManikumarGouni** [comment]
- 
![screenshot_2017-12-17-20-37-44_1](https://user-images.githubusercontent.com/26905169/34081986-4fe7ca0a-e37c-11e7-8893-76323370a471.jpg)

**Comment by 1stmetro** [comment]
Okay use  .spacing(0)

Change zero to how big you want the gap. 

It uses the background color to show as a gap, I just use my own code as I don't like the black flying in activity but this will do what you want.

**Comment by ManikumarGouni** [comment]
Thanks much...
