### ISSUE TITLE
How to verify password for encrypted pdf file?

### ISSUE THREAD

**Issue by dongliang0201** [barteksc/AndroidPdfViewer#474]
If this file is encrypted, how do you automatically pop a window to prompt the user to enter a password?
a dialog and callback.

**Comment by 1stmetro** [comment]
You add your own code to do this, as you said pop up a dialog and then reload the pdf with the password no callback in a sense.  Just reload the pdf.

**Comment by dongliang0201** [comment]
Hi, how do I detect this PDF file with a password？

**Comment by 1stmetro** [comment]
Simply catch the error then show your dialog box and reload pdfviewer with the new password inputted by the user.

**Comment by dongliang0201** [comment]
yeah, thanks a lot.

**Comment by 1stmetro** [comment]
If you were struggling... this will help..

.onError(new OnErrorListener() {
                                        @Override
                                        public void onError(Throwable t) {
                                            if (t instanceof PdfPasswordException) {
//add your code here
}

**Comment by dongliang0201** [comment]
thanks, I've done it like you did.
but the pdf file was parsed twice..

**Comment by barteksc** [comment]
Every PDF reader works that way

**Comment by dongliang0201** [comment]
Thanks @barteksc @1stmetro
