### ISSUE TITLE
3.0.0-beta.3 Hyperlinks not open

### ISSUE THREAD

**Issue by Jiten-Medic** [barteksc/AndroidPdfViewer#478]
Unable to open Hyperlinks within pdf:

I am using version 3.0.0-beta.3 and below is the code to load pdf-
pdfView.fromFile(new File(filePath))
.defaultPage(0)
.scrollHandle(new DefaultScrollHandle(this))
.pageFitPolicy(FitPolicy.BOTH)
.spacing(10)
.enableAnnotationRendering(true)
.linkHandler(new DefaultLinkHandler(pdfView))
.onError(this)
.load();

This the same code to load pdf as written in sample app too but its not working for hyperlinks.
Looking for the solution.

Thanks,

**Comment by barteksc** [comment]
Please don't duplicate issues, you just wrote that in #447
