### ISSUE TITLE
the jump to function do not work

### ISSUE THREAD

**Issue by hustyichi** [barteksc/AndroidPdfViewer#48]
Hi
    I try to use the jump to function, but it does not seem to work.
    Could someone help me?

Thank you

**Comment by hustyichi** [comment]
I find out the problem, the function works well.
getCurrentPage function get value start from 0, but the jumpTo function use  value start from 1, so if you want to jump to next page, use: pdfView.jumpTo( pdfView.getCurrentPage() + 2 )

**Comment by JulienRaad** [comment]
it jumps but the layout disappear until manual scroll, it reappears again. How can we solve this ?

**Comment by shineon84** [comment]
Same problem! For me the problem appears when setting defaultPage different than 0 in the constructor. The layout is blank, and it appears only after manual scroll.
