### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by Jiten-Medic** [barteksc/AndroidPdfViewer#480]
Hi

In release build with proguard active for our project, the PDFViewer fails to open the PDF files everytime trying to open the PDF file. Where as in dev builds it's opening the files.

Please look over the issue.

Thanks

**Comment by Jiten-Medic** [comment]
Please find the log on release build :

E/art: No implementation found for long com.shockwave.pdfium.c.a(int, java.lang.String) (tried Java_com_shockwave_pdfium_c_a and Java_com_shockwave_pdfium_c_a__ILjava_lang_String_2)

**Comment by Jiten-Medic** [comment]
Add following to the proguard which resolves my issue :

-keep class com.shockwave.**
-keepclassmembers class com.shockwave.** { *; }

**Comment by barteksc** [comment]
Thanks, I will add this info to README.
Isn't only first rule sufficient?

**Comment by Jiten-Medic** [comment]
I think ProGuard removes annotated EventBus subscriber methods and so events are fired but not consumed.
This rule fixes this issue.

**Comment by foxcode7** [comment]
thanks，very useful！

**Comment by jackgu1988** [comment]
> Add following to the proguard which resolves my issue :
> 
> -keep class com.shockwave.**
> -keepclassmembers class com.shockwave.** { *; }

Without the second rule I get an error while trying to access com.shockwave.pdfium.PdfPasswordException.

I think that it should be added to the README.

**Comment by decafmateen** [comment]
where we have to add that
