### ISSUE TITLE
PDFView shows garbage or blank screen

### ISSUE THREAD

**Issue by djnotes** [barteksc/AndroidPdfViewer#485]
I am creating a file object and pass it to PDFView using the following code:   
```
 try {
                URL url = new URL(urls[0]);
                HttpURLConnection conn = (HttpURLConnection) url.openConnection();
                conn.connect();

                if(conn.getResponseCode() != HttpURLConnection.HTTP_OK) {
                    return "Server returned HTTP " + conn.getResponseCode() + " "
                            + conn.getResponseMessage();
                }

                //Useful to display progress
                int fileLength = conn.getContentLength();


                //Download the file
                InputStream input = new BufferedInputStream(conn.getInputStream());
                File dir = new File(getFilesDir(), "/temp");
                dir.mkdir();
                file = new File(dir, "temp.pdf");
                OutputStream output = new FileOutputStream(file);

                byte[] data = new byte[1024];
                long total = 0;
                int count;
                while ((count = input.read(data)) != -1) {
                    if(isCancelled()) {
                        input.close();
                        return null;
                    }
                    total += count;

                  
                    output.write(data);

                }


                output.flush();
                output.close();
                input.close();
            } catch (IOException e) {
                Log.e(LOG_TAG, "IOException: " + e.getMessage());
            }
PDFView pdfView = findViewById(R.id.pdfView);
            pdfView.fromFile(file).load();

```
The resulting pdf view is blank or shows garbage characters for most pages (I am going to load mostly PDF files containing Persian and Arabic script). How can this be solved?

**Comment by 1stmetro** [comment]
Does the pdf open in another pdf app correctly ?

Is the path to internal or external drive correct in a file manager and also within your path as your path appears to be just temp, no drive as such sdcard, etc ?

File dir = new File(getFilesDir(), "/temp");

**Comment by jasonMisaq** [comment]
Yes, the pdf files open in other apps. No problem. Almost all of them fail to load in this code. 
Honestly, I have very little understanding of Android file system. Do you mean I need to have a directory named 'temp' in my Android emulator or device before running the code? I thought it creates one using the `new File()` statement.

**Comment by jasonMisaq** [comment]
I just realized that all PDFs load badly, even the Latin ones. It has nothing to do with Arabic and Persian script.

**Comment by jasonMisaq** [comment]
I also get the following error often:  

> 
 E/System: java.io.IOException: file not in PDF format or corrupted

**Comment by 1stmetro** [comment]
Post a sample pdf.

**Comment by jasonMisaq** [comment]
https://zoodbashcity.com/public/docs/1.pdf
https://zoodbashcity.com/public/docs/2.pdf
https://zoodbashcity.com/public/docs/3.pdf

**Comment by 1stmetro** [comment]
Here is an example image, i have no issues with the PDF's they all open and look ok.

I would suggest you look at the path within your app and compare with a file manager path, to me it appears you don't have the drive, internal, sdcard path correct but check by comparing the two.

Hope this helps. 

![test](https://user-images.githubusercontent.com/21983778/34325097-d197a13a-e87f-11e7-95da-e4d68dae9ccf.png)

**Comment by jasonMisaq** [comment]
Can you please provide some code for this? How do you generate bottom thumbnails?

**Comment by 1stmetro** [comment]
If you follow the read me it explains how to open pdf's which i think you know how to do.

In your /temp path you will need to add the path in front as it does not path the same as windows or linux may, get the path from your file manager to the pdf then statically add it to the temp path so it could be /storage/extSdCard/temp the pdf should then open without issues.

I just coded the bottom bar, just adding a blow up function so the page will enlarge and then the user can click to move to the page and close the bottom bar, its my new gadget. 

This function is also pdfviewer, but it does take some programming to get it to what you see, it already doesnt look like this as its been improved already.

**Comment by hellosad** [comment]
maybe,you didn't put PDFView in a RelativeLayout

**Comment by djnotes** [comment]
The problem was in my file processing code. The way I created the file was wrong. [This post](https://stackoverflow.com/a/576562/2009178 ) on SO explains the a small bug with Java. That fixed the issue.   When writing the an output file stream, using `fos.write(buffer, 0, count);` instead of `fos.write(buffer)` fixes the issue.

**Comment by malwinder-firminiq** [comment]
@djnotes I tried writing `fos.write(buffer, 0, count);` but still, it was showing invalid characters like  İ, ş.
Does anyone knows how to fix this issue?
