### ISSUE TITLE
How to change page in code?

### ISSUE THREAD

**Issue by jordan1997** [barteksc/AndroidPdfViewer#492]
I need to add seek bar below pdf viewer in my app. Can i change showed page by seekbar progrees?

**Comment by 1stmetro** [comment]
Yes I do this in a mini pdf view which is like a progess bar the screenshot images in recent posts which will show you what can be achieved with pdfview.

**Comment by jordan1997** [comment]
@1stmetro Thanks for help. I found `jumpTo` method.
