### ISSUE TITLE
Error inflating class com.github.barteksc.pdfviewer.ScrollBar

### ISSUE THREAD

**Issue by vikydev** [barteksc/AndroidPdfViewer#493]
getting Error inflating class com.github.barteksc.pdfviewer.ScrollBar
error while running app and app crashes. Please help am using 

com.github.barteksc:android-pdf-viewer:2.8.2

**Comment by barteksc** [comment]
There is no `ScrollBar` class in 2.8 version. Use library with corresponding documentation

**Comment by vikydev** [comment]
@barteksc  me also use lib project inculded as module but still getting same error.

my xml
<com.github.barteksc.pdfviewer.PDFView
        android:id="@+id/pdfView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="none"/>

android code

 pdfView.fromFile(targetFile_)
                .onLoad(PdfViewer.this)
                .defaultPage(1)
                .onPageChange(PdfViewer.this)
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .scrollHandle(new DefaultScrollHandle(this))
                .load();

used 

com.github.barteksc:android-pdf-viewer:2.8.2

in  project gradle.


buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }


please help me..  previously used  "joanzapata pdfview"  . trying to migrate to "barteksc pdfview".

dont know what is the issue.. pls help

**Comment by barteksc** [comment]
You are not using `ScrollBar` and getting error with `ScrollBar`?

**Comment by vikydev** [comment]
yes. Dont know why??

its shows log cat "Error inflating class com.github.barteksc.pdfviewer.ScrollBar " crashs in setContentView() line layout where my pdfview placed.

**Comment by barteksc** [comment]
You have errors in your project, rebuild and invalidate cache

**Comment by vikydev** [comment]
No errors in my project it running successfully.. crashs only if i take pdfview activity. ok let my try it and update you soon.

**Comment by yashp241195** [comment]
facing the same issue
