### ISSUE TITLE
Unable to scroll to next page when Pdf in zoom view 

### ISSUE THREAD

**Issue by dineshoffl** [barteksc/AndroidPdfViewer#497]
Unable to scroll to next page when Pdf in zoom view .help me please

**Comment by 1stmetro** [comment]
this is a little strange.... follow the sample it will work..

Otherwise post some code so we can see what the problem is.

**Comment by dineshoffl** [comment]
pdfView.fromFile(file)
                //.pages(0, 2, 1, 3, 3, 3) // all pages are displayed by default
                .enableSwipe(true)
                .defaultPage(0)

                .enableDoubletap(true)
                .swipeVertical(true)
                .defaultPage(1)
                .showMinimap(false)
//                .onDraw(onDrawListener)
//                .onLoad(onLoadCompleteListener)
                .onPageChange(this)
//                .onError(onErrorListener)
                .enableAnnotationRendering(false)
                .password(pass)
                .showPageWithAnimation(true)
                .load();

this is may code . am using 'com.github.barteksc:android-pdf-viewer:1.6.0'

**Comment by barteksc** [comment]
You are using 1.6.0 version, so corret reporitory for creating issues is ://github.com/barteksc/AndroidPdfViewerV1

You cannot change page while zooming, this by design
