### ISSUE TITLE
Start reading from last page

### ISSUE THREAD

**Issue by amanokerim** [barteksc/AndroidPdfViewer#498]
Hi!
How can I organize opening pdf file from last page.
Thank you.

**Comment by barteksc** [comment]
You can pass all pages in desired order to `.pages(...)`

**Comment by 1stmetro** [comment]
.pages(pdfView.getPageCount(),9,8,7,6,5,4,3,2,1) 

This will load the last page, but you will have to sequence the pages in reverse in the same way to show them all in reverse.

**Comment by amanokerim** [comment]
I am so sory for my bad English. I did not mean that.
Look, I am opening and reading some pdf. Then I close app when I was on for example 5th page. Next time when I am openign pdf it will start from first page. How it can be started from 5th page (last read).

**Comment by AhmerAfzal1** [comment]
@amanokerim email me at ahmerafzal@yahoo.com I'll help you

**Comment by barteksc** [comment]
@amanokerim You have to save current page number on configuration change in eg. `onSaveInstanceState()` and restore it in `onRestoreInstanceState()`

**Comment by amanokerim** [comment]
@barteksc How can I read page number.

**Comment by barteksc** [comment]
`pdfView.getCurrentPage()`

**Comment by amanokerim** [comment]
@barteksc I thied like this

    @Override
    public void onSaveInstanseState(){
        currentPage = pdfView.getCurrentPage();
        saveData("currentPage", currentPage); //save to shared preferences
    }

    @Override
    public void onRestoreInstanceState(){
        currentPage = loadData("currentPage"); // load from shared preferences
        pdfView.fromAsset("9alg.pdf").defaultPage(currentPage).load();
    }

Help me please?

**Comment by barteksc** [comment]
1. `onSaveInstanceState` and `onRestoreInstanceState` have `Bundle` parameters and you should use it for  saving state.
2. What is not working in your code?

**Comment by amanokerim** [comment]
Method is not override method from its superclass

**Comment by barteksc** [comment]
Read Android documentation, it is core Android concept

**Comment by amanokerim** [comment]
Thank you.

**Comment by kingdoom0** [comment]
I get the pdf files through an adapter
Can this way save the last page you read for each file?

**Comment by kingdoom0** [comment]
thats my view code

```
package com.zkingdoom.a2daret2lwaqt;

import android.os.Bundle;
import android.util.Log;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import com.github.barteksc.pdfviewer.PDFView;
import com.github.barteksc.pdfviewer.scroll.DefaultScrollHandle;
import com.github.barteksc.pdfviewer.util.FitPolicy;


import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class my_view extends AppCompatActivity {
    AdView mAdView ;
    private InterstitialAd mInterstitialAd;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.my_view);
        //PDF View
        PDFView pdfView = findViewById(R.id.general_v);
        pdfView.fromAsset(getIntent().getStringExtra("BOOK_PATH"))
                .enableSwipe(true) // allows to block changing pages using swipe
                .swipeHorizontal(false)
                .enableDoubletap(true)
                .defaultPage(0)
                .getCurrentPage()
                .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                .password(null)
                .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                // spacing between pages in dp. To define spacing color, set view background
                .spacing(0)
                .pageFitPolicy(FitPolicy.WIDTH)
                .scrollHandle(new DefaultScrollHandle(this,false))
                .load();





}
```

I Cant do it , please help me
