### ISSUE TITLE
Pages get stretched when viewing pdf-files with variable page width.

### ISSUE THREAD

**Issue by MPuhakka** [barteksc/AndroidPdfViewer#5]
I have a pdf file with mostly normal document pages but with a few large image-based pages. All the following pages seem to get stretched based on the width of the first page. 

Is there a way to mix horizontal and vertical pages without either of them getting stretched?

**Comment by barteksc** [comment]
Unfortunately it is not possible now, library assumes that all pages have equal dimensions. But I will take a look at this problem.

**Comment by MPuhakka** [comment]
Alright thanks for the reply. its kinda of a corner case feature but would be nice to have none the less.

**Comment by grilo341** [comment]
Any update on this?
