### ISSUE TITLE
Can not open PDF that has a PASSWORD protection

### ISSUE THREAD

**Issue by anbarasu-seven** [barteksc/AndroidPdfViewer#501]
I tried to open a document that is protected with password. It is showing empty screen. Also crashes on empty screen.

**Comment by 1stmetro** [comment]
You have to catch the password exception and of course use a password

**Comment by barteksc** [comment]
Closing due to no response from author

**Comment by connor-sleight** [comment]
@1stmetro how do we capture the exception? I dont seem to get any errors or exceptions thrown?

**Comment by AhmerAfzal1** [comment]
```
.onError(new OnErrorListener() {
                    @Override
                    public void onError(Throwable t) {
                        if (t instanceof PdfPasswordException) {
                            t.printStackTrace();
                            reloadPDFWithPassowrd();
                        }
                        Log.v(TAG, " onError while loading. " + t);
                    }
                })
}
```

**Comment by connor-sleight** [comment]
It would make way more sense to have a method we could use to check if there was a password on the pdf. Is there any chance we could get one added?

**Comment by connor-sleight** [comment]
@AhmerAfzal1 I'm trying to catch that error in a nativescript plugin, but it never gets thrown whether I pass in null or undefined into the password method

**Comment by AhmerAfzal1** [comment]
Email me

**Comment by anbarasu-seven** [comment]
It was the issue I faced in my previous company project. I do not have the
source code to reproduce the issue. But the scenario is I tried to open the
PDF file within the android activity. Try to reproduce with scenario if
possible.
