### ISSUE TITLE
Huawei trt-al00a loaded the network PDF error

### ISSUE THREAD

**Issue by zhiwo** [barteksc/AndroidPdfViewer#502]
java.io.FileNotFoundException: No content provider，知道为啥不

**Comment by barteksc** [comment]
Please write only in english and change title

**Comment by zhiwo** [comment]
Huawei trt-al00a loaded the network PDF error，Support online loading PDF？

**Comment by barteksc** [comment]
No, this library does not support downloading documents from internet.
