### ISSUE TITLE
why is rendering a single thread ?

### ISSUE THREAD

**Issue by BinarySatan** [barteksc/AndroidPdfViewer#504]
`mPdfView.fromFile(pdfFile)
                .defaultPage(PreUtils.getPrefInt(this, CACHE_SUFFIX + mId, 0))
                .enableDoubletap(true)
                .enableSwipe(true)\\
                .swipeHorizontal(true)
                .password(null)
                .scrollHandle(null)
                .enableAnnotationRendering(true)
                .enableAntialiasing(true)
                .spacing(ScreenUtils.dip2px(this, 5))
                .pageFitPolicy(FitPolicy.WIDTH)
                .onPageChange(this)
                }).load();`

AND 

    `private void getDisplayThumbnail(final float displayPage, final float totalPage) {
        _es.execute(new Runnable() {
            @Override
            public void run() {
                int model = (int) Math.ceil(totalPage / displayPage);
                mBitmaps.clear();
                for (int i = 0; i < totalPage; i++) {
                    if (i % 2 == 0) {
                        mBitmaps.add(getThumbnail(i));
                    } else if (i == totalPage - 1 && mBitmaps.size() == displayPage) {
                        mBitmaps.remove(mBitmaps.size() - 1);
                        mBitmaps.add(getThumbnail(i));
                    }
                }

                mH.sendEmptyMessage(0x10);
            }
        });

    }

    private Bitmap getThumbnail(int page) {
        Bitmap bitmap = Bitmap.createBitmap(mThumbnailWidth, mThumbnailHeight, Bitmap.Config.ARGB_4444);
        mPdfCore.openPage(mPdfDocument, page);
        mPdfCore.renderPageBitmap(mPdfDocument, bitmap, page, 0, 0, mThumbnailWidth, mThumbnailHeight);
        return bitmap;
    }

`

in PdfiumCore.java    
why do  nativeLoadPage  and  nativeRenderPageBitmap   use the same lock ?

**Comment by barteksc** [comment]
Pdfium library is single-threaded, so introducing new java thread would not help

**Comment by BinarySatan** [comment]
`      

 for (int i = 0; i < totalPage; i++) {         
if (destory) return;
                    if (i % 2 == 0) {
                        mBitmaps.add(getThumbnail(i));
                    } else if (i == totalPage - 1 && mBitmaps.size() == displayPage) {
                        mBitmaps.remove(mBitmaps.size() - 1);
                        mBitmaps.add(getThumbnail(i));
                    }
                }
    private Bitmap getThumbnail(int page) {
        Bitmap bitmap = Bitmap.createBitmap(mThumbnailWidth, mThumbnailHeight, Bitmap.Config.RGB_565);
        mPdfCore.openPage(mPdfDocument, page);
        mPdfCore.renderPageBitmap(mPdfDocument, bitmap, page, 0, 0, mThumbnailWidth, mThumbnailHeight);
        return bitmap;
    }
`

why i render the  16 bitmaps need take me  ~ 35second

Is there something wrong with my code?
