### ISSUE TITLE
Large apk size, how to fix that

### ISSUE THREAD

**Issue by sssvrock** [barteksc/AndroidPdfViewer#511]
Hi, I have gone through your document, like as it is using pdfium so that apk size is more. But any alternative to fix that.

I have generated signed apk, after extracting that there is a folder called 'lib' it is only taking 38 MB and all are ABI's in that method which are containing "libjniPdfium.so" file for the following folders.

arm64
armeabi
armeabi-v7a
mips
x86
x86_64

Any optimization to reduce apk size.
Thanks in advance for the help

**Comment by barteksc** [comment]
Only possibility is to use method from readme

**Comment by sssvrock** [comment]
Thanks for your quick reply, I have used multi apk link which is available in readme. It is helpful
