### ISSUE TITLE
How can i just package the armeabi's *.so lib?

### ISSUE THREAD

**Issue by cursorfei** [barteksc/AndroidPdfViewer#524]
Hello,thanks for provide this useful pdf lib.
when i assemble my apk,the apk's size is so big,it contains armeabi,arm64-v8a,armeabi-v7a,mips,x86 and x86_64 folders,but i just want to package armeabi floder into apk,what should i do?

**Comment by barteksc** [comment]
It was asked many times, please read readme

**Comment by Sanaebadi97** [comment]
https://github.com/barteksc/AndroidPdfViewer/issues/609#issuecomment-529188369
