### ISSUE TITLE
Oritention PDF 

### ISSUE THREAD

**Issue by hafiz013** [barteksc/AndroidPdfViewer#527]
hai, let say I on page 6 then when I do orientation to landscape the pdf go back to the first page. So how to make it stay on current page regardless i do orientation. thank you.

**Comment by hafiz013** [comment]
for orientation follow this 
   var pageNumber: Int = 0
   val KEY_CURRENT_PAGE = "current_page"
   val SAMPLE_FILE = "samplepdf.pdf"

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        if (savedInstanceState != null)
        {
            pageNumber = savedInstanceState.getInt(KEY_CURRENT_PAGE);
        }
        else
        {
            pageNumber = -1;
        }
       // display file pdf
       displayFromAsset(SAMPLE_FILE)
}
// restore current page
 override fun onRestoreInstanceState(savedInstanceState: Bundle) {
        super.onRestoreInstanceState(savedInstanceState)
        pageNumber = savedInstanceState.getInt(KEY_CURRENT_PAGE)
    }

//store current page
    public override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.putInt(KEY_CURRENT_PAGE, pageNumber)
    }

fun displayFromAsset(pdfFile:String):Unit {
        pdfView.fromAsset(SAMPLE_FILE)
                .defaultPage(pageNumber)  // it will default to current page
                .onPageChange(this@MainActivity)
                .enableAnnotationRendering(true)
                .onLoad(this@MainActivity)
                .scrollHandle(DefaultScrollHandle(this))
                .spacing(10) // in dp
                .onPageError(this@MainActivity)
                .pageFitPolicy(FitPolicy.WIDTH)    // if you want view full screen pdf for both orientation
                .load()
    }

**Comment by AhmerAfzal1** [comment]
Send an  email to me for further help at ahmerafzal@yahoo.com
