### ISSUE TITLE
PDF is not showing correct.

### ISSUE THREAD

**Issue by Yash463** [barteksc/AndroidPdfViewer#528]
https://d.smartcmobile.net/SanClemente/Attachments/pdf/lem_len_20170809_a_00000000010000000004.pdf

I have download the pdf from the above url and save into SD card and when i open it using PDF view it not showing as correct.

Please see below screen shot for reference 

![device-2018-02-05-113317](https://user-images.githubusercontent.com/25998568/35791208-9d12a252-0a6c-11e8-8d42-c48d221f64b5.png)

**Comment by 1stmetro** [comment]
Change the fit policy to height or both not width

**Comment by Yash463** [comment]
I don't understand what you mean. Could you please provide the updated code where i need to change. Your response would be highly appreciated.

**Comment by barteksc** [comment]
Which version of AndroidPdfViewer are you using?

**Comment by Yash463** [comment]
Latest one 2.8.2

**Comment by barteksc** [comment]
This version does not support different sized pages within document, you should use current beta version

**Comment by Yash463** [comment]
Thanks. It Works :+1:
