### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 13120241790** [barteksc/AndroidPdfViewer#530]
Hi~ Is support load Http Links add Header?  Thanks

**Comment by 1stmetro** [comment]
if you click a link it will open a browser if that is what you mean ?

**Comment by 13120241790** [comment]
Thanks reply~  
I mean, can I direct access to network resources(PDF)?
Example ：

```
pdfView.fromLinks("http://xxx.pdf")
            .addHeader("key","value")
           ... xxx ...
           .load();

```

**Comment by 13120241790** [comment]
@1stmetro

**Comment by 1stmetro** [comment]
possibly a link is a link it will go where you direct it, or you can override the action and build your own.

**Comment by barteksc** [comment]
@13120241790 there is no possibility to load remote PDFs

**Comment by 13120241790** [comment]
Thanks ~  @barteksc @1stmetro
