### ISSUE TITLE
how to change pages like viewpager

### ISSUE THREAD

**Issue by SAYEDALISINA93** [barteksc/AndroidPdfViewer#532]
Hi,
i am new to android and this library, Is it possible to change pages like viewpager???

**Comment by 1stmetro** [comment]
maybe explain what you are trying to do and someone maybe able to assist you.

**Comment by 1stmetro** [comment]
you could do page by page, but animation you would have to write

**Comment by SAYEDALISINA93** [comment]
good any hint how to do it page by page???

**Comment by 1stmetro** [comment]
Disable the view the use a next or previous button to load new page or scroll to a page

**Comment by 1stmetro** [comment]
Sorry this phone missed a couple of N's

**Comment by steven-gao** [comment]
@1stmetro can i scroll the pdfview like viewpager?
