### ISSUE TITLE
How can I show last opened page?

### ISSUE THREAD

**Issue by Yafroman** [barteksc/AndroidPdfViewer#533]
Hi!
How can I make the activity start from the last opened page
Thank you.

**Comment by 1stmetro** [comment]
store the pdf path and compare to the selected pdf if its the same use the stored page number, simple enough to implement.

**Comment by Yafroman** [comment]
when i close the app it will start from first pdf  page 
i need to get last readed page

**Comment by barteksc** [comment]
Store current page number in eg. `SharedPreferences` and restore it in `Activity#onCreate()` using `.defaultPage(int)` method when configuring PDFView.

**Comment by Yafroman** [comment]
So how can i store it and restore it 

onSaveInstanseState() & onRestoreInstanceState()

**Comment by barteksc** [comment]
This is core Activity lifecycle concept, you can read about it in Android docs

**Comment by Yafroman** [comment]
okay thank you
