### ISSUE TITLE
Hello, I would like to collaborate on your project as a translator to Spanish which is my native language

### ISSUE THREAD

**Issue by LuigiBaute** [barteksc/AndroidPdfViewer#534]

**Comment by 1stmetro** [comment]
How would that work ?

**Comment by LuigiBaute** [comment]
My intention is to translate the doc to spanish so it gets the atention of spanish speaking people, I'll make a new file of the translation and you'll merge the doc if you're happy with the results. let me know if you're interested. cheers!

**Comment by LuigiBaute** [comment]
@1stmetro
