### ISSUE TITLE
2.8.1 No implementation found for native nativeOpenDocument

### ISSUE THREAD

**Issue by velis74** [barteksc/AndroidPdfViewer#538]
Please forgive not using latest version, but I have some 600 deployments out there using 2.8.1.

My problem is that some of them are not displaying the documents and some of them work fine. All are running the same version of the software. All are Android 4.2 tablets.

So, using this code:

```
      final PDFView v = (PDFView) mainView.findViewById(R.id.pdf_layout);
      v.fromFile(new File(Documents.currentDoc)).onRender(new OnRenderListener() {
        @Override
        public void onInitiallyRendered(int nbPages, float pageWidth, float pageHeight)
        {
          v.fitToWidth();
        }
      }).load();
```

Displaying the SAME PDF works fine on one tablet and not at all on another. Here's what logcat says (for the non-working ones):

```
10:24:30.476 3859  4082                 dalvikvm W No implementation found for native Lcom/shockwave/pdfium/PdfiumCore;.nativeOpenDocument:(ILja
                                         va/lang/String;)J
10:24:30.486 3859  3859                  PDFView E load pdf error
10:24:30.486 3859  3859                  PDFView E java.lang.UnsatisfiedLinkError: Native method not found: com.shockwave.pdfium.PdfiumCore.nati
                                         veOpenDocument:(ILjava/lang/String;)J
10:24:30.486 3859  3859                  PDFView E at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
10:24:30.486 3859  3859                  PDFView E at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:113)
10:24:30.486 3859  3859                  PDFView E at com.github.barteksc.pdfviewer.source.FileSource.createDocument(FileSource.java:38)
10:24:30.486 3859  3859                  PDFView E at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)<
                                         /span>
10:24:30.486 3859  3859                  PDFView E at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)<
                                         /span>
10:24:30.486 3859  3859                  PDFView E at android.os.AsyncTask$2.call(AsyncTask.java:287)
10:24:30.486 3859  3859                  PDFView E at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10:24:30.486 3859  3859                  PDFView E at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10:24:30.486 3859  3859                  PDFView E at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10:24:30.486 3859  3859                  PDFView E at java.lang.Thread.run(Thread.java:856)
```

Any hints as to what might be wrong here?
It's not a problem moving to a newer version if this is a known issue, but I'd sure like to know what's going on too, if at all possible.

**Comment by 1stmetro** [comment]
looks like invalid pdf possibly hard to tell from that...

**Comment by velis74** [comment]
Not an invalid pdf if some tablets show it and some don't....

**Comment by velis74** [comment]
Sorry, I'm not following: how do I answer my own question when I'm running the same version of software on the same hardware and the same document opens on some tablets while it doesn't on others? The only possible alteration among the tablets being a slightly modified ROM build to compensate for minor hardware changes.

**Comment by velis74** [comment]
Further on-site testing that the difference between a non-working and a working tablet can be a single reboot.

The tablet does not show documents
reboot it
it now shows the documents
after some time, it no longer shows documents (even though nobody touched it in the mean time)

**Comment by zhouzhijiang** [comment]
i have same problem when i push my app to system/app directory,but no in system/app directory is work

**Comment by asi2012asi** [comment]
回楼上：
系统app应该会从system/lib/ 目录下查找so库 我遇到同样的问题 解决方案是：
1. 将xxx.apk改为 xxx.zip 
2. 解压zip
3. 在lib目录下找到那4个so库
4. copy 到system/lib目录下
5. reboot

**Comment by velis74** [comment]
We have found that the actual issue was chromium (crosswalk project) was preloading these libraries in a strange way. Then when the REAL java code was trying to load them, the loading failed, resulting in this error message.

We are currently solving this by loading the required libraries before loading chromium, however: finding a spot where that actually takes place is hard. For us we were lucky that one of our existing libraries ALWAYS loaded before chromium and we just added the appropriate loadLibrary( ) calls into that one. But we found no "recipe" as to where one should actually place the loadLibrary calls. Quite frustrating, I know, but try experimenting both with package names ans well as .java file names.

**Comment by Fight-Together-2019** [comment]
replace "com.github.barteksc:android-pdf-viewer:3.2.0-beta.1" with "com.github.barteksc:android-pdf-viewer:2.8.2", then restore to "com.github.barteksc:android-pdf-viewer:3.2.0-beta.1", issue fixed

**Comment by Egemen-Arslandogan** [comment]
> replace "com.github.barteksc:android-pdf-viewer:3.2.0-beta.1" with "com.github.barteksc:android-pdf-viewer:2.8.2", then restore to "com.github.barteksc:android-pdf-viewer:3.2.0-beta.1", issue fixed

it works. Thanks...

**Comment by XCarbone** [comment]
> i have same problem when i push my app to system/app directory,but no in system/app directory is work

what do you mean ? i got the probleme and i can't solve it

**Comment by 3bugs** [comment]
If you are using ProGuard, add following rule to proguard config file:

-keep class com.shockwave.** { *; }

**Comment by herrychenwj** [comment]
> If you are using ProGuard, add following rule to proguard config file:
> 
> -keep class com.shockwave.** { *; }
> 
> then clean & rebuild project.

thanks very much,help me a lot,you are so great
