### ISSUE TITLE
Error:Unable to resolve dependency

### ISSUE THREAD

**Issue by abunayem** [barteksc/AndroidPdfViewer#543]
Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.

Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
Required by:
    project :app 
No cached version of com.github.barteksc:android-pdf-viewer:2.8.2 available for offline mode.

**Comment by mnaji5544** [comment]
so I'm I this is my problem why
