### ISSUE TITLE
Apk size

### ISSUE THREAD

**Issue by benju69** [barteksc/AndroidPdfViewer#546]
This lib is +25 Mb :/ any way to optimize this ?

**Comment by mak12** [comment]
> This lib is +25 Mb :/ any way to optimize this ?

any luck?

**Comment by Karuhanga** [comment]
There is a link to a guide at the bottom of the README.
This though, should not be a concern with the newly introduced app bundle which helps you automatically build highly optimised apks.(https://developer.android.com/platform/technology/app-bundle/). I included this library in my project and still managed to achieve download sizes of ~11mb even without minifying my code.

-----Original Message-----

**Comment by mak12** [comment]
> There is a link to a guide at the bottom of the README. This though, should not be a concern with the newly introduced app bundle which helps you automatically build highly optimised apks.(https://developer.android.com/platform/technology/app-bundle/). I included this library in my project and still managed to achieve download sizes of ~11mb even without minifying my code.
> […](#)
> -----Original Message----- From: "Malik Abdul Kawee" <notifications@github.com> Sent: ‎01/‎01/‎2019 08:40 To: "barteksc/AndroidPdfViewer" <AndroidPdfViewer@noreply.github.com> Cc: "Subscribed" <subscribed@noreply.github.com> Subject: Re: [barteksc/AndroidPdfViewer] Apk size (#546) This lib is +25 Mb :/ any way to optimize this ? any luck? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Yeah got it already, checked readme and many many thanks for your response :) 👍
