### ISSUE TITLE
Get bitmap of the pages

### ISSUE THREAD

**Issue by asanz8** [barteksc/AndroidPdfViewer#547]
There is a way to get the bitmap of a page?

I have used this code:

`Bitmap bitmap = pdfView.getDrawingCache();`

But, the resolution is not the same, I need the generated bitmap of a page.

**Comment by 1stmetro** [comment]
Your on the right track!

Turn the view into a bitmap

**Comment by asanz8** [comment]
Hi! I found another solution for this, using **PdfiumCore**
PdfiumCore is included in AndroidPdfViewer

Here is the code:
```java
PdfiumCore pdfiumCore = new PdfiumCore(getContext());
int pageNum = your_page_num;

try{
com.shockwave.pdfium.PdfDocument pdf = pdfiumCore.newDocument(
    ParcelFileDescriptor.open(your_pdf_file, ParcelFileDescriptor.MODE_READ_WRITE)
);

                        pdfiumCore.openPage(pdf, pageNum);

                        int width = pdfiumCore.getPageWidth(pdf, pageNum);
                        int height = pdfiumCore.getPageHeight(pdf, pageNum);

                        Bitmap cbitmap = Bitmap.createBitmap(width, height, Bitmap.Config.RGB_565);
                        pdfiumCore.renderPageBitmap(pdf, cbitmap, your_page_num, 0, 0, width, height);

                        pdfiumCore.closeDocument(pdf);

                        new File(Environment.getExternalStorageDirectory()+"/PDF Reader").mkdirs();
                        File outputFile = new File(Environment.getExternalStorageDirectory()+"/PDF Reader", "temp_img.jpg");
                        FileOutputStream outputStream = new FileOutputStream(outputFile);

                        cbitmap.compress(Bitmap.CompressFormat.JPEG, 80, outputStream);
                        outputStream.close();

                    } catch(IOException ex) {
                        ex.printStackTrace();
                    }
```

Look for the folder _PDF Reader_ and there will be the image, this image has a better resolution than turn the view into a bitmap.

I hope it helps

**Comment by 1stmetro** [comment]
I will have to compare images as I generate a lot of thumbnails but I use png due to compression of jpg on small images.

**Comment by 1stmetro** [comment]
One question does your code generate the image after a complete render of the page so the image doesn't have darker and lighter parts to the image?

**Comment by asanz8** [comment]
@1stmetro Mmmm.... No

**Comment by songxiaoliang** [comment]
@asanz8 How to get  pageNum  ？

**Comment by 1stmetro** [comment]
Of the top Of my head pdfview.getCurrentPage ();

**Comment by shihabmi7** [comment]
I opened a pdf from assets. Now, I can't get the 'file' instance of this asset file. So, can;t pass it to below **ParcelFileDescriptor** method. 

`ParcelFileDescriptor.open(your_pdf_file, ParcelFileDescriptor.MODE_READ_WRITE) `

**Comment by manasid03** [comment]
> I opened a pdf from assets. Now, I can't get the 'file' instance of this asset file. So, can;t pass it to below **ParcelFileDescriptor** method.
> 
> `ParcelFileDescriptor.open(your_pdf_file, ParcelFileDescriptor.MODE_READ_WRITE) `

You can do this - 


PdfDocument pdf = pdfiumCore.newDocument(
                    ParcelFileDescriptor.open(FileUtils.fileFromAsset(getApplicationContext(), "filename.pdf"), ParcelFileDescriptor.MODE_READ_WRITE));

**Comment by albert0m** [comment]
> Hi! I found another solution for this, using **PdfiumCore** PdfiumCore is included in AndroidPdfViewer
> 
> Here is the code:
> 
> ```java
> PdfiumCore pdfiumCore = new PdfiumCore(getContext());
> int pageNum = your_page_num;
> 
> try{
> com.shockwave.pdfium.PdfDocument pdf = pdfiumCore.newDocument(
>     ParcelFileDescriptor.open(your_pdf_file, ParcelFileDescriptor.MODE_READ_WRITE)
> );
> 
>                         pdfiumCore.openPage(pdf, pageNum);
> 
>                         int width = pdfiumCore.getPageWidth(pdf, pageNum);
>                         int height = pdfiumCore.getPageHeight(pdf, pageNum);
> 
>                         Bitmap cbitmap = Bitmap.createBitmap(width, height, Bitmap.Config.RGB_565);
>                         pdfiumCore.renderPageBitmap(pdf, cbitmap, your_page_num, 0, 0, width, height);
> 
>                         pdfiumCore.closeDocument(pdf);
> 
>                         new File(Environment.getExternalStorageDirectory()+"/PDF Reader").mkdirs();
>                         File outputFile = new File(Environment.getExternalStorageDirectory()+"/PDF Reader", "temp_img.jpg");
>                         FileOutputStream outputStream = new FileOutputStream(outputFile);
> 
>                         cbitmap.compress(Bitmap.CompressFormat.JPEG, 80, outputStream);
>                         outputStream.close();
> 
>                     } catch(IOException ex) {
>                         ex.printStackTrace();
>                     }
> ```
> 
> Look for the folder _PDF Reader_ and there will be the image, this image has a better resolution than turn the view into a bitmap.
> 
> I hope it helps

how did you optimise this in an adapter? If I call the `pdfiumCore.openPage(pdf, currentPage); `for each item, eventually the app will run out of memory...

**Comment by VishalGopalrao** [comment]
> Your on the right track!
> 
> Turn the view into a bitmap
@1stmetro @Miha-x64 
barteksc library instance not clearing its instance, memory keeps on increasing while scrolling pdf in viewpager adapter
