### ISSUE TITLE
how could i preview pdf like viewpager?

### ISSUE THREAD

**Issue by steven-gao** [barteksc/AndroidPdfViewer#564]
hello ,I overide the  onPageScrolled() method,but it fail.
Anyone who can help me?

**Comment by 1stmetro** [comment]
Are you trying to do something like i have done in my picture ?

![bartek](https://user-images.githubusercontent.com/21983778/38170748-e82f8550-3584-11e8-8382-7182c21cd07f.png)

**Comment by Flamedek** [comment]
Are you looking for the kind of page flinging behaviour as in pull request #557?
If so you can clone that branch, see if it works for you and let us know.

**Comment by steven-gao** [comment]
@1stmetro good job,could you give me the demo code?

**Comment by steven-gao** [comment]
@Flamedek thank you , Besides the Viewpager above, I need a all page thumnail indicator below the viewpager.

**Comment by 1stmetro** [comment]
I did the thumbnails also, to copy what i have shown is to produce two pdfviewers on one page, the smaller one you can click to naviate to the page within the larger page, the smaller page will then slide down.

Its not code i can post as it would be too much, but its not difficult to replicate.

**Comment by steven-gao** [comment]
@1stmetro cool, thank you so much for everyone

**Comment by saikat1529** [comment]
@1stmetro really nice work. I was looking for that snippet since I started working with this library. Can you please share the code for bottom pdf viewpager?
