### ISSUE TITLE
Is it possible to draw an image drawn on the pdf view? - Question

### ISSUE THREAD

**Issue by hearbeathorror** [barteksc/AndroidPdfViewer#57]
Hi

i am trying to render an imageview ontop of the pdfview,,and then saving both together as merged, into a pdf document, but it doesnt seem to work. I wanted to know if there is a way i can allow a user to draw on a page, and then save the pdf. Please assist. It is a little urgent, all help will be appreciated.

Thanks

**Comment by barteksc** [comment]
You can use OnDrawListener to draw on pdf, but there is not possibility of saving edited documents.

**Comment by hearbeathorror** [comment]
is there a way i could save that ? may be by writing some code or something ?
