### ISSUE TITLE
Cant load pdf files with spaces in file name

### ISSUE THREAD

**Issue by cking24343** [barteksc/AndroidPdfViewer#573]
I ran into an issue recently with a user who was unable to load a pdf in the viewer. After some digging around I found that the issue was due to the pdf file having spaces in the file name. Apparently when passing the file location to load into the viewer it seems to fail. However if i update the pdf name and either replace the 'spaces' with '_' or edit to make it camel case, it works. Thoughts on a more permanate solution? I will I need to write code that does a cleanup of the file name prior to passing said file path to the viewer?

**Comment by 1stmetro** [comment]
Not found an issue with spaces in the names but had previous issues with PDF extensions and not pdf...

**Comment by cking24343** [comment]
Either way my workaround was to rename the file when saving and replacing spaces with '_' character, working now, thanks.
