### ISSUE TITLE
New version gradle Error

### ISSUE THREAD

**Issue by story9076** [barteksc/AndroidPdfViewer#576]
Hi. I use it well the new Version.
But It has a problem.
Whole Project Download and Run is Okay With new function like autoSpacing, pageFliping ...
But In Gradle script dependency, it's not has new function.
So i saw the git, graddle written like 'Fix issue with Configurator#pages() from #486'.
but actually The newest version is #557. 
So i think gadle update has wrong. please fix it.

**Comment by Flamedek** [comment]
The new features were merged into the project but not released on maven at the time.  
It has since been released as **3.1.0-beta.1** so this can be closed.
