### ISSUE TITLE
Search Text Inside PDF

### ISSUE THREAD

**Issue by nusagates** [barteksc/AndroidPdfViewer#593]
Hi, could we search text inside pdf?

**Comment by 1stmetro** [comment]
the code has not been wrote yet, but feel free to submit any development you can add to doing this.

**Comment by Sumit-Chakole** [comment]
Ya search text feature is needed to me too

**Comment by liupeng826** [comment]
me to, is it easy? seems it's a common function

**Comment by dvMadMan** [comment]
i need this too. please add this feature or help how we can do it. thanks

**Comment by ghost1372** [comment]
@dvMadMan  i found a better way to render pdf files on android with auto search ability if you want to know tell me know

**Comment by AhmerAfzal1** [comment]
@ghost1372 How?

**Comment by ghost1372** [comment]
@AhmerAfzal1 you must use javascript library just download and copy pdfjs lib in your assets folder then put a webview in your activity in last step show your pdf like this:
```
  webview = (WebView) findViewById(R.id.webview);
            WebSettings settings = webview.getSettings();
            settings.setJavaScriptEnabled(true);
            settings.setAllowFileAccessFromFileURLs(true);
            settings.setAllowUniversalAccessFromFileURLs(true);
            settings.setBuiltInZoomControls(true);
            webview.setWebChromeClient(new WebChromeClient());
            webview.loadUrl("file:///android_asset/pdfjs/web/viewer.html?file=" + pdfPath);
```
note: library must be this folder like this:<br>
-Assets
            -----pdfjs
                    -------build
                              ------ ...
                    -------web
                              ------ ...


[](https://github.com/mozilla/pdfjs-dist)

**Comment by dvMadMan** [comment]
maybe i'm stupid, but not work for me. just grey screen with navigation button.
last line:
webview.loadUrl("file:///android_asset/pdfjs/web/viewer.html?file=" + file:///android_asset/test.pdf);

**Comment by dvMadMan** [comment]
@ghost1372 this way is very slow for my phone.
this AndroidPdfViewer better, but need search ))))

**Comment by ghost1372** [comment]
@dvMadMan  yes because use webview and js, so its slow, but it has automatic search functionality And the much smaller size of this library.

**Comment by ghost1372** [comment]
@AhmerAfzal1  @dvMadMan  @liupeng826  @nusagates  @1stmetro  @Sumit-Chakole  i found a solution for this check this repo https://github.com/foobnix/LibreraReader it can read and search pdf files with MuPDF lib maybe @barteksc  can analysis this repo and add this

**Comment by barteksc** [comment]
Opensource version od MuPDF od licensed under AGPL license, which requires you to publish source code of your app

**Comment by ghost1372** [comment]
@barteksc  i dont have problem with this all of my works is free and open source

**Comment by BharathPujariMize** [comment]
@barteksc , is there any chance of getting search feature in Pdfviewer library?

**Comment by Taron133** [comment]
https://github.com/thevikke/read_pdf_text/blob/master/android/src/main/java/com/example/read_pdf_text/ReadPdfTextPlugin.java

**Comment by vimalcvs** [comment]
> @ghost1372 How?

This app is all ready done anyone can use reverse engineering.

https://play.google.com/store/apps/details?id=pdf.reader.pdfviewer.pdfeditor

**Comment by odmfl** [comment]
pdfium should have this function, the problem is to implement it for android.  I remember the old app "google pdf viewer" which however was based on pdfium and had this function

I did some research and found some libraries that have implemented the search, but I don't know if they work, they should be tested.
It would take someone to test them and maybe fork and keep an updated fork.

Test them and let me know if they work in any way

https://github.com/gulshan98185/AndroidPdfViewer

https://github.com/beeline09/AdvancedPdfView

https://github.com/beeline09/android-support-pdfium

https://github.com/benjinus/android-support-pdfium
