### ISSUE TITLE
add image to any page

### ISSUE THREAD

**Issue by yinhe-zeng** [barteksc/AndroidPdfViewer#625]
how to add images to  current page, and when the page scroll , the image scroll too. it looks like the image  is the part of the page.

**Comment by Flamedek** [comment]
Have you tried the `onDraw` and `onDrawAll` listeners?

**Comment by yinhe-zeng** [comment]
when I click a button, I want to add  an image into the page. By this way, can I use the onDraw listener?

**Comment by Flamedek** [comment]
Sure, you just have to program around it a little bit

``` java
boolean shouldDrawImage = false;

// set state on button click
view.setOnClickListener {
    shouldDrawImage = true;
    pdfView.invalidate();
}

// check state before drawing
public void onLayerDrawn(Canvas canvas, float pageWidth, float pageHeight, int displayedPage) {
    if (shouldDrawImage) {
        // do drawing
    }
}
```

Instead of a boolean you could also keep e.g. a list of images and positions to draw

**Comment by yinhe-zeng** [comment]
Thank you so much!  It works!

**Comment by reynoldyehezkiel** [comment]
can you tell me how to add image to pdfview?

**Comment by AasthaDoshi** [comment]
> Thank you so much! It works!

Hi @yinhe-zeng, I too wanted to know this. Can you suggest anything as of now it's not working for me.
