### ISSUE TITLE
Question - is there any page indicator?

### ISSUE THREAD

**Issue by IevgenGoltsev** [barteksc/AndroidPdfViewer#630]
Hello, first of all thanks for this beautiful library!!
I remembered in one of previous versions, there was some kind of page indicator while scrolling pdf.

Is there something like this now?

**Comment by Flamedek** [comment]
There is a scrollhandle which shows page number and allows scrolling.  
Call `.scrollHandle(new DefaultScrollHandle(this))` on the configurator.  
You could also implement your own ScrollHandle.

**Comment by IevgenGoltsev** [comment]
Thanks a lot, @Flamedek !!
