### ISSUE TITLE
add ImageView to PDFView

### ISSUE THREAD

**Issue by yinhe-zeng** [barteksc/AndroidPdfViewer#646]
I want to add imageViews into  the page, and the imageView can be touched, moved. 
 when the page scrolls, the imageView scrolls. when the page zooming, 
the imageview zooming.how can i do this?
    I  use PDFView.add(View view）to add an moving imageview, 
but the imageview's getLeft()、getTop()、getRight()、getBottom all return 0。
I don't know why...

**Comment by nbansal1** [comment]
Hi @yinhe-zeng I am looking for the same solution if you get the solution could you please let me know how you have done it.
Thanks in advance
