### ISSUE TITLE
Load pdf file failed with version 3.1.0-beta.1

### ISSUE THREAD

**Issue by chengww5217** [barteksc/AndroidPdfViewer#654]
When I update to 3.1.0-beta.1 from 3.0.0-beta.5, I cannot open pdf file.
And `OnErrorListener` called:

```
java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
```

**Comment by Krystal1220** [comment]
i get this crash too ,how to fix it??

**Comment by chengww5217** [comment]
Rollback the version to 3.0.0-beta.5

**Comment by Krystal1220** [comment]
tks ,find you   local library pdfium-android-1.9.0.arr,copy armeabi-v7a dir and rename to armeabi,you can have a try,also thank you

**Comment by zzzykf** [comment]
@chengww5217  have you fixed the issue? I'm facing the same issue

**Comment by chengww5217** [comment]
I've tried again. It works!!!  Wow, \(≧▽≦)/ amazing. 

There is a little bit different. I got the `.so` files from the local disk already downloaded by gradle.

@zzzykf
You can get the local path from the `Project` tree in the window left from the Android Studio.
Then open the `External Libraries` card.

![WX20181017-180827.png](https://upload-images.jianshu.io/upload_images/4971025-d93c821f8a3f9bcf.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

 Right click on `Gradle: com.github.barteksc:pdfium-android-1.9.0` , and choose `Library Properties`. That is the local path of the `.aar` file.

![WX20181017-180907.png](https://upload-images.jianshu.io/upload_images/4971025-b9f0f789d43e61f5.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![WX20181017-180920.png](https://upload-images.jianshu.io/upload_images/4971025-3d2c87591c89d17e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

> Thank you for your advice.
> 
> Unfortunately, it doesn't work. I download [the .arr file here](https://github.com/barteksc/PdfiumAndroid/releases). And unzip it, copy the .so files in folder
> armeabi-v7a to the armeabi folder whose parent is jniLibs of my project.
> 
> Run on Mi 6(armeabi device), not display, same exception occurd.
> 
> Maybe I should take some time to read the origin codes to fix it myself.

**Comment by imxy** [comment]
@chengww5217 谢啦，不过要注意是 复制aar文件下面的jni文件夹下面的armeabi文件夹，外面的文件夹不行。。。
and thanks @Krystal1220

**Comment by bawanglb123** [comment]
> @chengww5217 谢啦，不过要注意是 复制aar文件下面的jni文件夹下面的armeabi文件夹，外面的文件夹不行。。。 and thanks @Krystal1220

为什么是这个原因？改了下这样确实好了
