### ISSUE TITLE
Apk size increase 15MB 

### ISSUE THREAD

**Issue by tvhieuit** [barteksc/AndroidPdfViewer#664]
when I implement this library to read pdf, I see my apk size increase 15mb.
How to improve :(

**Comment by wsl007** [comment]
ndk {
                abiFilters "armeabi"
//                , "armeabi-v7a", "x86", "mips"
            }

**Comment by tvhieuit** [comment]
@wsl007 thank you for your support

**Comment by AamirNaseer1** [comment]
> ndk {
> abiFilters "armeabi"
> // , "armeabi-v7a", "x86", "mips"
> }
> ![1](https://user-images.githubusercontent.com/24606436/44777866-35331700-abae-11e8-960d-5b953c36a31a.png)

which architectures are useful and which are not ?
