### ISSUE TITLE
This library can not load the network PDF file,why?

### ISSUE THREAD

**Issue by scrylove** [barteksc/AndroidPdfViewer#67]
This library can not load the network PDF file,why?  how can i do?

**Comment by barteksc** [comment]
Library does not support remote files, you have to download it by yourself.

**Comment by scrylove** [comment]
Well, I've already solved this problem, thank you very much.

**Comment by supportreq** [comment]
@scrylove how did you solve this? how do I use PDF from a URL??

**Comment by barteksc** [comment]
@scrylove You have to download it by yourselve

**Comment by titosobabas** [comment]
That's why possibly hibrid apps with ionic are much better thank native development
