### ISSUE TITLE
Not able to load pdf from URI

### ISSUE THREAD

**Issue by shaanvipul** [barteksc/AndroidPdfViewer#672]
Hi Friend it great work really appreciate for your work, coming to me i am new with android and i have store my all pdf to google drive with password buy not able to load pdf from uri try many way please help me in this case.Thanks in Advance.
Error:- 08-30 12:22:20.075 8750-8750/com.sample.sample E/PDFView: load pdf error
    java.io.FileNotFoundException: No content provider: https://drive.google.com/file/d/1Ah2DPX9xrrBh2DPUfVIzSEya7u-oqipJ/view?usp=sharing

**Comment by shaanvipul** [comment]
Passing PDF from URI.

new RetrivePDFStream().execute(filePath);

class RetrivePDFStream extends AsyncTask<String, Void, InputStream> {
        @Override
        protected InputStream doInBackground(String... strings) {
            InputStream inputStream = null;
            try {
                URL uri = new URL(strings[0]);
                HttpURLConnection urlConnection = (HttpURLConnection) uri.openConnection();
                if (urlConnection.getResponseCode() == 200) {
                   inputStream = new BufferedInputStream(urlConnection.getInputStream());
              }
            } catch (IOException e) {
                return null;
            }
            return inputStream;
        }
        @Override
        protected void onPostExecute(InputStream inputStream) {
pdfView.fromStream(inputStream).password("Your Password").load();
            //progressBar.setVisibility(View.GONE);
        }
    }

**Comment by GuneetGupta** [comment]
package com.example.noteseasy1;
import android.os.AsyncTask;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;
import android.widget.Toast;

import com.github.barteksc.pdfviewer.PDFView;
import com.google.common.base.Strings;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;

public class mathsoneact extends AppCompatActivity {
    private PDFView pdfview;
    private TextView text1;
    private FirebaseDatabase database = FirebaseDatabase.getInstance();
    DatabaseReference mref = database.getReference("url");

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        pdfview = (PDFView) findViewById(R.id.pdfview1);
        text1 = (TextView) findViewById(R.id.text1);
        mref.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                String value = dataSnapshot.getValue(String.class);
                text1.setText(value);
                Toast.makeText(mathsoneact.this, "Updated", Toast.LENGTH_SHORT).show();
                String url = text1.getText().toString();
                new RetrivePdfStream().execute(url);
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {
                Toast.makeText(mathsoneact.this, "Failed to load", Toast.LENGTH_SHORT).show();

            }
        });
        class RetrivePdfStream extends AsyncTask<String, Void, InputStream> {

            @Override
            protected InputStream doInBackground(String... strings) {
                InputStream inputStream = null;
                try {
                    URL uri = new URL(strings[0]);
                    HttpURLConnection urlConnection = (HttpURLConnection) uri.openConnection();
                    if (urlConnection.getResponseCode() == 200) {
                        inputStream = new BufferedInputStream(urlConnection.getInputStream());
                    }
                } catch (IOException e) {
                    return null;
                }
                return inputStream;
            }

            @Override
            protected void onPostExecute(InputStream inputStream) {
                super.onPostExecute(inputStream);
                pdfview.fromStream(inputStream).load();
            }
        }
    }
}

**Comment by GuneetGupta** [comment]
i used the same code but i am getting error

**Comment by gabriel-TheCode** [comment]
Please what was your error ?

**Comment by shilp121** [comment]
new RetrivePdfStream().execute(**url**);
in this line i am getting error in Specific _url_ field

**Comment by Krishnakumar59** [comment]
using same code but still get errors @GuneetGupta @shaanvipul 

![Screenshot 2021-06-09 203419](https://user-images.githubusercontent.com/63739266/121377766-57af0d00-c962-11eb-8ca2-8d5ec6950f1f.png)

**Comment by hienncb** [comment]
why I can't click the link from pdf.
