### ISSUE TITLE
How to observe that the scrolling ended ？

### ISSUE THREAD

**Issue by dzqleo** [barteksc/AndroidPdfViewer#69]
I  would like to use a textveiw to show the current page and the page count like  10/80, and dismiss it when the scroll ends.   But i can not find any method to observe the scrollEnd.  How could i do this?

**Comment by dzqleo** [comment]
i've solved this issue by creating a runnable to observe the scroll time . Thanks any way~

**Comment by barteksc** [comment]
Sorry, I will add some scroll callback in future version.
