### ISSUE TITLE
Fatal Signal

### ISSUE THREAD

**Issue by elsennov** [barteksc/AndroidPdfViewer#7]
Hi, sometimes i got this error:
```
A/libc: Fatal signal 11 (SIGSEGV) at 0xffffffff (code=1), thread 16929 (AsyncTask #5)
```
This happened after i open -> exit -> reopen -> exit -> reopen... the activity.
This caused the activity to exit.

**Comment by barteksc** [comment]
@elsennov please check if version 1.1.0 fixes this issue

**Comment by elsennov** [comment]
@barteksc ok

**Comment by elsennov** [comment]
Seems it has been solved. No crash occurred! Thanks @barteksc
