### ISSUE TITLE
Disable Continuouse Scrolling

### ISSUE THREAD

**Issue by GanbaruTobi** [barteksc/AndroidPdfViewer#70]
Is there a way to get the behaviour of full pages swipe and still work with the actual branch?

For me, it is pretty unhandy to center every page.
This was the default before the improved rendering update
Any suggestions?

Thanks in advance

**Comment by barteksc** [comment]
Rendering engine has been built from scratch, only way is to use previous version. I'll consider adding old behavior, but it will require some work.

**Comment by GanbaruTobi** [comment]
Thank you for the feedback.
I like continuous scroll for vertical reading, but right now horizontal reading/swiping is preferred. 
There, it doesn't make sense to me.

I will stick with the old version for now.

**Comment by theebi** [comment]
Hai,
Is the swipe feature available in the version2?

**Comment by 1stmetro** [comment]
V2 has swipes both ways.

**Comment by theebi** [comment]
Thanks for the quick reply. But it does scroll through the pages. Isn't there any function to just swipe to the next page?

**Comment by 1stmetro** [comment]
A scroll and a swipe? If you scroll it changes page so what will a swipe do that's different to what a scroll does?

**Comment by barteksc** [comment]
@theebi No, there is no such feature. And please don't write in closed issues
