### ISSUE TITLE
After zoom by gesture,I found it always flash from some black bold linevery obviously into the right text 

### ISSUE THREAD

**Issue by ragerous** [barteksc/AndroidPdfViewer#708]
After zoom by gesture,I found it always flash from some black bold line very obviously into the right text .Can i disable or remove the process of the blur black img?

**Comment by ragerous** [comment]
found the answer ,it's the THUMBNAIL imgs

**Comment by AlexandrePhilibert** [comment]
I might have the same issue as you, can you please explain a bit more what did you change to make this flash disappear ?

**Comment by ragerous** [comment]
you can either disable the drawing of thumbnail or increase it's quality.
