### ISSUE TITLE
Reading from android PdfDocument 

### ISSUE THREAD

**Issue by kellyrose0902** [barteksc/AndroidPdfViewer#71]
Hi, 
Is it possible to read directly from an PdfDocument object? I find the when I'm generating large pdf file, it take a lot of time to just save it to storage. My case just required reading and no saving the document. 
Thanks

**Comment by isolpak1** [comment]
What code are you using to save it to storage, kindly share..

**Comment by barteksc** [comment]
There is no possibility of accessing PdfDocument.
Files from assets must be copied to cache for some reason, code is in [FileUtils.java](https://github.com/barteksc/AndroidPdfViewer/blob/master/android-pdf-viewer/src/main/java/com/github/barteksc/pdfviewer/util/FileUtils.java)

**Comment by kellyrose0902** [comment]
Thanks, it's a great library btw!
