### ISSUE TITLE
Support For implementation instead of compile 

### ISSUE THREAD

**Issue by akm5** [barteksc/AndroidPdfViewer#720]
Google is going to stop support for compile in gradle and it is restricted to use implementation from jan2019 
is their any update with this issue? need help regarding this.      Thank you.

**Comment by jdepypere** [comment]
@akm5 The `build.gradle` files in this project already use implementation. In your own `build.gradle` you can just use `implementation 'com.github.barteksc:android-pdf-viewer:x.x.x'` without issues. The readme isn't up to date.

**Comment by akm5** [comment]
Hi, @jdepypere Thank you for update I tested with using implementation it's worked successfully. Thank you :+1:
