### ISSUE TITLE
Load a range of pages

### ISSUE THREAD

**Issue by AmeenAhmed1** [barteksc/AndroidPdfViewer#735]
Hello, 
There is a way to give a page range like [ from 1 to 20 ] to be only loaded?! 

Because
pdf.pages(2,3,4,5);   only load spescific pages.

Thanks in advance.

**Comment by Omrankabalan** [comment]
Hello Ameen,

Yes you can achieve that,
Example using Kotlin:
`val range =  1.rangeTo(20).toList()`
...
` .pages(*range.toIntArray())` 
...

**Comment by AmeenAhmed1** [comment]
> Hello Ameen,
> 
> Yes you can achieve that,
> Example using Kotlin:
> `val range = 1.rangeTo(20).toList()`
> ...
> ` .pages(*range.toIntArray())`
> ...

Thank you, Omran.

**Comment by DrRO** [comment]
That's great solution
But I need the same solution in java
