### ISSUE TITLE
Hide/Show Annotations Function

### ISSUE THREAD

**Issue by oceanwaves90** [barteksc/AndroidPdfViewer#746]
Hiding/showing the annotations on a page or all the page is needed..

And I tried implementing the function, but it seemed difficult since it may be required to create the thumbnail again and render the parts. (How to refresh a page/all pages?)

Do you have any simple ideas for this? please help me!

**Comment by oceanwaves90** [comment]
I implemented it by ignoring the checkpoint of whether PageParts were loaded before, when I need to reload the page.

**Comment by Drakot** [comment]
What's PageParts?
