### ISSUE TITLE
Help required with fromFile function

### ISSUE THREAD

**Issue by brainstorm-ash** [barteksc/AndroidPdfViewer#747]
I am having trouble displaying pdf files using fromFile function. 
I followed the following steps to display a pdf file from local storage. 
1. Added user permissions in Android Manifest. 
2. Added PDFView on the main_activity.xml file
3. Created file variable and assigned file path/address.
4. Used fromFile(path).load() to display PDF.

I can display pdf files from the Assets folder. 

Any input would be appreciated.

**Comment by YuriyBereguliak** [comment]
Hi.
If you want load pdf file from assets folder you should use `fromAsset` method instead `fromFile`.

**PDFView class** :
> /** Use an asset file as the pdf source */
    public Configurator fromAsset(String assetName) {
        return new Configurator(new AssetSource(assetName));
    }

**Example**:
>         view.fromAsset(assetName)
>                 .onLoad(new OnLoadCompleteListener() {
>                     @Override
>                     public void loadComplete(int nbPages) {
>                         Log.d(TAG, "Load complete :: " + nbPages);
>                     }
>                 })
>                 .onPageChange(new com.github.barteksc.pdfviewer.listener.OnPageChangeListener() {
>                     @Override
>                     public void onPageChanged(int page, int pageCount) {
>                         Log.d(TAG, "Page changed :: " + page);
>                     }
>                 })
>                 .swipeHorizontal(true)
>                 .pageSnap(true)
>                 .autoSpacing(true)
>                 .pageFling(true)
>                 .load();

**Comment by brainstorm-ash** [comment]
Thank you for your response. I did not provide access to storage permission to the application on my device.
