### ISSUE TITLE
Pdf not loading from local storage

### ISSUE THREAD

**Issue by kartikj07** [barteksc/AndroidPdfViewer#762]
I tried loading a sample pdf from apps private storage directory as my application already has the pdf downloaded there. The issue is that the pdf is not opening and always displays a blank screen. Below is how I am trying to load the pdf from my apps internal storage
`try {
            val pdfFile = File(this.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS), "10.pdf")
            pdfView.fromFile(pdfFile).load()
        } catch (e: Exception) {
            e.printStackTrace()
        }`

**Comment by CoolMind** [comment]
Thanks for `.load()`! I also had blank screen until added that command.
