### ISSUE TITLE
Problem with crash of AndroidPdfViewer when reloanching activity after closing using finish()

### ISSUE THREAD

**Issue by jclev** [barteksc/AndroidPdfViewer#77]
I am having a problem where if I have a app that displays multiple PDFs using different icons. 

So you have one activity with some icons that each launch an activity that displays a PDF activity that gets the name of the pdf from the Bundle extras = getIntent().getExtras(); It then displays the pdf pdfView.fromAsset(pdf)
                        .defaultPage(0)
                        .enableAnnotationRendering(false)
                        .onLoad(this)
                        .load();

You then can close out of the pdf by clicking a close button that calls finish(); 
Now if you click the same pdf again it with then crash the app and sometimes the activity. With this error 
E/com.shockwave.pdfium.PdfiumCore: mContext may be null

This is on android 4.1.1 
pdf size is 266 KB

08-24 13:05:37.338 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.338 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.338 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.338 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.338 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.338 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.338 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.338 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.338 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.338 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.348 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.348 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.348 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.348 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.348 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.348 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.348 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.348 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.348 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.348 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.348 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.348 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.348 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.348 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.358 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.358 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.358 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.358 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.358 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.358 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.358 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.358 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.358 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.358 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.358 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.358 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.358 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.358 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.358 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.358 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.358 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.358 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.358 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.358 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.368 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.368 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.368 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.368 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.368 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.368 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.368 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.368 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.368 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.368 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.368 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.368 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.368 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.368 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.368 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.368 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.398 21865-21866/ D/dalvikvm: GC_CONCURRENT freed 1843K, 23% free 13239K/17159K, paused 12ms+2ms, total 30ms
08-24 13:05:37.398 21865-28104/ D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 8ms
08-24 13:05:37.398 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.408 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.408 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.408 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.408 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.408 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.408 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.408 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.408 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.408 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.408 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.408 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.408 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.408 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.408 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.418 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.418 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.418 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.418 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.418 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.418 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.418 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.418 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.418 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.418 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.418 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.418 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.418 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.418 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.418 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.428 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.428 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.428 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.428 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.428 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.428 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.428 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.428 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.428 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.428 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.428 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.428 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.448 21865-21866/ D/dalvikvm: GC_CONCURRENT freed 1967K, 23% free 13237K/17159K, paused 3ms+2ms, total 20ms
08-24 13:05:37.448 21865-28104/ D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 18ms
08-24 13:05:37.448 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.448 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.448 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.448 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.448 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.448 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.448 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.448 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.448 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.448 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.448 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.448 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.448 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.448 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.448 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.448 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.448 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.448 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.458 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.458 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.458 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.458 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.458 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.458 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.458 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.458 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.458 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.458 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.458 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.458 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.458 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.468 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.468 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.468 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.468 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.468 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.468 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.468 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.468 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.468 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.468 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.468 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.498 21865-21866/ D/dalvikvm: GC_CONCURRENT freed 1966K, 23% free 13237K/17159K, paused 12ms+3ms, total 29ms
08-24 13:05:37.498 21865-28104/ D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 14ms
08-24 13:05:37.498 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.498 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.498 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.498 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.498 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.498 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.498 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.498 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.498 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.498 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.498 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.498 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.508 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.508 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.508 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.508 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.508 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.508 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.508 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.508 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.508 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.508 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.508 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.508 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.508 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.508 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.508 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.508 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.508 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.508 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.508 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.508 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.508 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.508 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.508 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.518 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)
08-24 13:05:37.518 21865-28104/ E/com.shockwave.pdfium.PdfiumCore: mContext may be null
08-24 13:05:37.518 21865-28104/ W/System.err: java.lang.NullPointerException
08-24 13:05:37.518 21865-28104/ W/System.err:     at com.shockwave.pdfium.PdfiumCore.renderPageBitmap(PdfiumCore.java:216)
08-24 13:05:37.518 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:123)
08-24 13:05:37.518 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:77)
08-24 13:05:37.518 21865-28104/ W/System.err:     at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:34)
08-24 13:05:37.518 21865-28104/ W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-24 13:05:37.518 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-24 13:05:37.518 21865-28104/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-24 13:05:37.518 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-24 13:05:37.518 21865-28104/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-24 13:05:37.518 21865-28104/ W/System.err:     at java.lang.Thread.run(Thread.java:856)

**Comment by Yayo-Arellano** [comment]
I have a similar error. But it happens when i swap fragments that display pdf.

**Comment by jclev** [comment]
Found this in the log file today.

Skipped 161 frames!  The application may be doing too much work on its main thread.

**Comment by barteksc** [comment]
Check version 2.0.2, it should fix this problem

**Comment by jclev** [comment]
It don't seem to be crashing at all now. Thank you for the fix!
