### ISSUE TITLE
No content provider: https://pg.ipc.am/assetic/android_files/Simple.pdf

### ISSUE THREAD

**Issue by sench93** [barteksc/AndroidPdfViewer#78]
I have issue with loading pdf from URI. i will post my code snippet below. I how you will help me.

 Uri.Builder builder = new Uri.Builder();
        builder.scheme("https")
                .authority("pg.ipc.am")
                .appendPath("assetic")
                .appendPath("android_files")
                .appendPath("Simple.pdf");
        Uri uri = builder.build();
        if(uri!=null){

            pdfView.fromUri(uri)
                    .enableSwipe(true)
                    .swipeHorizontal(false)
                    .enableDoubletap(true)
                    .defaultPage(0)
                    //.onDraw(onDrawListener)
                    // .onLoad(onLoadCompleteListener)
                    // .onPageChange(onPageChangeListener)
                    // .onPageScroll(onPageScrollListener)
                    // .onError(onErrorListener)
                    .enableAnnotationRendering(false)
                    .password(null)
                    .scrollHandle(null)
                    .load();
        }
```

**Comment by sench93** [comment]
any link i use, returns the same exception . . .

**Comment by barteksc** [comment]
Library does not support remote files, you have to download it by yourself.
