### ISSUE TITLE
android10 cannot create document: File not in PDF format or corrupted.

### ISSUE THREAD

**Issue by xmc-w** [barteksc/AndroidPdfViewer#842]
![QQ图片20191204172522](https://user-images.githubusercontent.com/15245322/70130243-2691b480-16bb-11ea-99f2-f57f9ca6e55a.png)

**Comment by CoolMind** [comment]
@xmc-w, does it depend on device, PDF file?

**Comment by xmc-w** [comment]
> @xmc-w, does it depend on device, PDF file?

Not dependent, I tested on some devices running android10, and not for a pdf file, I got this error

**Comment by CoolMind** [comment]
@xmc-w, thanks! Please, say, if you add error callbacks, are they called?

    pdf_view.fromFile(file)
        .onError { t -> throw IllegalStateException("Error") }
        .onPageError { page, t -> throw IllegalStateException("PageError") }
        .load()

If they invoke, you can open in an external app.

**Comment by xmc-w** [comment]
Thanks, I found that it is a file download problem. The file download failed on android10, causing the open to fail.
