### ISSUE TITLE
PDF not rendering properly

### ISSUE THREAD

**Issue by dbotelho** [barteksc/AndroidPdfViewer#85]
Hi, 

This is what I get when I try to load this file [Teste.pdf](https://github.com/barteksc/AndroidPdfViewer/files/451576/Teste.pdf) in the Nexus 9 Emulator (Android 6.0):
<img width="641" alt="screen shot 2016-09-02 at 10 00 40" src="https://cloud.githubusercontent.com/assets/248831/18198493/3e1c9eb4-70f4-11e6-9ef0-058f5ce056dc.png">

What can I do to load it properly?

Best regards

**Comment by barteksc** [comment]
Pdfium version used in this library has some problem with non-standard fonts, unfortunately it cannot be fixed.

**Comment by dbotelho** [comment]
Ok.

FYI it works with both https://github.com/JoanZapata/android-pdfview and also https://developer.android.com/reference/android/graphics/pdf/PdfRenderer.html (on Android OS 5+) so I thought it was some fixable issue.

**Comment by barteksc** [comment]
Version 2.5.0 updated PdfiumAndroid to 1.6.0, which depends on freetype, it may fix fonts problems
