### ISSUE TITLE
Question: Is it possible to load pdf from binary data?

### ISSUE THREAD

**Issue by GoltsevEugene** [barteksc/AndroidPdfViewer#87]
It would be very nice option, cuz now I should save it to File first.
Thanks.

**Comment by paperrose** [comment]
Yes, I agree with TS it'll be very useful feature.
I already saw the function "FPDF_LoadMemDocument" in pdfium that can load pdf from bytes and can be used instead of "FPDF_LoadCustomDocument".

**Comment by misaghE** [comment]
I really need this feature.
For security reasons I don't want to save my byte array in a file.

**Comment by barteksc** [comment]
@misaghE you can send pull request. Older versions of PdfiumAndroid used FPDF_LoadMemDocument, but it didn't work good.

**Comment by paperrose** [comment]
@barteksc 
Tried to add FPDF_LoadMemDocument.
That solved my issue but I had one problem with open pages cause ptrs were NULL.
Just replaced one page opening to all pages and it works!

**Comment by contrudar** [comment]
can anyone show an example how to view a pdf when you have a byte array and can't save it as a file on a disk?

**Comment by barteksc** [comment]
Version 2.3.0 introduced possibility of loading documents from binary data.
