### ISSUE TITLE
 increases app size greatly 

### ISSUE THREAD

**Issue by rastha67** [barteksc/AndroidPdfViewer#88]
Adding dependency increases app size greatly (from 4 mb to 20.6 mb) .
How to reduce it?

**Comment by LuigiCapasso** [comment]
Read this section https://github.com/barteksc/AndroidPdfViewer#why-resulting-apk-is-so-big
;)

**Comment by PeterPo** [comment]
You can have a look at this PDF viewer if you want to keep down the size. It can publish as a PhoneGap app so it may be an alternative: 

https://flowpaper.com/demo/
