### ISSUE TITLE
App crashing after downloading from play store due to JNI DETECTED ERROR IN APPLICATION: java_class == null'

### ISSUE THREAD

**Issue by toralabs** [barteksc/AndroidPdfViewer#897]
I used the latest version of this library and app was working fine in debug and release mode but when I downloaded it from play store it was crashing in almost all devices. But the same thing was working with one of the apps but the rest of them were crashing as soon as the pdfViewer activity is launched.

`* * * * * * * * * * * * * * * *
Build fingerprint: 'xiaomi/lavender/lavender:9/PKQ1.180904.001/V11.0.9.0.PFGINXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 16710, tid: 16800, name: AsyncTask #1  >>> com.toralabs.phynotes <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: java_class == null'
    x0  0000000000000000  x1  00000000000041a0  x2  0000000000000006  x3  0000000000000008
    x4  0000007d79d4b000  x5  0000007d79d4b000  x6  0000007d79d4b000  x7  0000000000640e42
    x8  0000000000000083  x9  cf122f23716b8247  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 0000000000000140  x14 0000000000000000  x15 0000007d77ee8000
    x16 0000007d77edc2b0  x17 0000007d77dfbcd0  x18 0000000000000010  x19 0000000000004146
    x20 00000000000041a0  x21 0000007ce42322c0  x22 0000000000000058  x23 0000007cf378d443
    x24 0000007cf378d2f7  x25 0000000000000001  x26 0000007cd33dba00  x27 000000000000005b
    x28 0000007cf3ead720  x29 0000007cd33db8b0
    sp  0000007cd33db870  lr  0000007d77def144  pc  0000007d77def16c

backtrace:
    #00 pc 000000000002216c  /system/lib64/libc.so (abort+116)
    #01 pc 0000000000465684  /system/lib64/libart.so (art::Runtime::Abort(char const*)+1196)
    #02 pc 0000000000008ce0  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+724)
    #03 pc 00000000002e5ec8  /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1640)
    #04 pc 0000000000332cd8  /system/lib64/libart.so (art::JNI::GetMethodID(_JNIEnv*, _jclass*, char const*, char const*)+1464)
    #05 pc 0000000000004620  /data/app/com.toralabs.phynotes-Z_f-RHXNFgqF3C8m1UMVKw==/split_config.arm64_v8a.apk (offset 0xf7000) (Java_com_shockwave_pdfium_PdfiumCore_nativeGetPageSizeByIndex+328)
    #06 pc 000000000003f704  /data/app/com.toralabs.phynotes-Z_f-RHXNFgqF3C8m1UMVKw==/oat/arm64/base.odex (offset 0x3f000) (com.shockwave.pdfium.PdfiumCore.nativeGetPageSizeByIndex+148)
    #07 pc 000000000004973c  /data/app/com.toralabs.phynotes-Z_f-RHXNFgqF3C8m1UMVKw==/oat/arm64/base.odex (offset 0x3f000) (com.shockwave.pdfium.PdfiumCore.b+124)
    #08 pc 0000000000044d90  /data/app/com.toralabs.phynotes-Z_f-RHXNFgqF3C8m1UMVKw==/oat/arm64/base.odex (offset 0x3f000) (c.b.a.a.f.<init>+944)
    #09 pc 00000000000443d8  /data/app/com.toralabs.phynotes-Z_f-RHXNFgqF3C8m1UMVKw==/oat/arm64/base.odex (offset 0x3f000) (c.b.a.a.c.doInBackground+568)
    #10 pc 0000000001bd92cc  /system/framework/arm64/boot-framework.oat (offset 0xa43000) (android.os.AsyncTask$2.call+172)
    #11 pc 00000000008ee94c  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.util.concurrent.FutureTask.run+204)
    #12 pc 0000000000a7b1c4  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.util.concurrent.ThreadPoolExecutor.runWorker+996)
    #13 pc 0000000000a77250  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
    #14 pc 00000000005574c8  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.lang.Thread.run+72)
    #15 pc 0000000000557388  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #16 pc 00000000000cfcc8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #17 pc 000000000045dd7c  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #18 pc 000000000045ee38  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
    #19 pc 0000000000489d28  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
    #20 pc 0000000000090328  /system/lib64/libc.so (__pthread_start(void*)+36)
    #21 pc 0000000000023a28  /system/lib64/libc.so (__start_thread+68)`

I have also included the proguard rule `-keep class com.shockwave.**`  in proguard-rules.pro
Please help me ....

**Comment by JantuDeb** [comment]
Maybe you didn't define the pro-guard rule.

**Comment by 1stmetro** [comment]
The simple answer, get the app on firebase and run the app in the test lab it will show you what is crashing and where and it will easier to locate the issue,

I recently had an app where i used a " in the manifest i believe and not a ' , the app ran fine in development but crashed when tested outside of development, so i found the issue in minutes in the test lab, if its a certain device you can run your app on different devices...

**Comment by suryachandrabeeram** [comment]
I am Also Getting Same Issue

i used These Rule
-keep class com.shockwave.**

@ for implementation 'com.github.barteksc:android-pdf-viewer:3.2.0-beta.1'

**Comment by JantuDeb** [comment]
> I am Also Getting Same Issue
> 
> i used These Rule
> -keep class com.shockwave.**
> 
> @ for implementation 'com.github.barteksc:android-pdf-viewer:3.2.0-beta.1'

It should work if you are using this rule... I haven't face any issues..

**Comment by suryachandrabeeram** [comment]
Late-enabling -Xcheck:jni
The ClassLoaderContext is a special shared library.
I/Perf: Connecting to perf service.
MultiDex: VM with version 2.1.0 has multidex support
MultiDex: Installing application
MultiDex: VM has multidex support, MultiDex support library is disabled.
MultiDex: Installing application
MultiDex: VM has multidex support, MultiDex support library is disabled.
DynamiteModule: Considering local module com.google.android.gms.measurement.dynamite:14 and remote module com.google.android.gms.measurement.dynamite:0
DynamiteModule: Selected local version of com.google.android.gms.measurement.dynamite

**Comment by suryachandrabeeram** [comment]
2020-06-13 00:22:08.906 12484-12484/? A/linker: CANNOT LINK EXECUTABLE "/system/bin/dpmd": "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit

**Comment by JantuDeb** [comment]
> 2020-06-13 00:22:08.906 12484-12484/? A/linker: CANNOT LINK EXECUTABLE "/system/bin/dpmd": "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit

Did you upload App Bundle or Apk in Play Store?

**Comment by toralabs** [comment]
> Maybe you didn't define the pro-guard rule.

Yes you are right. This was the reason of crashing...
I added proguard rule  and it was working completely fine after downloading from playstore.
