### ISSUE TITLE
插件形式加载

### ISSUE THREAD

**Issue by shingohu** [barteksc/AndroidPdfViewer#9]
能否通过插件的形式集成 在需要的时候下载下来

**Comment by barteksc** [comment]
Please write in english, so that people (including me) can understand it

**Comment by shingohu** [comment]
i am sorry 
Can support similar plug-in, download and use in time of need

**Comment by FabianTerhorst** [comment]
@shingohu you can extends the pdfiumcore to use System.load(/*path to downloaded so file*/). You have to host the "so" file on a server, so that the app can download it.
