### ISSUE TITLE
How to clear the pdfView 

### ISSUE THREAD

**Issue by Zderosia** [barteksc/AndroidPdfViewer#907]
I'm trying to make the current PDF disappear when beginning to load a new PDF. I've searched for a .clear() function or something along those lines, but I can't find anything. Would there happen to be any functions or other, more roundabout, methods to do this?

**Comment by 1stmetro** [comment]
recycle(); seems familiar, although i would generally close the activity and reload with a new pdf rather than reusing i just find it more fluid to the user.
