### ISSUE TITLE
UnsatisfiedLinkError: couldn't find "libmodpdfium.so"

### ISSUE THREAD

**Issue by bhushand** [barteksc/AndroidPdfViewer#91]
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.edcast-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libmodpdfium.so"
java.lang.Runtime.loadLibrary(Runtime.java:366)
java.lang.System.loadLibrary(System.java:989)
com.shockwave.pdfium.PdfiumCore.<clinit>(PdfiumCore.java:19)
com.github.barteksc.pdfviewer.PDFView.<init>(PDFView.java:275)
java.lang.reflect.Constructor.newInstance(Native Method) 
java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
android.view.LayoutInflater.createView(LayoutInflater.java:607) 
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
com.edcast.feature.pdfViewer.view.activity.PDFViewerActivity.onCreate(PDFViewerActivity.java:45) 
android.app.Activity.performCreate(Activity.java:5933) 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251) 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
android.app.ActivityThread.access$800(ActivityThread.java:144) 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
android.os.Handler.dispatchMessage(Handler.java:102) 
android.os.Looper.loop(Looper.java:135) 
android.app.ActivityThread.main(ActivityThread.java:5221) 
java.lang.reflect.Method.invoke(Native Method) 
java.lang.reflect.Method.invoke(Method.java:372)

**Comment by lezardos** [comment]
Hi,

You should probably provide some information about the device on which this issue appears.

**Comment by barteksc** [comment]
Closing due to lack of information
