### ISSUE TITLE
ScrollHandle Icon over the toolbar

### ISSUE THREAD

**Issue by Naresh-Katta** [barteksc/AndroidPdfViewer#92]
Page Indicator of scroll handle is over the toolbar
![device-2016-09-16-194906](https://cloud.githubusercontent.com/assets/7877291/18589251/6b85e67c-7c47-11e6-8eb1-d98ff67404c3.png)

leaving the same space at the end of view

![device-2016-09-16-195052](https://cloud.githubusercontent.com/assets/7877291/18589252/6b8b29fc-7c47-11e6-81c0-bbd8c259148e.png)

My layout file is:

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
    
        <include layout="@layout/tool_bar" />

        <com.github.barteksc.pdfviewer.PDFView
            android:id="@+id/pdfView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@+id/toolbar" />
        
    </RelativeLayout>

**Comment by barteksc** [comment]
Fixed in version 2.1.0

**Comment by engkungs** [comment]
how to use
