### ISSUE TITLE
click listener on PdfView

### ISSUE THREAD

**Issue by janvde** [barteksc/AndroidPdfViewer#94]
On version 1.3.0 is was possible to set a click listener on the pdfView. From version 2.x.x this is no longer possible, probably because of the new scroll handler which consumes the touch events. Is it possible to add a clicklistener to the pdfView again? Thanks!

**Comment by Yayo-Arellano** [comment]
My solution to be able to set a clicklistener was setting on touchlistener and return false after this when i set the clicklistener i will get callbacks.;

` pdfView.setOnTouchListener(new View.OnTouchListener() {
                @Override
                public boolean onTouch(View view, MotionEvent motionEvent) {
                    return false;
                }
            });`

**Comment by janvde** [comment]
Tried that, but now I can't scroll by swiping. The scroll handler still works though.

**Comment by Yayo-Arellano** [comment]
I see. I just need to display one page pdf thats why i did not notice this problem.

**Comment by barteksc** [comment]
Fixed in 2.3.0
