### ISSUE TITLE
How can i select text in pdfview?

### ISSUE THREAD

**Issue by aeniserkaya** [barteksc/AndroidPdfViewer#95]
Hi, thanks for this library.
I want to select Words in pdf view.
Is it possible? How? 
Thanks.

**Comment by barteksc** [comment]
No, there is no such possibility.

**Comment by KnIfER** [comment]
why?googl pdf viewer can do this(i think it is from chrome browser)

**Comment by barteksc** [comment]
Selecting text is not implemented. Pdfium is pdf renderer, it doesn't have any user interaction by itself.

**Comment by KnIfER** [comment]
no...I am working on it right now..
the functionalities are in those .so libraries,and i just need to jni call them,according to their .h headers.
(mainly fpdf_text.h)
by now I have managed to extract one letter from page 1 when I tap a screen position.
but the coordinate system is frustrating......I cannot extract text on other pages accurately.

**Comment by KnIfER** [comment]
to achieve that,I must fetch each page's coordinate origin by pageNumber.

on the other hand,do you know the spacing length between two page? @barteksc

**Comment by jojonarte** [comment]
@KnIfER hey have you managed to solve the selection problem?

**Comment by homeautomationsys** [comment]
fpdf_text.h has all the APIs needed to implement text selection in pdfium.

**Comment by KnIfER** [comment]
It's three years later and I am more experienced and since pdfium is more powerful than ever so I am determined to seriously implement text selection !

**Comment by KnIfER** [comment]
https://www.jianshu.com/p/6a2ccadc668d

**Comment by GayashanR** [comment]
Hi,
Just a suggestion.
You could use FPDFText_GetCharIndexAtPos API to get the index of the char
where the pointer is located(Do this for the OnPointerPressed,
OnPointerMoved and OnPointerReleased events). With theses indexes, You can
call FPDFText_CountRects and FPDFText_GetRect APIs to get the rectangles
where you want add selection rectangles. You can use platform specific
methods to add rectangles on top of the PDF Bitmap Image to get the
selection effect.

Hope this helps.
Thanks
BR
Gayashan

**Comment by KnIfER** [comment]
This is what I am doing. But there is a problem. The rectangles returned by `FPDFText_CountRects` are too scattered, not line by line.

Also the underlying mechanism is not perfect comparing to ezpdf reader. Sometimes there is a hole in the seletion...

**Comment by KnIfER** [comment]
Magnifier， I'm doing my best !

![SVID_20201112_171449_1_SchivoNo 0_GifNo 1](https://user-images.githubusercontent.com/11593903/98921289-73f5e300-2514-11eb-9072-9d9584627e13.gif)

**Comment by GayashanR** [comment]
Hi,
I'm really impressed with what you have done. I also added text selection
features to one of my windows PDF viewer applications.
Now I'm trying to build a PDF viewer application with text selection
features. But I'm not much familiar with android. Could you please give me
some guidance?
  From the link that you have provided, I got to a PolymPic project. I'm
having troubles building it and it is combined with web browser project as
well. Is there a way to just build a PDF viewer with selection
functionalities?

Thanks in advance
Best Regards
Gayashan

**Comment by tadie** [comment]
hi folks,
is there any other alternative pdfviewer source for text selection and copy?

**Comment by Shubhgajj2004** [comment]
@KnIfER Could please share your full java code?

**Comment by theGBguy** [comment]
@Shubhgajj2004 You can check this comment for code: https://github.com/barteksc/AndroidPdfViewer/issues/224#issuecomment-725190413

**Comment by theGBguy** [comment]
@tadie Another source where pdf text selection is enabled is https://gitlab.com/axet/android-book-reader
