### ISSUE TITLE
How to make PdfViewer refresh/reload the pdf page

### ISSUE THREAD

**Issue by HamidrezaAmz** [barteksc/AndroidPdfViewer#964]
Hey guys ;)
I am implementing a pdf editor.
I have made my changes on pdf files with [https://github.com/LibrePDF/OpenPDF](OpenPdf) core that is based on iText.
My problem is the Pdf is not refreshable after adding changes (annotations).
I have tested all these functions:

- pdfView.recycle();
- pdfView.loadPages();
- pdfView.invalidate();
- pdfView.loadPages();
- pdfView.refreshDrawableState();

Non of the above functions worked!

Here is my code

```java
 pdfView.fromUri(uri)
                .defaultPage(pageNumber)
                .onPageChange(this)
                .enableAnnotationRendering(true)
                .onLoad(this)
                .enableSwipe(true)
                .scrollHandle(new DefaultScrollHandle(this))
                .spacing(10) // in dp
                .onPageError(this)
                .onTap(new OnTapListener() {
                    @Override
                    public boolean onTap(MotionEvent e) {
                        // here we have a tap
                        Log.i(TAG, "onTap --> X: " + e.getX() + " | Y: " + e.getY());
                        Log.i(TAG, "onTap --> ScaleX: " + pdfView.getScaleX() + " | ScaleY: " + pdfView.getY());
                        Log.i(TAG, "--------------------------------------------------");

                        try {
                            
                            String filePath = UriUtils.getPathFromUri(PDFViewActivity.this, uri);
                            PDFDrawer.DrawLine(filePath); // here I insert sth new into pdf
                            
                            // here I need to refresh the pdf page
                            // ...

                        } catch (FileNotFoundException fileNotFoundException) {
                            fileNotFoundException.printStackTrace();
                        }
                        return false;
                    }
                })
                .load();
```

Is there any ways to make the pdf page reload/refresh after adding new changes?

any help **appreciated**

**Comment by Drakot** [comment]
After first loading the document save the config instance (PDFView.Configurator) on a class variable. 

Then call this 2 lines:

```
pdfConfig?.defaultPage(pdfView.currentPage)
pdfConfig?.load()
```

The problem with this it loads the whole document and then positions to the current page so it's very slow, but its the only way I did reload the document.

**Comment by HamidrezaAmz** [comment]
Hey guys, according to my issue, I have create a new repository and added my research results into it.
I have added some base functionalities like refresh or update pdf , add and remove annotations and etc.
check it out here in [MagicalPdfEditor](https://github.com/HamidrezaAmz/MagicalPdfEditor)

**Comment by SweetD3v** [comment]
> After first loading the document save the config instance (PDFView.Configurator) on a class variable.
> 
> Then call this 2 lines:
> 
> ```
> pdfConfig?.defaultPage(pdfView.currentPage)
> pdfConfig?.load()
> ```
> 
> The problem with this it loads the whole document and then positions to the current page so it's very slow, but its the only way I did reload the document.

You can do it faster by doing this.

- save the value of last selected page using onPageChanged() method, then while loading the pdf again, pass that value in configurator's defaultPage() method, and it will jump to the page in no time!

**Comment by ramu2514** [comment]
This is not the right answer. It will cause zoom to loss & flicker to happen
