### ISSUE TITLE
How to convert the screen coordinate to pdf page coordinates ?

### ISSUE THREAD

**Issue by hehonghui** [barteksc/AndroidPdfViewer#999]
I want to implement text selection, the key step is:

1. the user touch the screen, and i get the screen coordinates;
2. convert screen coordinates to page coordinates
3. get text from current page with coordinates

But i can't get the right page coordinates, so that i get the correct text. Anyone can share some workaround ?

**Comment by taichushouwang** [comment]
@hehonghui hi, I have the same demand with you, can you tell me, how do you solve it?
